### ISSUE TITLE
QQ群加不了

### ISSUE THREAD

**Issue by imliujun** [wequick/Small#1]
不知道是不是mac版QQ的问题，点QQ群图标加不了群。改成QQ群号码吧。。
文档这一块希望能够出一个从新建项目到集成Small框架的流程说明。

**Comment by galenlin** [comment]
你好，感谢您的建议。页面已增加群号码。Quick Start正在写，请先看下Sample工程。

**Comment by Ivonhoe** [comment]
QQ群：374601844
