### ISSUE TITLE
buildLib第一次总是失败

### ISSUE THREAD

**Issue by peacepassion** [wequick/Small#100]
前提条件：
1. 包含多个Lib
2. strictSplitResources为true

现象：
第一次buildLib总是失败  
![image](https://cloud.githubusercontent.com/assets/5254121/14449386/f06b5e2c-00a4-11e6-9919-6d08b5dcb751.png)

然后再次buildLib就可以成功

原因：AppPlugin#configureReleaseVariant在project evaluate完毕之后就会执行，而这个时候，host还没有完成buildLib,也就没有app-D.txt文件  
![image](https://cloud.githubusercontent.com/assets/5254121/14449406/2adbd2b2-00a5-11e6-8ebe-7981256e1b88.png)
 这段代码收集到的dependentAAR就总为空。导致了第一次buildLib的失败，但是host的buildLib是已经成功的，app-D.txt就已经生成了。所以，第二次buildLib就能够成功。

**Comment by galenlin** [comment]
提交消息里带`fix #xx`会自动关闭issue 😂
