### ISSUE TITLE
宿主与插件之间如何共享资源

### ISSUE THREAD

**Issue by peacepassion** [wequick/Small#102]
插件之间可以通过lib.styles的形式做到资源共享，以lib.utils的形式做到代码共享。  

目前插件可以provided依赖到host的代码，可以使用host的代码。也可以通过host.R访问到host的资源。 

但是，插件目前却没有办法在资源文件里使用host的资源，比如说直接使用host的主题。  host目前也没有办法依赖到lib.styles，因为lib.styles在buildLib时会被转成application.  

所以，如何合理的达到宿主与插件共享资源呢？

**Comment by galenlin** [comment]
这一部分不在设计之中。

因为理论上，宿主应充分解耦，不应存在任何与业务相关的代码和资源。

**Comment by peacepassion** [comment]
got it.
