### ISSUE TITLE
启动后立即退出 - 多台手机测试 (三星，小米，Android Studio 2.0）

### ISSUE THREAD

**Issue by zijing07** [wequick/Small#105]
报的错如下，我定位不到错误，作者如果可以提供一个思路的话我可以帮着修哈。

> 04-14 14:52:49.972 4090-4090/net.wequick.example.small I/Adreno200-EGLSUB: <ConfigWindowMatch:2218>: Format RGBA_8888.
04-14 14:52:49.972 4090-4090/net.wequick.example.small D/memalloc: /dev/pmem: Mapped buffer base:0x51a6f000 size:17682432 offset:16146432 fd:55
04-14 14:52:50.082 4090-4090/net.wequick.example.small D/memalloc: /dev/pmem: Mapped buffer base:0x52b4c000 size:3072000 offset:1536000 fd:61
04-14 14:52:50.162 4090-4090/net.wequick.example.small D/OpenGLRenderer: Flushing caches (mode 0)
04-14 14:52:50.182 4090-4090/net.wequick.example.small D/memalloc: /dev/pmem: Unmapping buffer base:0x51a6f000 size:17682432 offset:16146432
04-14 14:52:50.192 4090-4090/net.wequick.example.small D/memalloc: /dev/pmem: Unmapping buffer base:0x52b4c000 size:3072000 offset:1536000
04-14 14:52:50.232 4090-4090/net.wequick.example.small D/CLIPBOARD: Hide Clipboard dialog at Starting input: finished by someone else... !
04-14 14:52:50.452 4090-4090/net.wequick.example.small D/OpenGLRenderer: Flushing caches (mode 2)

**Comment by addappcn** [comment]
me too

**Comment by peacepassion** [comment]
@zijing07 你贴的貌似不是crash log，都没看到small的调用栈。  

另外建议把机器、rom的具体信息贴出来。

**Comment by zijing07** [comment]
@peacepassion 我是用程序包名 net.wequick* 来过滤log的，然后就只有这么几句log，我也挺奇怪的……如果有调用栈的话，就比较容易定位错误了。

**Comment by zijing07** [comment]
@addappcn @peacepassion   弄好了，是因为我没有运行 buildLib & buildBundle，sorry，另外如果我想参与到开发中来，请问有什么可以上手的吗？

**Comment by peacepassion** [comment]
@zijing07 这个我也不知道呢。我也不是这个项目的team member。我目前是在尝试在公司项目里引入Small，遇到issue的话，就会到这里讨论，一直在watch这个项目。

**Comment by galenlin** [comment]
@all 提交Issue、Pull Request都可以参与到项目进来。

**Comment by galenlin** [comment]
我开了一个标签[Good First Task](https://github.com/wequick/Small/labels/Good%20First%20Task)，作为容易上手的功能点，可以上手改这些bug，提交PR。

**Comment by zijing07** [comment]
谢谢！
