### ISSUE TITLE
关于插件Activity在AndroidManifest中声明的属性的应用

### ISSUE THREAD

**Issue by wb31137** [wequick/Small#108]
关于插件中Activity在AndroidManifest文件中声明的一些属性，如configChanges，是否有什么好的处理方法？我试了下通过反射在运行时将Activity的属性mActivityInfo替换掉，虽然onConfigurationChanged被调用了，Activity仍然会被销毁重新创建。

**Comment by galenlin** [comment]
有些属性的读取与设置是在framework层完成的，似乎无法很好解决，只能预注册到宿主里

**Comment by wb31137** [comment]
嗯嗯，昨天跟踪了一下，对于这一点，暂时没找到ApplicationThread中接收到relaunch_activity 消息的来源。过后如果有找到再上来更新一下。

**Comment by galenlin** [comment]
ok
