### ISSUE TITLE
新建的lib.**包不一致会导致编译被忽略

### ISSUE THREAD

**Issue by xiaoxinxing12** [wequick/Small#110]
新建的lib.**包不一致会导致编译被忽略

比如：
lib.**包名为 com.xxx.a
引入别人代码 包名为  com.xxx.b

编译 com.xxx.b将被忽略

**Comment by galenlin** [comment]
哈 我刚自己提了这个issue #109

**Comment by galenlin** [comment]
@xiaoxinxing12 请更新gradle-small版本至0.6.0，看是否问题已解决。
