### ISSUE TITLE
为什么要使用last built id

### ISSUE THREAD

**Issue by peacepassion** [wequick/Small#113]
lib在切割资源的时候，会参考使用上次build生成的entries. 如下图：  
![image](https://cloud.githubusercontent.com/assets/5254121/14760834/d0365762-0980-11e6-878f-44ad4f2411dd.png)

这些entry是保存在lib.**/public.txt中的，而且cleanLib的时候不会清掉。 

没看懂这样做的目的何在？

**Comment by galenlin** [comment]
为了保证lib的资源id不变，从而可以独立更新而不影响任何有依赖它的app插件

**Comment by peacepassion** [comment]
![image](https://cloud.githubusercontent.com/assets/5254121/14766145/aa087474-0a31-11e6-8269-7cb892d2ee0c.png)

这段代码，应该是用来优化生成的R.class的吧，切除掉多余的资源entry。   
但是，是不是应该先做R$**.class的删除，再做javac的操作？

**Comment by peacepassion** [comment]
这个顺序确实已经反了，看反编译出来的结果。  
![image](https://cloud.githubusercontent.com/assets/5254121/14766231/6358d958-0a34-11e6-9fd8-71df56843c95.png)

R.class其实已经空了。  但为什么demo是OK的呢，是因为生成的R.java的内容都是final的，编译的时候直接替换为常量了。  
![image](https://cloud.githubusercontent.com/assets/5254121/14766239/9fe6cc2c-0a34-11e6-8b04-8653b5e7efd3.png)

但为什么使用v7这样的aar也没有问题呢？毕竟v7内部使用的时候，用的是aar项目生成的非final的id。应该是因为host内部依赖的了v7，因此，:app:aR的时候，将v7生成的R.class给完整无损的带上了。

**Comment by galenlin** [comment]
对 其实javac能顺利完成 R.java就功成身退了 那个顺序倒没注意过 需要测试下ant.javac是否也会生成R$

**Comment by galenlin** [comment]
aar的R.xx在build-small/pre-jar里，插件模块会自动provided其
