### ISSUE TITLE
Sample文档上里的问题

### ISSUE THREAD

**Issue by pscj** [wequick/Small#116]
1. bundle.json的创建路径不对，不应该是右键app模块，应该是右键app/src/main，在main上右键创建
2. `Small.setBaseUri("http://example.com/");
    Small.setUp(this, new net.wequick.small.Small.OnCompleteListener() {

        @Override
        public void onComplete() {
            Small.openUri("main", LaunchActivity.this);
        }
    });`
直接这么调会报个错，说需要调用preSetUp,，我在两行中添加了一行
`Small.preSetUp(getApplication());`
就正常了，也不知道是否应该这么搞

**Comment by galenlin** [comment]
@pscj 
1. 右键app模块也是可以的
2. `preSetUp`要放在宿主application里，以保证后台被杀重启后程序正常

另，现在创建工程有个快捷的方法：复制templates/activities/SmallLauncher到Android Studio模板路径，选择`@Small`模块即可自动配置好上述工程。

**Comment by pscj** [comment]
好的，多谢多谢
