### ISSUE TITLE
so文件重复打到了插件中

### ISSUE THREAD

**Issue by tcking** [wequick/Small#126]
**前提**
1.lib.base中`compile 'com.facebook.fresco:fresco:0.9.0'`  （fresco会使用so，支持armeabi,arm84_8a,armeabi-v7a,x86,x86_64，每个目录下6个so文件）
2.app.* 依赖此lib： `compile project(':lib.base')`

**问题**
反编译打出来的插件(lib*.so,app.*.so)，全部都包含了fresco的so文件

**期望**
只有直接引用的插件包含fresco的so，其他间接依赖的插件不拷贝此so

**Comment by 77jiang** [comment]
实测0.12.0版本的fresco。还是会把其中一个so（libimagepipeline.so）打到每一个包中。

**Comment by galenlin** [comment]
@77jiang 请使用新版`gradle-small:1.0.0-beta7`试下

**Comment by 77jiang** [comment]
可以了
