### ISSUE TITLE
启动插件时，如何指定Activity?

### ISSUE THREAD

**Issue by erhu** [wequick/Small#130]
启动插件时，如何指定Activity?
在 json 中可配置吗？

**Comment by peacepassion** [comment]
https://github.com/wequick/Small/blob/master/Android%2FSample%2Fapp%2Fsrc%2Fmain%2Fassets%2Fbundle.json 

'detail'下面有个rules字段

**Comment by maxwell-nc** [comment]
看这个https://github.com/wequick/Small/wiki/UI-route
rules下面可以定义，
      "rules": {
        "sub": ".YourActivity"
      }
wiki上写简写名称，不过我看好像写全称才能查找到，研究中

**Comment by galenlin** [comment]
@maxwell-nc `aarVersion`需要更新到新版`0.9.0`
