### ISSUE TITLE
新需求：合并插件中的metaData到宿主

### ISSUE THREAD

**Issue by tcking** [wequick/Small#134]
**场景**
有些第三方包将初始配置参数放在manifest的metaData标签中，初始化的时候直接读取其中的值：
``` xml
<meta-data
            android:name="apikey"
            android:value="12345678" />
```
``` java
ApplicationInfo localApplicationInfo = context.getPackageManager().getApplicationInfo(paramContext.getPackageName(), 128);
    
String key = localApplicationInfo.metaData.getString("apikey");
```
在small中只能在宿主中定义，或者通过java代码来设置初始值

**期望**
metaData能在插件的manifest中定义，插件安装的时候在直接put到宿主的metaData里面，这样第三方包的初始化能使用原来的方法进行，独立运行app.*时也可以。

**Comment by galenlin** [comment]
看起来要hook PackageManagerService的binder，重写getApplicationInfo方法。性价比不高呀。

**Comment by tcking** [comment]
能否在插件加载的时候直接把插件的`metaData` put 到宿主的`applicationInfo. metaData`里？

**Comment by galenlin** [comment]
使用`context.getApplicationInfo()`的方式貌似可以，取得是当前进程的缓存变量：`ActicityThread.mLoadedApk.mApplicationInfo`，可以按你说的方式修改。

但是通过`context.getPackageManager().getApplicationInfo(paramContext.getPackageName(), 128)`的方法就不行了。跟踪进去可以发现里面调用了`mPM.getApplicationInfo(xxx)`。这个方法跨进程了（在`system_process`里），控制不了。能做的只有替换`mPM`。参考[这里](http://weishu.me/2016/03/07/understand-plugin-framework-ams-pms-hook/)。
