### ISSUE TITLE
unspecified on project app resolves to an APK archive which is not supported as a compilation dependency

### ISSUE THREAD

**Issue by lihuapinghust** [wequick/Small#153]
我的工程有三个module
app(宿主) app.main lib.ui 

app依赖于lib.ui，app.main依赖于lib.ui
在执行./gradlew buildLib -q的时候出现了以下错误
bogon:mysmall lihuaping$ ./gradlew buildLib -q --stacktrace
[Small] building library 1 of 2 - app (0x7f)
[Small] building library 2 of 2 - lib.ui (0x31)
        [lib.ui] split aar classes...                                   [  OK  ]
Dependency mysmall:lib.ui:unspecified on project app resolves to an APK archive which is not supported as a compilation dependency. File: /Users/lihuaping/Documents/JD/Small/Android/mysmall/app/smallLibs/armeabi/libcom_example_mysmall_lib_ui.so
Dependency mysmall:lib.ui:unspecified on project app resolves to an APK archive which is not supported as a compilation dependency. File: /Users/lihuaping/Documents/JD/Small/Android/mysmall/app/smallLibs/armeabi/libcom_example_mysmall_lib_ui.so

原因是：宿主不能依赖lib module，
去掉app对lib.ui的依赖就行了

**Comment by galenlin** [comment]
👍

**Comment by jiezili** [comment]
大写的所以：宿主工程不能有任何依赖lib的动作....😢
