### ISSUE TITLE
插件无法通过网络方式进行更新问题

### ISSUE THREAD

**Issue by wjyin** [wequick/Small#156]
如题，我对app.detail进行过一些修改，想测试通过网络进行更新，提示更新成功，实际上是失败的，没有发现app.detai有被更新的迹象。更新的逻辑代码我是从Sample->app.home里面拷贝的。我确定app.detail有重新编译过，因为我再次运行宿主时是发现app.detail有改变的，所以我确定是通过网络进行更新导致的问题，测试机为Galaxy S6 Edge（Android 6.0.1）。
我还以为是这台手机的问题，于是我使用小米3进行测试（Android 4.4.4/MIUI7）,这时问题更严重，不管是通过网络更新还是重新编译(buildLib->buildBundle->run)都没有发现app.detail有被修改的迹象，例：我在app.detail的MainActivity里面加上一个Toast提示，然后重新编译运行，app.detail没有Toast提示，如果我卸载掉整个程序重新安装，app.detail才会有Toast提示。
PS：
apply plugin: 'net.wequick.small'
small {
    aarVersion = '1.0.0-beta2'
}

**Comment by tcking** [comment]
更新时需要加大插件的versionCode
重新编译的时候最好先执行cleanLib

**Comment by wjyin** [comment]
可以了，versionCode问题。
不过很奇怪，偶尔会出现：
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
不论怎么编译都不行，必须卸载掉重装才可以，不知道是不是跟Small自带的冲突了

**Comment by winglight** [comment]
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
这个是已知问题了，坐等大神fix

**Comment by galenlin** [comment]
关闭本问题
@wjyin @winglight AppCompat问题请再单独提问，并附上复现路径。
