### ISSUE TITLE
NSURLConnection 过期

### ISSUE THREAD

**Issue by yinanwang1** [wequick/Small#160]
iOS Demo里，在- (void)upgradeBundle:(SMBundle *)bundle withUrlString:(NSString *)urlString complection:(void (^)(NSError *error))complection 方法中，用到了NSURLConnection，调用了+ (nullable NSData *)sendSynchronousRequest:(NSURLRequest *)request returningResponse:(NSURLResponse * __nullable * __nullable)response error:(NSError **)error NS_DEPRECATED(10_3, 10_11, 2_0, 9_0, "Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h") __WATCHOS_PROHIBITED;
这个方法在iOS9已经废弃，建议使用NSURLSession。

**Comment by galenlin** [comment]
ok，demo写的比较早了，可否提交一个Pull Request
