### ISSUE TITLE
Could not find property 'assembleRelease' on project ':app'.

### ISSUE THREAD

**Issue by alkaid** [wequick/Small#167]
Sample工程跑不起来，执行任何gradlew命令都报这个错：
Could not find property 'assembleRelease' on project ':app'.

请问怎么解决~

**Comment by alkaid** [comment]
android studio版本为2.2 preview3
gradle版本为2.1.0

**Comment by tcking** [comment]
gradle android plugin 版本不能高于2.1(2.0和2.1可以)
```
        classpath 'com.android.tools.build:gradle:2.0.0'
```

**Comment by alkaid** [comment]
@tcking 好的 谢谢 我试试  是因为gradle-small不兼容高版本么

**Comment by galenlin** [comment]
@alkaid @tcking `gradle-small:1.0.0-alpha1` 已修正该问题，请尝试。
