### ISSUE TITLE
Android的大概什么时候可以出release版本，很期待！

### ISSUE THREAD

**Issue by hongxialiu** [wequick/Small#168]
麻烦问下，大概什么时候可以出release版本，很期待！Android的

**Comment by galenlin** [comment]
感谢支持。这周忙着准备北京[GMTC](http://gmtc.geekbang.org/)的演讲内容，预计要到下周。
预发布内容：
1. 支持插件混淆
2. 并发加载优化
已经都提交到DevSample了（混淆的在bundle-proguard分支），可以先尝试下是否正常运行。

如果你有别的希望增加的功能，也可以在这里提出。再次感谢。

**Comment by alkaid** [comment]
好棒 好想去帝都围观

**Comment by a137235** [comment]
还有个期望:可以支持那种插件分化如:AndFix修复这种，我们有时候更新的没有那么多，所以能不能就只加载增加的。

**Comment by galenlin** [comment]
@a137235 按功能模块这个粒度更新感觉还是比较ok的，更新包不会太大，同时也比较好管理。
差分的逻辑其实可以自己加的，你下载一个差量包，再跟旧插件进行合并，然后放到patch目录下。

@hongxialiu 版本已更新，关闭此issue.
