### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by TangSirOnGit** [wequick/Small#17]
i download the sample code and build it, there're some errors:

/home/tangsir/study/android/small/Small/Android/Sample/app.home/src/main/java/net/wequick/example/small/app/home/MainFragment.java
Error:(100, 53) 错误: 找不到符号
符号:   方法 findByName(String)
位置: 类 Bundle
Error:(102, 67) 错误: 找不到符号
符号:   方法 getPatchFile()
位置: 类型为Bundle的变量 bundle
Error:(174, 31) 错误: 找不到符号
符号:   方法 upgrade()
位置: 类型为Bundle的变量 bundle
3 个错误
Error:Execution failed for task ':app.home:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by galenlin** [comment]
These methods are new feature in small 0.2.0, Do you set the `aarVersion` to `'0.2.0'` on `small` DSL?
