### ISSUE TITLE
前天下的Sample不能编译

### ISSUE THREAD

**Issue by hongxialiu** [wequick/Small#170]
dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
//        classpath 'net.wequick.tools.build:gradle-small:0.1.1'
        classpath 'net.wequick.tools.build:gradle-small:0.8.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }`

Error:(26, 0) Cause: net/wequick/gradle/RootPlugin : Unsupported major.minor version 52.0
<a href="openFile:D:\workspace\Small-master\Android\Sample\build.gradle">Open File</a>

然后我把 classpath 'net.wequick.tools.build:gradle-small:0.8.0'换成 classpath 'net.wequick.tools.build:gradle-small:0.1.1'
执行./gradlew buildLib -q报错

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\workspace\Small-master\Android\Sample\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating root project 'Sample'.
> Failed to apply plugin [class 'net.wequick.gradle.LibraryPlugin']
   > Duplicate package id 0x06 with lib.style and lib.utils!
Please redefine one of them in bundle's build.gradle or gradle.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.227 secs
Duplicate package id 0x06 with lib.style and lib.utils!
Please redefine one of them in bundle's build.gradle or gradle.properties.

**Comment by galenlin** [comment]
呃，请用最新的版本。然后下载JDK1.8

**Comment by zzvvc** [comment]
@hongxialiu 你解决这个问题了么？我也碰到这个问题了，重新安装了jdk1.8也不行。

**Comment by hongxialiu** [comment]
我解决了的。重装jdk1.8然后把环境从以前的1.7切到1.8就行了。

**Comment by hongxialiu** [comment]
@zzvvc 我解决了的。重装jdk1.8然后把环境从以前的1.7切到1.8就行了。

**Comment by zzvvc** [comment]
@hongxialiu 我也这么弄了，还是报一样的错误。

**Comment by hongxialiu** [comment]
@zzvvc 额，你确定你jdk1.8环境配置成功了？Android Studio里面设置了项目编译是用JDK1.8？如果还是这样的话，，我也不清楚。哈哈，只能说我打开姿势很对。
