### ISSUE TITLE
资源找不到的问题

### ISSUE THREAD

**Issue by alkaid** [wequick/Small#172]
1.问题1   其中一个lib插件的res/raw下的资源找不到  
`FATAL EXCEPTION: main Process: android.content.res.Resources$NotFoundException: File res/raw/key_click.mp3 from drawable resource ID #0x40050000 at android.content.res.Resources.openRawResourceFd(Resources.java:2416) at android.media.MediaPlayer.create(MediaPlayer.java:992) at android.media.MediaPlayer.create(MediaPlayer.java:975)`

2.问题2  Context.getAssets().openFd(Path)方法异常
`error: This file can not be opened as a file descriptor; it is probably compressed
                                                                  java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
                                                                      at android.content.res.AssetManager.openAssetFd(Native Method)
                                                                      at android.content.res.AssetManager.openFd(AssetManager.java:332)`

**Comment by zhouzhengting** [comment]
遇到同样的问题，很多资源找不到

**Comment by galenlin** [comment]
@alkaid 已解决该问题，请使用gradle-small: 1.0.0-beta2进行编译
