### ISSUE TITLE
插件在application中创建handle会异常

### ISSUE THREAD

**Issue by alkaid** [wequick/Small#173]
app.xxx的appliacation中创建handler会异常被ApkBundleLauncher.java捕获
![image](https://cloud.githubusercontent.com/assets/1241940/16221304/a1b62684-37c4-11e6-8adc-0ef2f4b1f1b6.png)
发现是因为loadBundles是在LoadBundleThread中跑的
![image](https://cloud.githubusercontent.com/assets/1241940/16221332/ca62d2bc-37c4-11e6-9eeb-c9f4b4d6b22d.png)

**Comment by galenlin** [comment]
感谢反馈，已复现问题
