### ISSUE TITLE
bundle.json  建议添加 type项确定 bundle类型

### ISSUE THREAD

**Issue by kongyan4696** [wequick/Small#178]
> 
Bundle.java
line 441

        if (sUserBundlesPath == null) { // Lazy init
            sUserBundlesPath = Small.getContext().getApplicationInfo().nativeLibraryDir;
            sIs64bit = sUserBundlesPath.contains("64");
        }

        String pkg = map.getString("pkg");
        if (pkg != null && !pkg.equals(HOST_PACKAGE)) {
            String soName = "lib" + pkg.replaceAll("\\.", "_") + ".so";
            mBuiltinFile = new File(sUserBundlesPath, soName);
            mPatchFile = new File(FileUtils.getDownloadBundlePath(), soName);
            ## //mPackageName 为bundle.json pkg字段
            mPackageName = pkg;
        }

BundleLauncher.java

> 
public abstract class SoBundleLauncher extends BundleLauncher {

    private static final String TAG = "SoBundle";

    /** Types that support */
    protected abstract String[] getSupportingTypes();

    @Override
    public boolean preloadBundle(Bundle bundle) {
        String packageName = bundle.getPackageName();
        if (packageName == null) return false;

        // Check if supporting
        String[] types = getSupportingTypes();
        if (types == null) return false;

        boolean supporting = false;
        for (String type : types) {
            ##  //根据packageName 和 BundleLauncher 支持的type做处理
            ## //建议改为读取bundle.json type字段
            ## if (packageName.contains("." + type + ".")) {
                supporting = true;
                break;
            }
        }
        ……

> 

插件的命令规则定为 宿主包名.lib.xxx， 这样规定是否有深层次的含义？
建议不要规定插件包名(原因：如果将 第三方module转成 Lib时改变包名，需要修改 Module中引用的R文件、方法  较为麻烦)

**Comment by galenlin** [comment]
主要是为了区分插件类型，你这里的第三方module是一个本地的aar？

**Comment by kongyan4696** [comment]
@galenlin 项目里面原本有个library module, 现在把它转成bundle， 但是包名没有包含*lib*,改包名的代价比较大，在bundle.json加入类别标识比较简单。

**Comment by galenlin** [comment]
可以新建一个lib.* module，然后去依赖你的module

**Comment by galenlin** [comment]
type选项已支持，请查看新版CHANGELOG
