### ISSUE TITLE
您的微信号多少

### ISSUE THREAD

**Issue by jorry** [wequick/Small#179]
想要下您的在infoQ 开发大会上面的ppt,给同事进行分享

**Comment by jorry** [comment]
或者ppt可以发我邮箱  156224301@qq.com

**Comment by zhouzhengting** [comment]
http://ppt.geekbang.org/gmtc?amp;isappinstalled=0&amp;amp;amp;from=groupmessage&amp;amp;from=groupmessage&amp;amp;isappinstalled=0&amp;from=timeline&amp;isappinstalled=0&from=timeline&isappinstalled=0

**Comment by galenlin** [comment]
@jorry 我把二维码放到了wiki里的PPT最后一页 😃
