### ISSUE TITLE
Android Sample的代码启动后闪退

### ISSUE THREAD

**Issue by zhouzhengting** [wequick/Small#182]
运行出现这个错误：
06-28 15:20:48.159 7931-8099/net.wequick.example.small E/BundleParser: Package net.wequick.example.small.app.main has no certificates at entry AndroidManifest.xml; ignoring!

debug调试发现：bundle为null，
// Small url schemes
        Bundle bundle = Bundle.getLaunchableBundle(uri);
        if (bundle != null) {
            bundle.launchFrom(context);
        }

**Comment by galenlin** [comment]
插件需要签名。

你使用的gradle-small的版本是不是偏低了，在0.6.0以下？
[CHANGELOG](https://github.com/wequick/Small/blob/master/Android/DevSample/buildSrc/CHANGELOG.md)

**Comment by zhouzhengting** [comment]
是 classpath 'net.wequick.tools.build:gradle-small:0.8.0'，没有使用老版本。昨天刚刚同步Ｓａｍｐｌｅ代码运行就这样了

**Comment by galenlin** [comment]
从错误来看，是app.main没有签名，你cleanBundle重新编译下看看

**Comment by galenlin** [comment]
duplicate with #181, closed
