### ISSUE TITLE
按照“开始Small之旅”，文档创建项目无法启用插件。

### ISSUE THREAD

**Issue by leoliuzhou** [wequick/Small#184]
你好，我按照“开始Small之旅”的文档内容，创建了Android studio项目，并且创建了app.main 的插件模块，并按文档的流程进行编译，但是我在LaunchActivity调用 Small.openUri("main", LaunchActivity.this);却无法启动插件模块的Activity，也没有报错，会是什么原因？

**Comment by galenlin** [comment]
你好，无法启动看下wiki/FAQ

**Comment by leoliuzhou** [comment]
昨天已经查阅过相关文档，只看到可能因为签名问题可能会导致插件启用失败，没有发现其他相关的问题解答。我在启动应用后看到了 E/art: No implementation found for java.lang.String com.tencent.feedback.eup.jni.NativeExceptionUpload.registNativeExceptionHandler2(java.lang.String, java.lang.String, int, int) (tried Java_com_tencent_feedback_eup_jni_NativeExceptionUpload_registNativeExceptionHandler2 and Java_com_tencent_feedback_eup_jni_NativeExceptionUpload_registNativeExceptionHandler2__Ljava_lang_String_2Ljava_lang_String_2II)
这样一句错误提示，不知道是否与插件启用失败有关系？

**Comment by galenlin** [comment]
这个似乎是说你调用的JNI方法找不到实现？

**Comment by leoliuzhou** [comment]
基本上除了这句，没有发现其他异常，请问下，按照你的文档新建项目及添加插件app.main后，调用 Small.openUri("main", FullscreenActivity.this);此句代码正常情况是否是直接打开app.main工程的MainActivity？

**Comment by galenlin** [comment]
是的

**Comment by leoliuzhou** [comment]
我核对过文档，没有什么遗漏，不知道是否是其他配置有问题，要不我将我创建的项目工程打包发你帮忙看看，应该不会占用你太多时间，请问可以吗？

**Comment by galenlin** [comment]
可以

**Comment by leoliuzhou** [comment]
请问你邮箱账号多少？

**Comment by galenlin** [comment]
不在QQ群里吗，QQ发我就行了，或者oolgloo@foxmail.com

**Comment by leoliuzhou** [comment]
已发送到你邮箱，麻烦查收下

**Comment by leoliuzhou** [comment]
你好。请问昨天发送给你的demo有查看吗？是配置问题还是？
