### ISSUE TITLE
crash with moto x 2014 when launch sample app.

### ISSUE THREAD

**Issue by huangyanan** [wequick/Small#189]
Log:
07-01 17:34:41.043 15223-15223/net.wequick.example.small D/XposedBuild: afterHookedMethod: SystemProperties.get: debug.second-display.pkg retrun: 
07-01 17:34:41.127 15223-15223/net.wequick.example.small D/XposedBuild: afterHookedMethod: SystemProperties.get: service.slate.enabled retrun: false
07-01 17:34:41.130 15223-15243/net.wequick.example.small D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
07-01 17:34:41.142 15223-15242/net.wequick.example.small W/ResourceType: No known package when getting value for resource number 0x7f09008c
07-01 17:34:41.143 15223-15242/net.wequick.example.small W/ResourceType: No known package when getting value for resource number 0x79030000
07-01 17:34:41.143 15223-15242/net.wequick.example.small W/ResourceType: No known package when getting value for resource number 0x7f060014
07-01 17:34:41.147 15223-15242/net.wequick.example.small W/ResourceType: No known package when getting value for resource number 0x7f09008c
07-01 17:34:41.149 15223-15242/net.wequick.example.small W/ResourceType: No known package when getting value for resource number 0x7f09008c
07-01 17:34:41.199 15223-15243/net.wequick.example.small I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I3193f6e94a)
                                                                       OpenGL ES Shader Compiler Version: E031.28.00.02
                                                                       Build Date: 10/09/15 Fri
                                                                       Local Branch: mybranch15039904
                                                                       Remote Branch: quic/LA.BF.1.1.3_rb1.2
                                                                       Local Patches: NONE
                                                                       Reconstruct Branch: NOTHING
07-01 17:34:41.201 15223-15243/net.wequick.example.small I/OpenGLRenderer: Initialized EGL, version 1.4
07-01 17:34:41.513 15223-15242/net.wequick.example.small W/ResourceType: ResTable_typeSpec entry count inconsistent: given 1, previously 78
07-01 17:34:41.514 15223-15242/net.wequick.example.small W/System.err: java.lang.NoSuchMethodException: <init> [class android.content.res.AssetManager, class android.util.DisplayMetrics, class android.content.res.Configuration]
07-01 17:34:41.514 15223-15242/net.wequick.example.small W/System.err:     at java.lang.Class.getConstructor(Class.java:528)
07-01 17:34:41.514 15223-15242/net.wequick.example.small W/System.err:     at java.lang.Class.getConstructor(Class.java:492)
07-01 17:34:41.514 15223-15242/net.wequick.example.small W/System.err:     at net.wequick.small.util.ReflectAccelerator.newResources(ReflectAccelerator.java:425)
07-01 17:34:41.514 15223-15242/net.wequick.example.small W/System.err:     at net.wequick.small.ApkBundleLauncher.mergeResources(ApkBundleLauncher.java:652)
07-01 17:34:41.514 15223-15242/net.wequick.example.small W/System.err:     at net.wequick.small.ApkBundleLauncher.postSetUp(ApkBundleLauncher.java:399)
07-01 17:34:41.514 15223-15242/net.wequick.example.small W/System.err:     at net.wequick.small.Bundle.loadBundles(Bundle.java:673)
07-01 17:34:41.514 15223-15242/net.wequick.example.small W/System.err:     at net.wequick.small.Bundle.loadBundles(Bundle.java:287)
07-01 17:34:41.515 15223-15242/net.wequick.example.small W/System.err:     at net.wequick.small.Bundle.access$100(Bundle.java:64)
07-01 17:34:41.515 15223-15242/net.wequick.example.small W/System.err:     at net.wequick.small.Bundle$LoadBundleThread.run(Bundle.java:638)
07-01 17:34:41.517 15223-15242/net.wequick.example.small W/art: The dalvik.system.DexPathList$Element constructor is not accessible by default. This is a temporary workaround for backwards compatibility with class-loader hacks. Please update your application.
07-01 17:34:41.517 15223-15242/net.wequick.example.small W/art: The dalvik.system.DexPathList$Element constructor is not accessible by default. This is a temporary workaround for backwards compatibility with class-loader hacks. Please update your application.
07-01 17:34:41.518 15223-15242/net.wequick.example.small W/art: The dalvik.system.DexPathList$Element constructor is not accessible by default. This is a temporary workaround for backwards compatibility with class-loader hacks. Please update your application.
07-01 17:34:41.518 15223-15242/net.wequick.example.small W/art: The dalvik.system.DexPathList$Element constructor is not accessible by default. This is a temporary workaround for backwards compatibility with class-loader hacks. Please update your application.
07-01 17:34:41.518 15223-15242/net.wequick.example.small W/art: The dalvik.system.DexPathList$Element constructor is not accessible by default. This is a temporary workaround for backwards compatibility with class-loader hacks. Please update your application.
07-01 17:34:41.518 15223-15242/net.wequick.example.small W/art: The dalvik.system.DexPathList$Element constructor is not accessible by default. This is a temporary workaround for backwards compatibility with class-loader hacks. Please update your application.
07-01 17:34:41.518 15223-15242/net.wequick.example.small W/art: The dalvik.system.DexPathList$Element constructor is not accessible by default. This is a temporary workaround for backwards compatibility with class-loader hacks. Please update your application.
07-01 17:34:41.518 15223-15242/net.wequick.example.small W/art: The dalvik.system.DexPathList$Element constructor is not accessible by default. This is a temporary workaround for backwards compatibility with class-loader hacks. Please update your application.
07-01 17:34:41.520 15223-15223/net.wequick.example.small D/Main Plugin: AppContext()
07-01 17:34:41.520 15223-15223/net.wequick.example.small D/Main Plugin: onCreate()
07-01 17:34:41.520 15223-15223/net.wequick.example.small D/Main Plugin: {net.wequick.example.small.app.detail=1, net.wequick.example.small.web.about=1, com.example.mysmall.lib.style=1, net.wequick.example.small.app.mine=1, net.wequick.example.small.app.home=1, net.wequick.example.small.lib.utils=1, net.wequick.example.lib.analytics=1, net.wequick.example.small.app.main=1}
07-01 17:34:41.520 15223-15223/net.wequick.example.small W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.res.Resources.getString(int)' on a null object reference
07-01 17:34:41.521 15223-15223/net.wequick.example.small W/System.err:     at android.content.Context.getString(Context.java:409)
07-01 17:34:41.521 15223-15223/net.wequick.example.small W/System.err:     at net.wequick.example.small.app.main.AppContext.onCreate(AppContext.java:26)
07-01 17:34:41.521 15223-15223/net.wequick.example.small W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
07-01 17:34:41.521 15223-15223/net.wequick.example.small W/System.err:     at net.wequick.small.ApkBundleLauncher$1.run(ApkBundleLauncher.java:445)
07-01 17:34:41.521 15223-15223/net.wequick.example.small W/System.err:     at android.os.Handler.handleCallback(Handler.java:746)
07-01 17:34:41.521 15223-15223/net.wequick.example.small W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-01 17:34:41.521 15223-15223/net.wequick.example.small W/System.err:     at android.os.Looper.loop(Looper.java:148)
07-01 17:34:41.521 15223-15223/net.wequick.example.small W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5443)
07-01 17:34:41.521 15223-15223/net.wequick.example.small W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-01 17:34:41.521 15223-15223/net.wequick.example.small W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
07-01 17:34:41.521 15223-15223/net.wequick.example.small W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
07-01 17:34:41.521 15223-15223/net.wequick.example.small W/System.err:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
07-01 17:34:41.522 15223-15223/net.wequick.example.small D/AndroidRuntime: Shutting down VM
07-01 17:34:41.522 15223-15223/net.wequick.example.small E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: net.wequick.example.small, PID: 15223
                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.res.Resources.newTheme()' on a null object reference
                                                                               at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.dequeueStubActivity(ApkBundleLauncher.java:282)
                                                                               at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.wrapIntent(ApkBundleLauncher.java:246)
                                                                               at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.execStartActivity(ApkBundleLauncher.java:143)
                                                                               at android.app.Activity.startActivityForResult(Activity.java:3921)
                                                                               at android.app.Activity.startActivityForResult(Activity.java:3881)
                                                                               at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:843)
                                                                               at net.wequick.small.BundleLauncher.launchBundle(BundleLauncher.java:169)
                                                                               at net.wequick.small.ApkBundleLauncher.launchBundle(ApkBundleLauncher.java:589)
                                                                               at net.wequick.small.Bundle.launchFrom(Bundle.java:497)
                                                                               at net.wequick.small.Small.openUri(Small.java:268)
                                                                               at net.wequick.small.Small.openUri(Small.java:250)
                                                                               at net.wequick.example.small.LaunchActivity$1.onComplete(LaunchActivity.java:57)
                                                                               at net.wequick.small.Bundle$LoadBundleHandler.handleMessage(Bundle.java:712)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                               at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

my phone has installed xposed. android version 6.0.1

**Comment by galenlin** [comment]
#169 has a simular issue with xposed. Would you please help us to fix it, thanks.

**Comment by huangyanan** [comment]
https://github.com/huangyanan/Small/commit/bdf20ceb770c503adb91f5a5c234af2c4d5240ec

**Comment by galenlin** [comment]
@huangyanan Xposed的问题已经修复，请使用新版尝试，相同的问题还有 #169

**Comment by huangyanan** [comment]
👍

2016-08-11 15:20 GMT+08:00 林光亮 <notifications@github.com>:
