### ISSUE TITLE
DevSample里面浏览Issues 会崩溃

### ISSUE THREAD

**Issue by nickyangjun** [wequick/Small#197]
在issues 列表里面多浏览几个问题，大概5，6个的样子，就会遇到崩溃，下面是崩溃log:

E/AndroidRuntime(24300): java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wequick.example.small/net.wequick.small.webkit.WebActivity}: java.lang.NullPointerException
E/AndroidRuntime(24300):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2263)
E/AndroidRuntime(24300):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
E/AndroidRuntime(24300):        at android.app.ActivityThread.access$800(ActivityThread.java:147)
E/AndroidRuntime(24300):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1226)
E/AndroidRuntime(24300):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(24300):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(24300):        at android.app.ActivityThread.main(ActivityThread.java:5137)
E/AndroidRuntime(24300):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(24300):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(24300):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
E/AndroidRuntime(24300):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617)
E/AndroidRuntime(24300):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(24300): Caused by: java.lang.NullPointerException
E/AndroidRuntime(24300):        at android.view.ViewGroup.addViewInner(ViewGroup.java:3561)
E/AndroidRuntime(24300):        at android.view.ViewGroup.addView(ViewGroup.java:3415)
E/AndroidRuntime(24300):        at net.wequick.small.webkit.WebActivity.onCreate(WebActivity.java:104)
E/AndroidRuntime(24300):        at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime(24300):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime(24300):        at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:167)
E/AndroidRuntime(24300):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2227)
E/AndroidRuntime(24300):        ... 11 more

**Comment by galenlin** [comment]
small：1.0.0已经修复该问题
