### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by lixf078** [wequick/Small#203]
情景：
插件app.main 中LoginActivity.java
Module lib.base 定义一些BaseActivity.java
Module lib.loadview 改造过的第三方view

BaseActivity中引用了lib.loadview中的第三方view 如：PtrClassicFrameLayout

LoginActivity extends BaseActivity{
.....
}

运行时出错：BaseActivity中的布局文件初始化失败：

布局文件部分内容：
<in.srain.cube.views.ptr.PtrClassicFrameLayout >
。。。。。。
    </in.srain.cube.views.ptr.PtrClassicFrameLayout>

报错信息：
07-08 15:10:51.249 E/AndroidRuntime(29895): Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class in.srain.cube.views.ptr.PtrClassicFrameLayout

Caused by: java.lang.ClassNotFoundException: Didn't find class "in.srain.cube.views.ptr.PtrClassicFrameLayout" on path: DexPathList[[zip file "/data/app-lib/com.strum.wenyu-1/libcom_strum_wenyu_lib_base.so"
zip file "/data/app-lib/com.strum.wenyu-1/libcom_strum_wenyu_app_main.so"
。。。。。

在线等回复。。。

**Comment by lixf078** [comment]
布局文件内容：
<in.srain.cube.views.ptr.PtrClassicFrameLayout >
        <RelativeLayout
            android:id="@+id/content_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>
    </in.srain.cube.views.ptr.PtrClassicFrameLayout>

**Comment by galenlin** [comment]
@lixf078 
检查下gradle-small的版本是不是最新的，
再看下`in.srain.cube.views.ptr.PtrClassicFrameLayout`这个类在哪个插件里定义的，反编译之看是否存在该class。

**Comment by lixf078** [comment]
我是直接把.so改成.jar，打开后没有相对应的.class文件，一个都没有。。。为是什么啊？

**Comment by lixf078** [comment]
classpath 'net.wequick.tools.build:gradle-small:0.9.0'
    aarVersion = '1.0.0'

**Comment by galenlin** [comment]
感谢QQ群@深圳-hcanyz的解答：
> “包名不对，需要包含*lib*或者*app*，不然small不识别，会加载不到”
