### ISSUE TITLE
使用了multidex的宿主启动不了别的插件

### ISSUE THREAD

**Issue by soaringEveryday** [wequick/Small#205]
我将老工程的代码（试用了multidexapplication）作为宿主，准备将新的需求功能作为插件模块用small管理。在老工程中去启动插件，发现启动不了，没有任何反应，mApplicableLauncher总是为null。
请问下宿主可以使用multidexapplication吗？

**Comment by galenlin** [comment]
@soaringEveryday 没有尝试过multidex呃。

**Comment by nicGithub** [comment]
可以用，亲测可用
