### ISSUE TITLE
老项目使用small, 添加插件模块之后，显示找不到插件。需要配置的地方都检查了，没有问题

### ISSUE THREAD

**Issue by Seven2Qin** [wequick/Small#206]
老项目使用small, 添加插件模块之后，代码都执行了，但是log显示  “ApkBundleLauncher: Could not find any APK bundles!”这是什么原因啊

**Comment by Carlos2927** [comment]
我也碰到过这个问题，仔细看[Android快速实践](https://github.com/wequick/Small/blob/master/Android/README.md)后才知道要编译插件
1.执行命令 [./]gradlew buildLib -q
2.执行命令 [./]gradlew buildBundle -q

**Comment by Seven2Qin** [comment]
这个编译过了之后，才出现这个问题的

**Comment by galenlin** [comment]
@Seven2Qin 在app/smallLibs下有生成`*.so`吗，如果在模拟器运行需要把armeabi改为x86

**Comment by bktoky** [comment]
我刚刚在一个老项目中使用也出现了，smallLibs 下有生成*.so

**Comment by galenlin** [comment]
@Seven2Qin, @bktoky 解压看下宿主apk里面的libs目录下是不是不只一个`armeabi`目录
```bash
aapt list 宿主.apk
```

**Comment by galenlin** [comment]
@Seven2Qin @bktoky 这个问题建了FAQ，请参考#219
