### ISSUE TITLE
Unable to start service Intent { act=com.qiyiqi.apiservice } U=0: not found

### ISSUE THREAD

**Issue by lixf078** [wequick/Small#209]
背景：app.main中定义了一个service,在app.main的MainActivity中startService

>

App.main的mainfest.xml中定义
《service android:name=".service.ApiService"》
            《intent-filter android:priority="1000"》
                《action android:name="com.qiyiqi.apiservice"/》
            《/intent-filter》
        《/service》

> 

private void startService(){
        Intent  intent = new Intent("com.qiyiqi.apiservice");
//        intent.setClass(LaunchActivity.this, ApiService.class);
        startService(intent);
    }
日志显示not found该service?

在编译成的*app_mian.so中是可以找到这个Service的，这是为什么啊？

**Comment by MartinDong** [comment]
同问，现在使用激光推送，注册到了Main中但是不起作用 #
