### ISSUE TITLE
在lib.utils引入一些工具报错

### ISSUE THREAD

**Issue by ahlzhang** [wequick/Small#21]
我在lib.utils里引入了Volley的框架.
在执行gradlew buildLib 的时候把length为负数的异常.

**Comment by galenlin** [comment]
感谢反馈，@wu4321 已经定位到这个问题。原因是`ArscEditor.groovy`#207的一个类型错误，导致数据溢出：

```groovy
short size = lib.header.size
```

`short`应该为`int`

@wu4321 将会在稍候提交PR来修复
