### ISSUE TITLE
启动报错！

### ISSUE THREAD

**Issue by zjunbutterfly** [wequick/Small#210]
07-11 09:43:33.976 10225-10246/com.szxys.mhub.nethospital2 W/dalvikvm: VFY: unable to resolve static field 110 (SUPPORTED_64_BIT_ABIS) in Landroid/os/Build;
07-11 09:43:33.976 10225-10246/com.szxys.mhub.nethospital2 W/dalvikvm: VFY: unable to resolve static field 109 (SUPPORTED_32_BIT_ABIS) in Landroid/os/Build;
07-11 09:43:33.996 10225-10246/com.szxys.mhub.nethospital2 W/ResourceType: Bad string block: last string is not 0-terminated
07-11 09:43:34.001 10225-10246/com.szxys.mhub.nethospital2 W/ResourceType: No known package when getting value for resource number 0x73020000
07-11 09:43:34.016 10225-10246/com.szxys.mhub.nethospital2 W/ResourceType: Bad string block: last string is not 0-terminated
07-11 09:43:34.026 10225-10225/com.szxys.mhub.nethospital2 W/dalvikvm: VFY: unable to resolve static field 7116 (paf_build_host) in Lcom/paf/spileboard/R$string;
07-11 09:43:34.026 10225-10225/com.szxys.mhub.nethospital2 W/dalvikvm: VFY: unable to resolve static field 7117 (paf_build_revision) in Lcom/paf/spileboard/R$string;
07-11 09:43:34.026 10225-10225/com.szxys.mhub.nethospital2 W/dalvikvm: VFY: unable to resolve static field 7119 (paf_build_time) in Lcom/paf/spileboard/R$string;
07-11 09:43:34.026 10225-10225/com.szxys.mhub.nethospital2 W/dalvikvm: VFY: unable to resolve static field 7118 (paf_build_sdkverson) in Lcom/paf/spileboard/R$string;
07-11 09:43:34.026 10225-10225/com.szxys.mhub.nethospital2 W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41621c50)

**Comment by galenlin** [comment]
@zjunbutterfly 能否提供更详细的Log

**Comment by galenlin** [comment]
重复 #211
