### ISSUE TITLE
一个lib依赖另一个lib，buildLib时出现Duplicate package错误

### ISSUE THREAD

**Issue by offbye** [wequick/Small#213]
一个lib依赖另一个lib，buildLib时出现下面的错误，目前还没有找到解决吧，clean工程和cleanLib都做了，但还不行，只好把依赖去掉了才行。原因未知
Duplicate package id 0x7f with lib.domain and lib.domain!

**Comment by sfsheng0322** [comment]
我在编译工程的时候也报这个错误啦，下面是错误信息：

* What went wrong:
A problem occurred configuring project ':lib.style'.
> Failed to notify project evaluation listener.
   > Duplicate package id 0x79 with lib.location and lib.style!
     Please redefine one of them in build.gradle (e.g. 'ext.packageId=0x7e') or gradle.properties (e.g. 'packageId=7e').

**Comment by galenlin** [comment]
@sfsheng0322 你这个可以根据提示来操作修改
