### ISSUE TITLE
Bundle更新机制的问题

### ISSUE THREAD

**Issue by pscj** [wequick/Small#214]
在参考了DevSample的升级之后，打算自己做这块的逻辑，发现现有机制有个问题可能会导致升级出错。
     比如我有3个模块要升级，2个app,1个lib,  app都依赖于lib. 2个app已经下载完写到了small_patch目录以后，由于某些原因(断网、杀进程)，lib模块没有下载或者下了一半。此时如果重启程序，按现在的逻辑，会加载那2个新的app模块，但是由于新app模块是依赖新的lib模块的，然后就报错崩溃了。 
感觉需要提供一种类似事务的方式，只要升级没有完成，下次启动程序，还是会加载旧的so。或者下载bundle先保存到一个临时目录，全下载完之后，统一复制替换旧的so

**Comment by galenlin** [comment]
@pscj 应该可以这样：

下载bundle先保存到一个临时目录，全下载完之后，统一复制到patch目录下，并标记升级。

**Comment by pscj** [comment]
好的，就按群主说的搞了
