### ISSUE TITLE
读取插件中raw资源问题

### ISSUE THREAD

**Issue by tcking** [wequick/Small#215]
**前提：**
在插件的raw下有些音频文件

**现象：**
通过插件的方式启动，通过调用`getResources().openRawResourceFd(R.raw.test)` (`MediaPlayer.create`内部会通过此方法打开资源)会出现异常：
```
android.content.res.Resources$NotFoundException: File res/raw/test.m4a from drawable resource ID #0x3c05000c
```

调用`getResources().openRawResource(R.raw.test)`能获取到正确的inputstream，插件单独启动时正常

**Comment by galenlin** [comment]
#172 提了这个问题。我在Sample的app.mine中也做了测试。
资源是存在的，但是无法返回FileDescriptor。
初步判断错误在[Asset.cpp](https://github.com/android/platform_frameworks_base/blob/master/libs/androidfw/Asset.cpp#L629)返回了-1。原因还未知。

**Comment by tcking** [comment]
扒了下这块的代码，在调用`Asset->openFileDescriptor`之前会调用4个参数的`openChunk`(在`AsssetManager.cpp的createFromFile`中执行)，在`openChunk`中应该是确定mMap==NULL，mFileName!=NULL的，所以如果返回-1则只有可能是`open(fname, O_RDONLY | O_BINARY)`，但是同样的函数在`createFromFile`中已经调用过了，应该也不会出现问题。凌乱了

**Comment by tcking** [comment]
做了个测试，发现跟编译后的插件有关系，没有经过small脚本处理的apk动态加载到asset里面能正常调用`openRawResourceFd` small编译出来的插件则不行。
测试过程如下：

1.准备两份apk，`net.wequick.example.small.app.main.apk`是small编译后的，`test.apk`是正常编译的，两份apk都拷贝到`/data/data/net.wequick.example.small/app_small_base/`下


2.测试small编译后的apk
``` java
AssetManager assets = ReflectAccelerator.newAssetManager();
Context context=getApplication();
ReflectAccelerator.addAssetPath(assets, "/data/data/net.wequick.example.small/app_small_base/net.wequick.example.small.app.main.apk");
Resources base1 = context.getResources();
ApkBundleLauncher.ResourcesMerger resourcesMerger = new ApkBundleLauncher.ResourcesMerger(assets, base1.getDisplayMetrics(), base1.getConfiguration());
System.out.println(resourcesMerger.openRawResourceFd(0x7703000c));//0x7703000是编译后的资源id
```
错误日志为：`java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed`

3.测试正常编译的apk：

``` java
AssetManager assets = ReflectAccelerator.newAssetManager();
Context context=getApplication();
ReflectAccelerator.addAssetPath(assets, "/data/data/net.wequick.example.small/app_small_base/test.apk");
Resources base1 = context.getResources();
ApkBundleLauncher.ResourcesMerger resourcesMerger = new ApkBundleLauncher.ResourcesMerger(assets, base1.getDisplayMetrics(), base1.getConfiguration());
System.out.println(resourcesMerger.openRawResourceFd(2130968576));//2130968576是编译后的资源id
```

结果正常
