### ISSUE TITLE
[新需求]根据插件名称获取ResourcePath

### ISSUE THREAD

**Issue by tcking** [wequick/Small#221]
类似于`getPackageResourcePath`，有些第三方的sdk需要获取资源的加载路径（例如科大讯飞的tts），如果作为插件加载则需要根据插件包名获取资源的加载路径

**Comment by galenlin** [comment]
这里“资源的加载路径”应该是插件的路径？

**Comment by galenlin** [comment]
@tcking b3f0501 可以试下看看

**Comment by tcking** [comment]
此法可行 👍
