### ISSUE TITLE
单独调试app.main不能安装

### ISSUE THREAD

**Issue by chsasaw** [wequick/Small#224]
报错

INSTALL_FAILED_NO_MATCHING_ABIS

**Comment by galenlin** [comment]
模拟器上跑的吗，看起来是没有x86架构

**Comment by chsasaw** [comment]
不是的  在真机上跑的

**Comment by galenlin** [comment]
@chsasaw 那就是没有armeabi架构，你看看吧，把那个报错Google一下会有答案的。
