### ISSUE TITLE
插件app能够通过small去调用宿主app的activity吗？

### ISSUE THREAD

**Issue by Seven2Qin** [wequick/Small#225]
插件app能够通过small去调用宿主app的activity吗？

**Comment by galenlin** [comment]
可以隐式调用，或者在bundle.json里配置

**Comment by Seven2Qin** [comment]
在bundle.json里配置了，宿主app的activity起不来。隐式调用？直接在宿主app的androidminfast中个给activity配置action吗？

**Comment by galenlin** [comment]
@Seven2Qin 可以intent写上宿主activity的全名，bundle.json的支持要等新版本发布

**Comment by Seven2Qin** [comment]
好的，感谢感谢

**Comment by Seven2Qin** [comment]
@galenlin 我现在在插件中依赖  compile 'com.yalantis:ucrop:2.1.1' 这个第三方的库，但是它包含了一些资源文件。编译之后找不到资源(应该是包名不同，一个是插件的包名，一个是宿主app包名)，有没有好的解决方法啊？

**Comment by galenlin** [comment]
@Seven2Qin 这个问题在 #195 讨论
