### ISSUE TITLE
启动模式的singletask好像不支持

### ISSUE THREAD

**Issue by pscj** [wequick/Small#231]
以DevSample为例说，就是
1. 把app.main工程里的mainActivity类设置成singletask
2. 在app.home工程里mainFragment找个onclick事件，执行Small.openUri("main", getContext());
 希望结果是：跳转到app.main工程里mainActivity类执行onNewIntent
当前结果是：跳转到app.main工程里mainActivity类执行onCreate

**Comment by galenlin** [comment]
small:1.1.0-beta2 已修正

**Comment by jarvan11** [comment]
和@pscj描述的差不多，执行Small.openUri("main", getContext());
希望结果是：跳转到app.main工程里mainActivity类执行onNewIntent
当前结果是：跳转到app.main工程里mainActivity类执行onCreate
版本：1.1.0-alpha2
