### ISSUE TITLE
android bundle.json配置fragment的rules

### ISSUE THREAD

**Issue by chsasaw** [wequick/Small#236]
```
     {
      "uri": "community",
      "pkg": "com.huanxiao.store.app.community",
      "rules":{
        "community":".CommunityFragment"
      }
```
需要加"."符号才能匹配到Fragment，感觉这样设计有点奇怪。
另外不能从其他modle获取到数据类型的实例，比如有一个插件名字叫app.account放置个人信息和登录注册修改个人信息等功能，其他app类型的插件如何获取到个人信息如token、uid等，难道需要抽出一个lib.account来管理？这样就分的太细了。

**Comment by galenlin** [comment]
1. 感谢反馈，近期会支持不加`.`
2. 是这样的，`app`模块间应该要做到互相不认识，公共的模块都是某种程度的`lib`，你可以直接把app.account做成lib.account
