### ISSUE TITLE
bundle资源id找不到

### ISSUE THREAD

**Issue by tobiashu2016** [wequick/Small#239]
如题。
独立运行bundle没有问题，打包运行时不能通过findViewId找到插件布局中的view
补充：Layout是可以拿到的

**Comment by galenlin** [comment]
log发下看下

**Comment by tobiashu2016** [comment]
code(onCreate):
View v = LayoutInflater.from(this).inflate(R.layout.activity_main, null);
        setContentView(v);
        Button btn = (Button)v.findViewById(R.id.small_main_btn);

logcat:
 Caused by: java.lang.NullPointerException
                                                       at com.lestar.www.app.main.MainActivity.onCreate(MainActivity.java:20)

**Comment by tobiashu2016** [comment]
使用最新版本的small未能重现此问题了

**Comment by DHGHH** [comment]
我也遇到这样的问题，使用最新的出现这问题
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0'
        classpath 'net.wequick.tools.build:gradle-small:1.0.0-beta1'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

apply plugin: 'net.wequick.small'


small {
    aarVersion = '1.1.0-beta1'
}



打包运行时不能通过findViewId找到插件布局中的view
但R.layout.xx是可以拿到的

**Comment by galenlin** [comment]
@DHGHH 请使用`classpath 'net.wequick.tools.build:gradle-small:1.0.0-beta5'`试下

**Comment by galenlin** [comment]
close this, remain #255
