### ISSUE TITLE
SoBundleLauncher问题

### ISSUE THREAD

**Issue by ahlzhang** [wequick/Small#24]
SoBundleLauncher类里getPluginInfo返回值一直为空.

protected PackageInfo getPluginInfo(File plugin) {
        if (plugin == null || !plugin.exists()) return null;

        PackageManager pm = Small.getContext().getPackageManager();
        File file = new File(plugin.getPath());
        if (file.exists()) {
            System.out.println("============有这个文件");
        } else {
            System.out.println("============没有这个文件");
        }
        PackageInfo pluginInfo = pm.getPackageArchiveInfo(plugin.getPath(),
            PackageManager.GET_SIGNATURES);
        return pluginInfo;
    }

我写了一个测试,发现能找到这个文件,但是pluginInfo一直为null

**Comment by galenlin** [comment]
你的应用签名需要配置下。

**Comment by ahlzhang** [comment]
我配置了签名之后,发现另一个问题.
无法找到style.
我怎么才能使用宿主里在资源呢?比如BaseActivity和styles.xml

**Comment by galenlin** [comment]
加上宿主的包名前缀。
这个issue我先关了。
