### ISSUE TITLE
web 模块 ,  small-asset does not exist.

### ISSUE THREAD

**Issue by lanzhihong6** [wequick/Small#242]
其他模块编译正常,web.* 的模块  buildBundle 的时候 一直是 small-asset does not exist. ,这个是什么原因

**Comment by galenlin** [comment]
@lanzhihong6 提供个demo我看下

**Comment by lanzhihong6** [comment]
我qq群联系你

**Comment by galenlin** [comment]
发现问题为工程配置问题：“模块自身没有assets目录”，关闭本问题。
