### ISSUE TITLE
关于插件之间的Intent跳转问题

### ISSUE THREAD

**Issue by mygift2016** [wequick/Small#246]
Intent it = Small.getIntentOfUri("main", LoginActivity.this);
                it.putExtra("mStr", "testABC");
                LoginActivity.this.startActivityForResult(it, 1);

以上使用Small.getIntentOfUri的方法获取Intent会报空指针，调试发现该方法内的scheme需要增加为空的判断，请验证。

**Comment by zxpllff** [comment]
Small.getIntentOfUri(uriId, context) 返回值为 null 怎么处理  还有别的方法获取吗
