### ISSUE TITLE
关于动态修复的流程（bundle.json生效，但so文件并未生效）

### ISSUE THREAD

**Issue by Tang-xun** [wequick/Small#247]
1 使用Sample项目，修改了app.detail里面的setTitle的内容
2 修改原来的bundle.json更新的地址为自己放在7牛上的文件
3 修改了bundle.json中的updates指定为
   "pkg": "net.wequick.example.small.app.detail",
   "url": "http://ob25ribd0.bkt.clouddn.com/libnet_wequick_example_small_app_detail.so"
4 将上面修改的app.detail重新使用./gradlew buildBundle生成新的so文件
5 将so方在文件里指定的7牛服务器
6 app中点击check upgrade 
7 调试发现bundle.json请求到了最新的数据但是修改的app.detail没有生效

**Comment by galenlin** [comment]
Please refer to [wiki/FAQ](https://github.com/wequick/Small/wiki/Android-FAQ).
