### ISSUE TITLE
插件中的activity没有开启硬件加速

### ISSUE THREAD

**Issue by tcking** [wequick/Small#258]
自定义动画在直接运行插件和通过插件来加载其流畅度相差很大，发现通过插件加载时没有打开硬件加速，在宿主的`application`和占坑的`acitivity`以及插件中的`activity`都声明了`android:hardwareAccelerated="true"` 但是并没有效果。

目前有两种方式能打开硬件加速：
1.在activity中setFlags
``` java
getWindow().setFlags(
                WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED,
                WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED);
```

2.在`ApkBundleLauncher`解析activities时主动加上`FLAG_HARDWARE_ACCELERATED`
``` java
for (ActivityInfo ai : pluginInfo.activities) {
            ai.flags |= ActivityInfo.FLAG_HARDWARE_ACCELERATED;
            sLoadedActivities.put(ai.name, ai);
        }
```

**Comment by galenlin** [comment]
@tcking small:1.1.0-beta4已支持，请尝试。
