### ISSUE TITLE
android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by 77jiang** [wequick/Small#259]
宿主中的mainactivity中，有一个framlayout.
使用如下方法
FragmentManager fragmentManager = getSupportFragmentManager();
        Fragment mainFragment = Small.createObject("fragment-v4", "home", this);
        fragmentManager.beginTransaction().replace(R.id.fl_main, mainFragment).commitAllowingStateLoss();
无法加载插件中的fragment，挂在插件中的fragment的inflate那句，找不到layout。这是在appcompat-23.2.1中出现的。
如果把appcompat改成24.1.1，则可以加载，但是如果插件layout.xml中使用了一个资源，如color，则会报找不到这个color。

**Comment by 77jiang** [comment]
我后来又试了一下，宿主貌似不能直接使用插件中的fragment，但是插件中的activity却可以直接使用其他插件的fragment

**Comment by 77jiang** [comment]
又尝试修改了一下，发现，宿主的首个activity会引起这个问题，但是放在后边打开的activity中这样用就不会有问题

**Comment by galenlin** [comment]
@77jiang 这个正常的，第一个Activity只是用来做加载插件的用途，在实际场景中通常为**闪屏页**。
