### ISSUE TITLE
看不懂smaple

### ISSUE THREAD

**Issue by liuguangli** [wequick/Small#27]
下载了sample，跑不起来。插件是怎么被加载的？插件不是先编译成apk然后放到某个路径下，由宿主取加载么？

**Comment by galenlin** [comment]
要理解框架的原理，建议看下[DevSample](https://github.com/wequick/Small/tree/master/Android/DevSample)。

Sample是使用者模式，对开发者来说是完全透明的。

至于“跑不起来”，请确认执行了`buildLib`，`buildBundle`等操作，或者提供详细的错误日志。

**Comment by liuguangli** [comment]
谢谢  buildLib，buildBundle 没执行，搞定了第一步。

**Comment by galenlin** [comment]
请先独立运行起Sample 我们更愿意收到源码级别的issue
