### ISSUE TITLE
Activity created twice while orientation set to landscape

### ISSUE THREAD

**Issue by Stay** [wequick/Small#276]
#86

现在能支持横屏，但是在manifest中设置为landscape，打开activity会创建两次。

**Comment by galenlin** [comment]
Activity设置了 android:configChanges 属性吗？

**Comment by Stay** [comment]
@galenlin 
设置了android:configChanges="keyboardHidden|orientation|screenSize"
但并不生效。只有app中的LauchActivity不会创建两次

**Comment by galenlin** [comment]
@Stay 现在还不支持该属性，可能需要在宿主里定义相关的Activity
