### ISSUE TITLE
Gradle 无法 download jcenter small-0.11.aar？翻墙了也不行？是不是gradle版本问题

### ISSUE THREAD

**Issue by WangGD0812** [wequick/Small#28]
Gradle一直download jcenter small-0.11.aar
我的project build.gradle 配置如下：
 buildscript {
   repositories { 
        jcenter()
   } 
   dependencies { 
         classpath 'com.android.tools.build:gradle:1.3.0'
         classpath 'net.wequick.tools.build:gradle-small:0.1.1' 
   } 
} 
allprojects { 
     repositories {
        jcenter()
     }
 }
 apply plugin: 'net.wequick.small'

**Comment by galenlin** [comment]
请根据Readme设置aarVersion
