### ISSUE TITLE
lib中百度定位、语音识别SDK使用时权限获取不到，相应配置权限都写好的

### ISSUE THREAD

**Issue by clxxcl** [wequick/Small#282]
我手机是小米Note。百度定位、语音识别需要的定位和录音权限在使用时会跳出弹窗进行询问，但移入lib中后，使用时就不会进行提示，它们就获取不到权限。

**Comment by galenlin** [comment]
权限在宿主manifest声明了吗

**Comment by clxxcl** [comment]
申明了

**Comment by galenlin** [comment]
有无其他错误log

**Comment by clxxcl** [comment]
这是语音识别的，就提示权限不足，但在权限管理中是有的，也没拒绝
![n6 4d28yk43t 93oed yycm](https://cloud.githubusercontent.com/assets/11555733/17842486/00d2fbd0-6856-11e6-9783-2d25b3ab8a75.png)
![screenshot_2016-08-22-10-49-14_com miui securityc](https://cloud.githubusercontent.com/assets/11555733/17842494/1912c770-6856-11e6-9cf8-204ad005f66b.png)

**Comment by clxxcl** [comment]
其实是android6.0权限的问题，要主动请求下，测过6.0一下就没问题。但还是有点疑惑，以前没有用Small框架时不需要主动请求权限也可以用，MIUI系统会自己弹出询问dialog。
