### ISSUE TITLE
lib.x 模块不支持 有 layout文件?

### ISSUE THREAD

**Issue by hejie** [wequick/Small#285]
报错  Dependency bfbm-core:lib.style:unspecified on project app resolves to an APK archive which is not supported as a compilation dependency. app/app/bfbmLibs/armeabi/libcom_bfbm_lib_style.so

**Comment by galenlin** [comment]
> lib.x 模块不支持 有 layout文件？

是什么让你有了这种假设？提问可以专业点吗？你是程序员吗，靠凭空猜测？有根据吗？

你验证过吗：

1. 当有layout的时候报错
2. 没有layout的时候不报错

这种基本的排除做过吗？

严谨一点吧。我认为这是作为一个程序员基本的原则。

回到问题上来。我觉得很有必要啰嗦下如何 **独立自主** 的查问题：

1. 很明显已经有报错信息了：

  `Dependency bfbm-core:lib.style:unspecified on project app resolves to an APK archive`

2. 把非关键信息 (*主谓宾* 的 *宾语*) 去掉，可以得到：

  `Dependency on project resolves to an APK archive` ---- (1)

3. 拿这个去Google我相信会得到很多答案。

  于是你明白了：“哦，原来指定为 com.android.application 的模块不能被其他模块所依赖”。

4. 如果你在我们的issues里搜索，其实甚至能直接知道为什么：

  #237 #153 

原理其实在[wiki](https://github.com/wequick/Small/blob/master/Android/DevSample/buildSrc/README.md)什么的也都有，对于 `lib.*` 模块：

1. 在开发时期，被声明为 `com.android.library` ，以供 `app.*` 模块引用
2. 在编译时期，被动态切换为 `com.android.application`，以打包成插件

所以 "宿主不能依赖`lib.*`"，否则编译时期会报错，当然 `app.*` 也不能被依赖，总结一句话就是：

>  宿主不能依赖插件

然而，你可能又有疑惑了，为什么不能依赖呢，是不是需要支持一下？
这又回到另一个问题：关于宿主与插件的关系，如果你仔细看下issue，会发现这里有答案：

#207 

最后一句话：“严谨求学，独立探索”，与君共勉。
