### ISSUE TITLE
宿主 Application 和插件 Application 之间是什么关系呢？

### ISSUE THREAD

**Issue by pessonljxpd** [wequick/Small#288]
宿主 Application 和插件 Application 之间是什么关系呢？我插件中定义了插件 Application 的类型后，在运行程序的时候，提示我 “PluginApplication cannot cast to HostApp”

**Comment by galenlin** [comment]
插件application只是用来分发启动事件，没有实际意义。
在插件application里通过 `getApplicationContext()` 可以得到宿主application。

**Comment by pessonljxpd** [comment]
我在 Plugin 中的某个Activity中调用 getApplication 后，返回的是宿主的Application。请问：在用了咱们这个 Small 框架之后，我怎么在 Plugin 中的某个 Activity 中去调用 getApplication 从而拿到当前 Plugin 的Application呢？

**Comment by galenlin** [comment]
取不到的。建议用实例类来做。

**Comment by pessonljxpd** [comment]
好的，多谢

**Comment by xiaweizi** [comment]
@galenlin 如果单 module 可以拿到宿主的 ApplicationContext吗？
比如QQ分享需要拿到宿主包名进行创建，应该怎么搞

**Comment by galenlin** [comment]
@xiaweizi 直接 getApplicationContext() 即可
