### ISSUE TITLE
“我们的最终方案是对资源包进行重新打包，重设资源id”的疑惑

### ISSUE THREAD

**Issue by liuguangli** [wequick/Small#29]
看了资源打包那段，“我们的最终方案是对资源包进行重新打包，重设资源id”，是指插件包的资源重新打包么？ 宿主发布之后，后续更新插件包单独编译不会引起资源id冲突问题吧

**Comment by galenlin** [comment]
我不知道你是否运行过Sample 如果没有 建议你先试下 里面包含了升级示例。
