### ISSUE TITLE
能否只指定一个插件或者Lib去build成so,并且移动到smallLibs目录

### ISSUE THREAD

**Issue by gordonpro** [wequick/Small#304]
文档中发现 
`gradlew buildLib `  构建全部 lib.*
`gradlew buildBundle`  构建全部app.*

如果我只修改了 app.map ，并且只想构建它,  需要怎么做？

我试过 `gradlew -p app.map buildBundle`  
但是直接 build 了一个app.map 对应的 apk 出来，在 smallLibs 目录也没有构建出 .so

**Comment by gordonpro** [comment]
感觉因为涉及资源文件的修改，所以只能够全部项目构建

**Comment by galenlin** [comment]
README上有写的：
`./gradlew :app.map:assembleRelease`

**Comment by gordonpro** [comment]
嗯，可以
