### ISSUE TITLE
ui route的配置中，json文件命名为bundles.json是一定要这个命名吗

### ISSUE THREAD

**Issue by warrior1991** [wequick/Small#308]
在这个配置，我按照ui route的规则，配置好了，但是在开启launchActivity的时候，怎么也跳转不到MainActivity，看了warn日志，将命名改成bundle.json才正常了，请问这个命名是可以修改的吗？还是官方写错了

**Comment by galenlin** [comment]
文档有误，应该是 `bundle.json`

**Comment by warrior1991** [comment]
还请更正下文档，以免更多人走了误区

**Comment by galenlin** [comment]
@warrior1991 3q，已更新
