### ISSUE TITLE
插件项目名和包名的疑问

### ISSUE THREAD

**Issue by pscj** [wequick/Small#311]
在changelog里发现了以下：
• 取消模块名lib.xx限制, 可在build.gradle里通过bundles ('lib', [moduleA, moduleB])来配置
• 取消模块包名*.app.*限制, 可在bundle.json里通过type字段来配置 (*.app.*, *.appXX形式的包名无需配置, 可被自动识别)

是不是说*.app.*的模块名规则还需要保持，lib.xxx的包名规则还需要保持？

**Comment by galenlin** [comment]
@pscj 应该是都取消限制了。

1. 模块名可以自由定义，类型可以在build.gradle里进行声明
2. 包名可以自由定义，类型可以在bundle.json里进行声明
