### ISSUE TITLE
 Please recompile com.mobile.indiapp.app.demoplugin use gradle-small 0.9.0 or above

### ISSUE THREAD

**Issue by chikeong** [wequick/Small#313]
`
java.lang.RuntimeException: Please recompile com.mobile.indiapp.app.demoplugin use gradle-small 0.9.0 or above
at 
09-18 16:39:40.242 22540-22678 E/DEBUG: net.wequick.small.BundleParser.parsePackage(BundleParser.java:233)
09-18 16:39:40.242 22540-22678 E/DEBUG:     at 
09-18 16:39:40.242 22540-22678 E/DEBUG: net.wequick.small.BundleParser.parsePackage(BundleParser.java:159)
09-18 16:39:40.242 22540-22678/com.mobile.indiapp E/DEBUG:  at 
09-18 16:39:40.243 22540-22678 E/DEBUG: net.wequick.small.BundleParser.parsePackage(BundleParser.java:130)
09-18 16:39:40.243 22540-22678 E/DEBUG:     at 
09-18 16:39:40.243 22540-22678 E/DEBUG: net.wequick.small.SoBundleLauncher.preloadBundle(SoBundleLauncher.java:92)
09-18 16:39:40.243 22540-22678 E/DEBUG:     at 
09-18 16:39:40.243 22540-22678 E/DEBUG: net.wequick.small.BundleLauncher.resolveBundle(BundleLauncher.java:112)
`

我明明是用 
`
classpath 'net.wequick.tools.build:gradle-small:1.0.0-beta9
` 
，怎么会报这个错呢？

**Comment by chikeong** [comment]
@galenlin  麻烦帮忙看一下

**Comment by galenlin** [comment]
@chikeong 方便把工程发我下吗。需要调试下

**Comment by chikeong** [comment]
@galenlin  抱歉，因为我是用我们的公司主项目代码，改成small的配置，然后再加个demo作为plugin调试的，完整的代码无法提供，你看看需要哪些代码片段需要查看的，我可能可以发部分出来

**Comment by galenlin** [comment]
@chikeong 看看做个最小化可复现的demo

**Comment by chikeong** [comment]
@galenlin  ok,我把 这个demo 发送到你的gmail 邮箱 oolgloo.2012@gmail.com 可以吗

**Comment by galenlin** [comment]
可以

**Comment by Huyamin150** [comment]
@chikeong 哥们你这个问题解决了么，我也碰到了这个问题
