### ISSUE TITLE
使用gradlew buildLib -q编译出现Could not get unknown property 'assembleRelease' for project ':app' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by lishoulin** [wequick/Small#315]
Could not get unknown property 'assembleRelease' for project ':app' of type org.gradle.api.Project.

**Comment by parcool** [comment]
改回这个版本就ok了。`classpath 'com.android.tools.build:gradle:2.1.3'`
当然，也可能可以更高，我没试，你试好了告诉我？

**Comment by galenlin** [comment]
@lishoulin @parcool `gradle-small:1.0.0-alpha1` 已支持到`android gradle 2.2.0`，请尝试。

**Comment by kgmeng** [comment]
在Sample里面的build.gradle将
classpath 'net.wequick.tools.build:gradle-small:1.0.0-beta9'
改成
classpath 'net.wequick.tools.build:gradle-small:1.0.0-alpha1'

在Run app的时候还是会出现
Information:Gradle tasks [:app:clean, :app:generateWequickDebugSources, :app:generateWequickDebugAndroidTestSources, :app:prepareWequickDebugUnitTestDependencies, :app:mockableAndroidJar, :app:assembleWequickDebug]
Error:Execution failed for task ':app:preBuild'.
> Task with name 'assembleRelease' not found in project ':app'.

**Comment by kgmeng** [comment]
降低了下版本，as 2.2,  gradle 2.10,  android plugin version 2.1.2, small 1.0.0-beta9就没问题了,之前gradle用了2.14

**Comment by struggle111** [comment]
我也遇到这个问题了：
## 错误信息：
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':nice-image-processor'.
   > A problem occurred configuring project ':lib.utils'.
      > Could not get unknown property 'jarReleaseClasses' for project ':lib.utils' of type org.gradle.api.Project.

## build.gradle配置（project）
我的配置如下，（build gradle 2.2.0）
dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0'
        classpath 'net.sf.proguard:proguard-gradle:4.11'
        classpath 'com.tencent.bugly:symtabfileuploader:2.0.7'
        classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.4.13"
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3'
        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.0.9'
        classpath 'net.wequick.tools.build:gradle-small:1.1.0-beta4'
    }
.......
task wrapper(type: Wrapper) {
    gradleVersion = '2.14.1'
}
请问怎么解决???

**Comment by struggle111** [comment]
异常信息如下：
 Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'jarReleaseClasses' for project ':lib.utils' of type org.gradle.api.Project.

**Comment by struggle111** [comment]
我的gradle-wrapper.properties文件如下：
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-bin.zip

**Comment by qaz349293703** [comment]
A problem occurred configuring project ':app'.
> Could not get unknown property 'explodedDir' for task ':app:prepareComAndroidSupportAnimatedVectorDrawable2520Library' of type com.an
droid.build.gradle.internal.tasks.PrepareLibraryTask.

**Comment by xufan** [comment]
@qaz349293703 This can happen when you use the new version `2.3.0` of gradle. We are working on upgrade gradle-core from `2.2.0+` to `2.3.0`.For now you could rollback your gradle version to `2.2.0+`.
