### ISSUE TITLE
Error:Could not get unknown property 'assembleRelease' for project ':app' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by marklogg** [wequick/Small#323]
按照readme 新建一个project, 然后build提示上面的错误，build.gradle配置如下：
[// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

// ------------------------------------------------------------------

// Small plugin

//

// Cannot automatically merge the buildscript in Android Studio 2.0,

// uncomment following to go into force.

// ------------------------------------------------------------------

//

buildscript  {

    dependencies {
        classpath 'net.wequick.tools.build:gradle-small:1.0.0-beta9'
    }
}

apply plugin: 'net.wequick.small'

small {

    aarVersion = '1.1.0-beta5'

}
](url)

**Comment by marklogg** [comment]
android studio 2.2,

**Comment by ouyangpeng** [comment]
@marklogg  you can try   classpath 'com.android.tools.build:gradle:2.0.0'

**Comment by galenlin** [comment]
这个问题在 #167 #315 中已有提问，请转往查看。关闭本问题。
