### ISSUE TITLE
引用support design包时，编译失败。

### ISSUE THREAD

**Issue by 601367322** [wequick/Small#330]
之前看到一个问题是关于混淆的，解决方法是
# Support Libraries
-dontwarn android.support.**
-keep class android.support.** { *; }
-keep interface android.support.** { *; }
貌似这个混淆已经被集成到gradle插件里了吧。

但是我加上之后报错
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForDebugFlavorsRelease'.
> java.io.IOException: Can't write [/Users/bingbing/Documents/project/tengyue-android/app/build/intermediates/transforms/proguard/debugFlavors/release/jars/3/1f/main.jar] (Can't read [/Users/bingbing/Documents/project/tengyue-android/app/build/intermediates/exploded-aar/com.android.support/design/24.2.1/jars/classes.jar(;;;;;;**.class)] (Duplicate zip entry [classes.jar:android/support/design/widget/Snackbar$3.class]))

**Comment by galenlin** [comment]
有具体的报错吗？Sample里也是有design包的，混淆正常。

**Comment by 601367322** [comment]
好像是包冲突了吧，但是我找不到冲突的

Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForDebugFlavorsRelease'.
> java.io.IOException: Can't write [/Users/bingbing/Documents/project/tengyue-android/app/build/intermediates/transforms/proguard/debugFlavors/release/jars/3/1f/main.jar] (Can't read [/Users/bingbing/Documents/project/tengyue-android/app/build/intermediates/exploded-aar/com.android.support/design/24.2.1/jars/classes.jar(;;;;;;**.class)] (Duplicate zip entry [classes.jar:android/support/design/widget/Snackbar$3.class]))

**Comment by 601367322** [comment]
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForDebugFlavorsRelease'.
java.io.IOException: Can't write [/Users/bingbing/Documents/project/tengyue-android/app/build/intermediates/transforms/proguard/debugFlavors/release/jars/3/1f/main.jar] Can't read [/Users/bingbing/Documents/project/tengyue-android/app/build/intermediates/exploded-aar/com.android.support/design/24.2.1/jars/classes.jar(;;;;;;**.class)] (Duplicate zip entry [classes.jar:android/support/design/widget/Snackbar$3.class])

**Comment by 601367322** [comment]
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForDebugFlavorsRelease'.
> java.io.IOException: Can't write [/Users/bingbing/Documents/project/tengyue-android/app/build/intermediates/transforms/proguard/debugFlavors/release/jars/3/1f/main.jar] Can't read [/Users/bingbing/Documents/project/tengyue-android/app/build/intermediates/exploded-aar/com.android.support/design/24.2.1/jars/classes.jar(;;;;;;**.class)] (Duplicate zip entry [classes.jar:android/support/design/widget/Snackbar$3.class

**Comment by 601367322** [comment]
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForDebugFlavorsRelease'.
 java.io.IOException: Can't write [/Users/bingbing/Documents/project/tengyue-android/app/build/intermediates/transforms/proguard/debugFlavors/release/jars/3/1f/main.jar] Can't read [/Users/bingbing/Documents/project/tengyue-android/app/build/intermediates/exploded-aar/com.android.support/design/24.2.1/jars/classes.jar(;;;;;;**.class)] Duplicate zip entry [classes.jar:android/support/design/widget/Snackbar$3.class]

**Comment by 601367322** [comment]
貌似跟插件没关系，但是我实在找不到问题的原因了。。

**Comment by 601367322** [comment]
好吧，找到原因了。。
-applymapping ../mappings/mapping.txt
我用了旧的映射文件。
真的蠢。。

**Comment by dukezhao** [comment]
能具体说下怎么解决的吗？

**Comment by dreamDemo** [comment]
也碰到了 相同的问题请问是什么原因呀
