### ISSUE TITLE
如果我需要修改small

### ISSUE THREAD

**Issue by hjw541988478** [wequick/Small#342]
如何编译本地调试呀

**Comment by xufan** [comment]
使用```DevSample```那个工程 可以调试small的代码

**Comment by galenlin** [comment]
>注：issue不再接收咨询类问题(可在QQ群上提问)，报告错误参考[贡献指南](https://github.com/wequick/Small/blob/master/%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97.md)
