### ISSUE TITLE
framework如何签名？

### ISSUE THREAD

**Issue by lqwang521** [wequick/Small#344]
请问iOS插件化，使用动态framework，那么framework如何进行签名呢？而且多个framework要一个一个签名吗？

**Comment by galenlin** [comment]
在Framework的Project可以配置签名，需要一个个配，或者可以自己写个脚本（没试过）。

>注：issue不再接收咨询类问题（可在QQ群上提问），报告错误参考[贡献指南](https://github.com/wequick/Small/blob/master/%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97.md)
