### ISSUE TITLE
Android studio启动DevSample，配置失败问题

### ISSUE THREAD

**Issue by cangwang** [wequick/Small#349]
提示错误
Error:Execution failed for task ':small:processDebugAndroidTestManifest'.
> java.lang.RuntimeException: Manifest merger failed : Attribute provider#net.wequick.small.SetUpProvider@authorities at manifestMerger2048859972902660819.xml requires a placeholder substitution but no value for <SMALL_SETUP_PROVIDER_HOST> is provided.

**Comment by galenlin** [comment]
@cangwang 先显示赋值一个值，这个bug我稍后看下怎么处理
