### ISSUE TITLE
如何在一个framework中实现多个controller的交互？

### ISSUE THREAD

**Issue by cj768025549** [wequick/Small#350]
如何在一个framework中实现多个controller的交互？现在的一个xcodeproj只绑定了一个ViewController,如何添加多个？

**Comment by galenlin** [comment]
参考 wiki/UI Route 进行配置。

**Comment by galenlin** [comment]
> 注：提问参考[贡献指南](https://github.com/wequick/Small/blob/master/%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97.md)，此类问题可在群里提问，issue只处理框架的错误
