### ISSUE TITLE
添加新模块之后

### ISSUE THREAD

**Issue by cj768025549** [wequick/Small#351]
所有的vc与uri的对应关系都放在bundle.json里面，如果我添加了新的模块，在bundle.json里面没有的，我是不是要更新bundle.json文件？需要更新整体应用吗，bundle.json可以自定义读取的路径吗

**Comment by galenlin** [comment]
bundle.json可以独立更新。

> 注：提问参考[贡献指南](https://github.com/wequick/Small/blob/master/%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97.md)，此类问题可在群里提问，issue只处理框架的错误
