### ISSUE TITLE
Small最新版本在Android Studio2.2会提示Manifest merger failed的问题

### ISSUE THREAD

**Issue by mygift2016** [wequick/Small#352]
Small的Mainfest:
        <provider
            android:exported="false"
            android:authorities="${SMALL_SETUP_PROVIDER_HOST}"
            android:name=".SetUpProvider"/>

构建项目会提示：
Error:Execution failed for task ':app.dispatchTask:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

将android:authorities改成任意名称后，构建项目成功，不再出现Manifest merger failed的提示。
        <provider
            android:exported="false"
            android:authorities="MPSFinest"
            android:name=".SetUpProvider"/>

另外Small最新版本，在没执行gradlew small之前，IDE对SMALL_SETUP_PROVIDER_HOST 部分是有报红的，虽然影响不大，但对于新学习和了解Small的人会有干扰，建议尽可能完善。

**Comment by galenlin** [comment]
DevSample是开发版本，与 #349 重复，关闭
