### ISSUE TITLE
BUG: 进程服务，bindservice报ClassNotFoundException

### ISSUE THREAD

**Issue by kongyan4696** [wequick/Small#354]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

我在插件模块中使用了 bindservice开启一个进程服务
示例代码：https://github.com/kongyan4696/Small/tree/master/Android/Sample

## 你期望的结果是什么？

进程服务能正常运行，能正常bind交互。

## 实际结果是什么？

启动时出现 该 服务的类文件找不到的现象。

尝试定位了下， 程序崩溃于：
ContextImpl.java  bindServiceCommon(Intent service, ServiceConnection conn, int flags,UserHandle user)

`            int res = ActivityManagerNative.getDefault().bindService(
                mMainThread.getApplicationThread(), getActivityToken(), service,
                service.resolveTypeIfNeeded(getContentResolver()),
                sd, flags, getOpPackageName(), user.getIdentifier());`

之前使用 small : 
    aarVersion = '1.1.0-beta5'
    classpath 'net.wequick.tools.build:gradle-small:1.0.0-beta9'   未出现此问题。

Small发送运行报错，报错信息如下：
```
FATAL EXCEPTION: main Process: net.wequick.example.small:aaa, PID: 19865 
java.lang.RuntimeException: Unable to instantiate service net.wequick.example.small.appok_if_stub.MyService:
java.lang.ClassNotFoundException: Didn't find class"net.wequick.example.small.appok_if_stub.MyService" on path: DexPathList[[zip file "/data/app/net.wequick.example.small-2/base.apk"],nativeLibraryDirectories=[/data/app/net.wequick.example.small-2/lib/arm, /system/fake-libs, /data/app/net.wequick.example.small-2/base.apk!/lib/armeabi, /system/lib, /vendor/lib]] 
at android.app.ActivityThread.handleCreateService(ActivityThread.java:3147) 
at android.app.ActivityThread.-wrap5(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6077) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) Caused by: 
java.lang.ClassNotFoundException: Didn't find class"net.wequick.example.small.appok_if_stub.MyService" on path: DexPathList[[zip file "/data/app/net.wequick.example.small-2/base.apk"],nativeLibraryDirectories=[/data/app/net.wequick.example.small-2/lib/arm, /system/fake-libs, /data/app/net.wequick.example.small-2/base.apk!/lib/armeabi, /system/lib, /vendor/lib]] 
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:380) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:312) 
at android.app.ActivityThread.handleCreateService(ActivityThread.java:3144) at android.app.ActivityThread.-wrap5(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6077) 
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

### Compile-time

```
  gradle-small plugin : 1.1.0-beta3 (project)
            small aar : 1.1.0-beta7 (project)
          gradle core : 2.1.2
       android plugin : 2.2.2
                   OS : Windows 7 x86
```

### Runtime

```
  Device : Huawei p7,xiaomi note等
     SDK : Android 7.0
     ABI : armeabi-v7a
```

**Comment by kongyan4696** [comment]
@galenlin  

small环境:
   classpath 'net.wequick.tools.build:gradle-small:1.1.0-beta3'
   aarVersion = '1.1.0-beta7'

问题描述: 
   开启一个远程服务将会引发崩溃，普通服务不会。

示例代码：https://github.com/kongyan4696/Small/tree/master/Android/Sample
实例代码与最新Sample区别： 
     Android/Sample/app+stub/src/main/AndroidManifest.xml
     Android/Sample/app.ok-if-stub/src/main/java/net/wequick/example/small/appok_if_stub/MainFragment.java


崩溃log日志：

`FATAL EXCEPTION: main Process: net.wequick.example.small:aaa, PID: 19865 java.lang.RuntimeException: Unable to instantiate service net.wequick.example.small.appok_if_stub.MyService: java.lang.ClassNotFoundException: Didn't find class "net.wequick.example.small.appok_if_stub.MyService" on path: DexPathList[[zip file "/data/app/net.wequick.example.small-2/base.apk"],nativeLibraryDirectories=[/data/app/net.wequick.example.small-2/lib/arm, /system/fake-libs, /data/app/net.wequick.example.small-2/base.apk!/lib/armeabi, /system/lib, /vendor/lib]] at android.app.ActivityThread.handleCreateService(ActivityThread.java:3147) at android.app.ActivityThread.-wrap5(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6077) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) Caused by: java.lang.ClassNotFoundException: Didn't find class "net.wequick.example.small.appok_if_stub.MyService" on path: DexPathList[[zip file "/data/app/net.wequick.example.small-2/base.apk"],nativeLibraryDirectories=[/data/app/net.wequick.example.small-2/lib/arm, /system/fake-libs, /data/app/net.wequick.example.small-2/base.apk!/lib/armeabi, /system/lib, /vendor/lib]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56) at java.lang.ClassLoader.loadClass(ClassLoader.java:380) at java.lang.ClassLoader.loadClass(ClassLoader.java:312) at android.app.ActivityThread.handleCreateService(ActivityThread.java:3144) at android.app.ActivityThread.-wrap5(ActivityThread.java)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)  at android.os.Handler.dispatchMessage(Handler.java:102)  at android.os.Looper.loop(Looper.java:154)  at android.app.ActivityThread.main(ActivityThread.java:6077)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) `

**Comment by galenlin** [comment]
@kongyan4696 看了下，指定了`android:process`的组件要把实现类放到宿主。因为我们Hook的只有当前应用程序的进程。

**Comment by kongyan4696** [comment]
@galenlin  不太好弄，项目里有个进程是第三方播放器启动的，类文件在jar包中。要移动到宿主内，工作量比较大。


另外：
aarVersion = '1.1.0-beta5'
classpath 'net.wequick.tools.build:gradle-small:1.0.0-beta9' 。

这个版本不会出现这个问题，应该是在这后续的更新导致的，

现在我在调试，看看是哪个地方引起的。

**Comment by kongyan4696** [comment]
@galenlin  现在的问题是：
ActivityManagerNative.getDefault().bindService( mMainThread.getApplicationThread(), getActivityToken(), service, service.resolveTypeIfNeeded(getContentResolver()), sd, flags, getOpPackageName(), user.getIdentifier());

这个过程，系统找不到对应的类文件。

关于service进程生命周期的事情，我可以在service中在初始化一遍需要的过程就好了。

**Comment by galenlin** [comment]
好，已经找到问题了，我稍等提交到DevSample里

**Comment by kongyan4696** [comment]
测试，已解决。
