### ISSUE TITLE
推送问题

### ISSUE THREAD

**Issue by cj768025549** [wequick/Small#359]
如果采用更新framework的方式，如何设置各模块的bundleId？是跟主工程一样吗，我在网上查了一下，真机只能用通配的id，但是通配无法实现推送，不知作者是怎么解决的

**Comment by galenlin** [comment]
@cj768025549 模块是用通配符ID，推送相关的配置与代码还是要放到主工程。

**Comment by galenlin** [comment]
> 注：提问参考[贡献指南](https://github.com/wequick/Small/blob/master/%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97.md)，此类问题可在群里提问，issue只处理框架的错误

**Comment by tuxuzhang** [comment]
@galenlin 师兄，我在运用small开发中遇到几个问题。1 ： 我在主框架里面实现了pods工程， 并且insall AFNetworking第三方库， 现在我在子模块里面想要用这个AFNetworking 能怎么操作呢 ？2：子模块tagert工程能否支持pods？3：子模块的数据存储，在主框架中怎么得到？（反过来能实现也可以）请问 朋友能给点指点或建议吗？如果能可否留个联系方式？提前谢谢师兄了。
