### ISSUE TITLE
AS运行sample一直出错

### ISSUE THREAD

**Issue by SakuraLxm** [wequick/Small#362]
net::ERR_NAME_NOT_RESLVED  toast也是这个内容 是不是我配置没有正确
Step 3. Compile Plugins(编译插件) 这一步没有执行 该在哪里执行？

**Comment by galenlin** [comment]
提issue请先阅读[贡献指南](https://github.com/wequick/Small/blob/master/%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97.md)，不符规范关闭本问题。
