### ISSUE TITLE
Fragment 在 插件之间的调用，默认只能调起名称为“ MainFragment ”的 Fragment，请问 这是 Small 故意设计成这样的吗？

### ISSUE THREAD

**Issue by pessonljxpd** [wequick/Small#363]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

在 宿主 app 的 Launcher.activity 中调起 app.main 中的 一个 SplashFragment

## 你期望的结果是什么？

Small 框架能够正常调起，

## 实际结果是什么

程序运行错误，提示找不到 MainFragment。 我翻看了源码，Small 默认会创建名字 “MainFragment” 的 Fragment。

请问，您是故意要设计成这样的吗？为了尽量避免 Fragment 在插件之间的调用吗？

### Bundles

（注：编译时错误只需本行以上内容，运行时错误补充本行以下内容）

**Comment by galenlin** [comment]
MainFragment是主路由，其他的路由可以在bundle.json中配置，参考[wiki/UI Route](https://github.com/wequick/Small/wiki/UI-route)。

> 注：咨询类问题可在QQ群上提问，issue现只接收错误报告，关闭本问题。
