### ISSUE TITLE
兼容问题

### ISSUE THREAD

**Issue by andarly** [wequick/Small#365]
错误报告

你做了什么？

旧项目移植

你期望的结果是什么？

Small能够正确运行。

实际结果是什么？

模拟器api 23上可以运行   api 17、api19报错

 E/dalvikvm: Could not find class 'android.util.ArrayMap', referenced from method net.wequick.small.util.ReflectAccelerator.mergeResources
 E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.NoClassDefFoundError: com/*****/lib/common/LiefengRetrofit$1
加上 "support-core-utils"也不行
另外支不支持   app.main--> lib.common-->lib.core这种依赖模式
对使用aar的注意事项有没有相关详细文档？

**Comment by galenlin** [comment]
你好，你的问题细节不足，请先仔细阅读[贡献指南]，再根据文末模板来提问，感谢支持。
