### ISSUE TITLE
为什么不能按指定packageid生成

### ISSUE THREAD

**Issue by iofisher** [wequick/Small#366]
在app.main中添加
ext {
    packageId = 0x59
}
或者在gradle.properties中添加：　packageId=59

执行编译时提示时对的：[Small] building bundle 1 of 1 - app.main (0x59)
但是解压这个so后看到的R文件的数字，都是77开头的，并不是指定的id

使用的版本：classpath 'net.wequick.tools.build:gradle-small:1.1.0-beta3'
aarVersion = "1.1.0-beta9"

请问这是怎么回事？

**Comment by iofisher** [comment]
重新建了个项目，又可以了，又缓存么

**Comment by galenlin** [comment]
你好，修改 `packageId` 需要 clean.

> 注：提issue请参考[贡献指南](https://github.com/wequick/Small/blob/master/%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97.md)
