### ISSUE TITLE
Lib中远程依赖aar中的so包问题

### ISSUE THREAD

**Issue by xufan** [wequick/Small#367]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

在Lib.utils中远程依赖了AAR， 这里远程依赖了Fresco。
` compile 'com.facebook.fresco:fresco:0.14.1'`

## 你期望的结果是什么？

Small能够正确把远程依赖的AAR中Fresco的jniLib包打入Lib*.so的jni目录中。

## 实际结果是什么？

Small没有把Fresco中的jniLib打入Lib*.so的jni目录中。在Fresco的imagepipeline中有jni包libimagepipeline.so但是没有在Lib*.so的jni中找到，Lib*.so的jni中只有本地依赖的jni_plugin的jni包。

### Compile-time

```
  gradle-small plugin : 1.1.0-beta3 (project)
            small aar : 1.1.0-beta9 (project)
          gradle core : 2.14.1
       android plugin : 2.2.2
                   OS : Windows 10 10.0 (amd64)
```

### Bundles

| type |      name      |  PP  | sdk |  aapt  | support | file(armeabi)  |   size   |
|------|----------------|------|-----|--------|---------|----------------|----------|
| host | app            |      | 24  | 23.0.3 | 23.4.0  |                |          |
| stub | app+stub       |      | 24  | 23.0.3 | 23.4.0  |                |          |
| app  | app.main       | 0x77 | 24  | 23.0.3 | 23.4.0  | *_main.so      | 11.5 KB  |
| app  | app.mine       | 0x16 | 24  | 23.0.3 |         | *_mine.so      | 17.3 KB  |
| app  | app.ok-if-stub | 0x6a | 24  | 23.0.3 |         | *_stub.so      | 20.9 KB  |
| app  | app.detail     | 0x67 | 24  | 23.0.3 | 23.4.0  | *_detail.so    | 7.3 KB   |
| app  | app.home       | 0x70 | 24  | 23.0.3 |         | *_home.so      | 11.4 KB  |
| lib  | lib.analytics  | 0x76 | 24  | 23.0.3 |         | *_analytics.so | 125.7 KB |
| lib  | lib.utils      | 0x73 | 24  | 23.0.3 | 23.4.0  | *_utils.so     | 515.4 KB |
| lib  | lib.style      | 0x79 | 24  | 23.0.3 | 23.4.0  | *_style.so     | 4.6 KB   |
| web  | web.about      |      | 24  | 23.0.3 | 23.4.0  | *_about.so     | 24.5 KB  |

**Comment by xufan** [comment]
看起来有referenced  issue https://github.com/wequick/Small/issues/87

**Comment by xufan** [comment]
已在#368 中修复

**Comment by linjson** [comment]
@xufan主分支上看不到,是还没合并吗?
