### ISSUE TITLE
下载下来Small，运行后提示找不到网页，点击链接提示如下

### ISSUE THREAD

**Issue by benshayu2015** [wequick/Small#369]
net::ERR_NAME_NOT_RESOLVED

**Comment by jarvan11** [comment]
遇到了同样的问题？没人解答？

**Comment by galenlin** [comment]
请先根据文档编译

**Comment by joychen1579** [comment]
我也是一样的问题。http://m.wequick.net/demo/ 这个地址打不开

**Comment by galenlin** [comment]
@joychen1579 编译完是会跳转到插件的，不会跳往那个网页的

**Comment by galenlin** [comment]
此外，请看下首页的贡献指南，可以避免不必要的问题。同时issue的提交应遵循规范。
