### ISSUE TITLE
MySmall工程不能正常运行

### ISSUE THREAD

**Issue by lambor** [wequick/Small#37]
根据指示建的MySmall工程不能正常运行，停留在launchactivity中，不能跳转到app.main。

**Comment by galenlin** [comment]
buildLib, buildBundle是否执行了？

**Comment by lambor** [comment]
执行了，没有报错

**Comment by galenlin** [comment]
真机运行请确认：Sample/app/smallLibs/armeabi下是否有生成*.so文件
模拟器确认：Sample/app/smallLibs/x86下有文件

**Comment by lambor** [comment]
是在data文件夹下吗？

**Comment by galenlin** [comment]
电脑的目录下

**Comment by lambor** [comment]
工程中MySmall/app/smallLibs/armeabi/有libcom_*******_main.so

**Comment by galenlin** [comment]
bundle.json配置了吗

**Comment by lambor** [comment]
配置了，
{
  "version": "1.0.0",
  "bundles": [
    {
      "uri": "main",
      "pkg": "com.example.mysmall.app.main"
    }
  ]
}

刚才的so文件名：libcom_example_mysmall_app_main.so

**Comment by galenlin** [comment]
签名设置了吗

**Comment by lambor** [comment]
没有。必须设置吗。我只是在debug模式

**Comment by galenlin** [comment]
需要配一个签名。插件启动会判断签名一致性

**Comment by lambor** [comment]
哦，谢谢

**Comment by lambor** [comment]
还是不行啊

**Comment by galenlin** [comment]
确认下有没有步骤遗漏https://github.com/wequick/Small/tree/master/Android，或者跟Sample工程比对下

**Comment by lambor** [comment]
添加签名文件后是不是还需要执行buildLib, buildBundle

**Comment by galenlin** [comment]
恩，，

**Comment by lambor** [comment]
现在是报错，错误定位到app.main MainActivity的OnCreate方法
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mysmall/net.wequick.small.A.0}: android.view.InflateException: Binary XML file line #44: Error inflating class <unknown>

Caused by: android.view.InflateException: Binary XML file line #44: Error inflating class <unknown>

**Comment by lambor** [comment]
再问一个问题，Small.setBaseUri("http://example.com/"); 内容可以随意吗

**Comment by galenlin** [comment]
,,可以。用于html5跨平台，如果没有m站可以忽略

**Comment by coolara** [comment]
你好 galenlin， 请问html5怎么用small 有例子吗。 我们是用ionic3开发的app
