### ISSUE TITLE
一直buildBundle报错:app.main:processReleaseResources!

### ISSUE THREAD

**Issue by jionkang** [wequick/Small#375]

**Comment by jionkang** [comment]
Error:Execution failed for task ':app.main:processReleaseResources'.
> In strict mode, we do not allow vendor aars, please declare them in host build.gradle:
    - compile('com.android.support:design:23.4.0')
or turn off the strict mode in root build.gradle:
    small {
        strictSplitResources = false
    }


最后android  studio提示我这个 然后
 strictSplitResources = false加上可以编译了 
但是md的控件报错 
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.x.x.smalldemo/com.xx.xxx.smalldemo.app.main.MainActivity}: android.view.InflateException: Binary XML file line #16: Error inflating class android.support.design.widget.FloatingActionButton

**Comment by jsjxsy** [comment]
要先运行 ./gradlew buildLib -q
再运行./gradlew buildBundle -q
亲自测试

**Comment by jionkang** [comment]
md貌似appcompat写到宿主工程就好了
