### ISSUE TITLE
lib依赖远程第三方库的jar重复打包

### ISSUE THREAD

**Issue by xufan** [wequick/Small#378]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

在lib插件包中依赖了远程第三方库（该库属于是jar包分类而非aar，例如fastjson、glide），在宿主中也申明依赖该远程第三方库。

## 你期望的结果是什么？

第三方库的class只打在宿主中。

## 实际结果是什么？

产出的lib中包含了第三方库的class文件，没有在transform阶段抽离。

分析：
在`StripAarTransform`这个类中对插件产生dex之前对jarInput没有正确抽离相关三方库的代码，只是抽离了aar类型三方库的代码。
```grooy
small.splitAars.each {
            splitPaths.add(new File(small.aarDir, "$it.group/$it.name").absolutePath)
  }
```
目前我的解决办法：
在`AppPlugin`中的`hookPreReleaseBuild`方法中收集对应的jar包信息，以供transform做抽离判断。
```grooy
File jar = new File(rootSmall.preLinkJarDir, "$lib.name-D.txt")
```

**Comment by galenlin** [comment]
@xufan 这个是说，双方 libs 目录下有同样的 jar 吗？

**Comment by xufan** [comment]
是lib或者app中的第三方依赖在expend-aar目录下归类于jar类型 所以没有被剥离

**Comment by galenlin** [comment]
ok, any PR refer to this?

**Comment by xufan** [comment]
Wrong operating cause cover my first PR about https://github.com/wequick/Small/pull/368...
That fix about aar's so & assets not package in bundle.
