### ISSUE TITLE
[android]更新的问题

### ISSUE THREAD

**Issue by linjson** [wequick/Small#379]
更新下来的so文件,能在APP不重启的情况下,自动重新加载新的SO文件来实现热更新吗

**Comment by galenlin** [comment]
issue只接收bug，请参考[贡献指南](https://github.com/wequick/Small/blob/master/%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97.md)

**Comment by linjson** [comment]
有疑问哪里问?
