### ISSUE TITLE
app.detail 内存被回收后恢复显示时应用崩溃

### ISSUE THREAD

**Issue by baoti** [wequick/Small#38]
原因为 ClassLoader 找不到 A.0 类，luanchActivity出错

**Comment by galenlin** [comment]
感谢反馈，将于近期修复

**Comment by galenlin** [comment]
该问题已解决，请使用 small {aarVersion = '0.4.2'}

* 问题原因：由于后台被杀后，系统会创建一个新的application，从而原本注入的Instrumentation失效，无法动态创建插件Activity。
* 解决方法：实现占坑Activity - net.wequick.small.A，在后台被杀重启activity时进入A，在A中完成Small.setUp，并在onComplete中跳转至原插件Activity。
