### ISSUE TITLE
加入react-native,运行时异常,找不到so文件

### ISSUE THREAD

**Issue by linjson** [wequick/Small#381]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

我在插件模块中使用了`compile 'com.facebook.react:react-native:0.38.0'`. 我尝试了`./gradlew buildLib -q`方法，但结果是
```
Execution failed for task ':lib.util:processReleaseResources'.
> In strict mode, we do not allow vendor aars, please declare them in host build.gradle:
      - compile('com.facebook.react:react-native:0.38.0')
  or turn off the strict mode in root build.gradle:
      small {
          strictSplitResources = false
      }//我加了这句话
```

## 你期望的结果是什么？

Small能够正确编译数据绑定，并正确运行。

## 实际结果是什么？

可以编译,但是运行时报错,信息如下:
```
 java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so
```
### Compile-time

```
  gradle-small plugin : 1.1.0-beta4 (project)
            small aar : 1.1.0-beta9 (project)
          gradle core : 2.14.1
       android plugin : 2.2.2
                   OS : Mac OS X 10.12 (x86_64)
```

### Bundles

|  type  |       name       |   PP   |          file           |    size    |
|--------|------------------|--------|-------------------------|------------|
|  host  |  app             |        |                         |            |
|  app   |  app.main        |    |  *_main.so (x86)        |  1M   |
|  lib   |  lib.util        |    |  *_util.so (x86)  |  1.1M   |

（注：编译时错误只需本行以上内容，运行时错误补充本行以下内容）
### Runtime

```
  Device : 小米4
     SDK : Android 6.0.1
     ABI : armeabi-v7a/x86
```

**Comment by linjson** [comment]
我感觉rn库的so文件没打包进去

**Comment by galenlin** [comment]
@linjson 请查看下插件中是否打包进了相应的 so 文件：

```
aapt list app/smallLibs/x86/[your-bundle].so | grep lib/
```

**Comment by xufan** [comment]
seems like #367 I will commit a PR about fix this issue

**Comment by linjson** [comment]
![3523c41a-da6a-49da-b772-502b9a8e8b32](https://cloud.githubusercontent.com/assets/5102303/21134194/a82a464a-c157-11e6-8681-71e3b0405ec7.png)
执行后没什么结果
主app没有x86的文件夹,只有armeabi文件夹
![a34e5590-f4a5-4e80-af4b-4e76415f8ac6](https://cloud.githubusercontent.com/assets/5102303/21134248/dcf9b298-c157-11e6-949f-2cd433d56174.png)

**Comment by linjson** [comment]
@xufan,合并到master上了吗?

**Comment by jinyb09017** [comment]
原因其实是SoLoader加载，指定了具体的so路径。而插件解压出来的so路径不在这个路径里面。所以需要加入路径即可

**Comment by lhb11** [comment]
> 原因其实是SoLoader加载，指定了具体的so路径。而插件解压出来的so路径不在这个路径里面。所以需要加入路径即可

如何加入路径，谢谢
