### ISSUE TITLE
small中引入React Native出现跳转异常

### ISSUE THREAD

**Issue by halibobo** [wequick/Small#391]
| type |    name     |  PP  | sdk |  aapt  | support | file(armeabi) |  size  |
|------|-------------|------|-----|--------|---------|---------------|--------|
| host | app         |      | 23  | 23.0.3 | 23.4.0  |               |        |
| stub | app+stub    |      | 23  | 23.0.3 | 23.4.0  |               |        |
| app  | app.main    | 0x77 | 23  | 23.0.3 |         | *_main.so     | 7.1 KB |
| app  | app.product | 0x57 | 23  | 23.0.3 |         | *_product.so  | 5.8 KB |

问题说明：在app+stub分身模块里依赖 compile "com.facebook.react:react-native:+"  // From node_modules 后会导致 Small.openUri("main", MainActivity.this)不能正常跳转到指定的子模块；取消依赖后可以跳转
调试的的demo地址：https://github.com/halibobo/SmallReact

debug后发现问题出现在SoBundleLauncher中preloadBundle第92行
`BundleParser parser = BundleParser.parsePackage(plugin, packageName);`

![image](https://cloud.githubusercontent.com/assets/5876719/21516869/020c575c-cd15-11e6-92ef-27b32f38c6f9.png)
会执行!sourceFile.exists()为true,即sourceFile不能空但这个文件不存在！

**Comment by xufan** [comment]
因为react的远程aar里有jni相关so包 不是armeabi架构是v7a和x86的 由于Android机制手机cpu如果是v7a或者x86架构会优先去这两个文件夹里找相关so 而忽略掉armeabi目录下的插件so。
目前有两种解决方案：
1.不要在宿主里定义带有jni相关的aar依赖，在lib.*或者app.*中定义
2.使用buildFromAssets，具体参考DevSample

**Comment by halibobo** [comment]
@xufan 请教：
方案2里的使用buildFromAssets是在哪里？
![image](https://cloud.githubusercontent.com/assets/5876719/21519908/753b0d16-cd2b-11e6-8000-bc90bd890eff.png)
是这个吗?

**Comment by halibobo** [comment]
解决了！
