### ISSUE TITLE
app.xxx布局访问app+stub的资源无法找到，build bundle无法通过

### ISSUE THREAD

**Issue by luoxiaoxiaozi** [wequick/Small#395]
app.xxx的xml文件引用app+stub的资源文件提示找不到
 AAPT: No resource found that matches the given name (at 'background' with value '@drawable/account_bg_corners_white').
  但是在app.xxx的代码中动态引用account_bg_corners_white资源是可以通过，希望能直接在xml文件中直接引用

**Comment by galenlin** [comment]
提issue请先查阅贡献指南
