### ISSUE TITLE
Lib.zxing startActivityForResult 启动异常

### ISSUE THREAD

**Issue by kuwork** [wequick/Small#401]
# 错误报告

## 你做了什么？
我在lib.zxing插件中使用了[zxing-android-embedded](https://github.com/journeyapps/zxing-android-embedded)的代码。设置了两种方式在MainActivity去启动CaptureActivity:
* 第一种是使用内部IntentIntegrator类打开CaptureActivity
* 第二种方式参照IntentIntegrator类的原理，打开CaptureActivity
```java
@OnClick(R.id.btnScan)
    protected void OnScanClick(){
        IntentIntegrator integrator = new IntentIntegrator(MainActivity.this);
        integrator.setCaptureActivity(CustomCaptureActivity.class);
        integrator.setDesiredBarcodeFormats(IntentIntegrator.ALL_CODE_TYPES);
        integrator.setPrompt("Scan something");
        integrator.setOrientationLocked(true);
        integrator.setBeepEnabled(true);
        integrator.initiateScan();
    }
    @OnClick(R.id.btnScan2)
    protected void OnScan2Click(){
        //CustomCaptureActivity空继承CaptureActivity类
        Intent intent = new Intent(getBaseContext(), CustomCaptureActivity.class);
        intent.putExtra(Intents.Scan.PROMPT_MESSAGE, "Scan something");
        intent.putExtra(Intents.Scan.ORIENTATION_LOCKED, true);
        intent.putExtra(Intents.Scan.BEEP_ENABLED, true);
        startActivityForResult(intent,IntentIntegrator.REQUEST_CODE);
    }

@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
        if(result != null) {
            String toast;
            if(result.getContents() == null) {
                toast = "Cancelled from fragment";
            } else {
                toast = "Scanned from fragment: " + result.getContents();
            }

            Toast.makeText(getBaseContext(), toast, Toast.LENGTH_LONG).show();
        }
    }
```

IntentIntegrator 部分代码
```java
private final Activity activity;
...
public final void initiateScan() {
        startActivityForResult(createScanIntent(), REQUEST_CODE);
    }
protected void startActivityForResult(Intent intent, int code) {
        if (fragment != null) {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
                fragment.startActivityForResult(intent, code);
            }
        } else if (supportFragment != null) {
            supportFragment.startActivityForResult(intent, code);
        } else {
             activity.startActivityForResult(intent, code);
        }
    }
```

## 你期望的结果是什么？

什么原因引起的，和第二种方式一样返回。

## 实际结果是什么？

第一种方式启动CustomCaptureActivity后，onActivityResult立即回调了(并不是SingleTask)，输出：
> Cancelled from fragment
在CustomCaptureActivity内点击返回键，则直接把MainActivity关闭了。

第二种方式，则完全正常。正常关闭CustomCaptureActivity，获得返回值。

### Compile-time

```
  gradle-small plugin : 1.1.0-beta4 (project)
            small aar : 1.1.0-alpha1 (project)
          gradle core : 2.14.1
       android plugin : 2.2.3
       OS : Mac OS X 10.12 (x86_64)
```

### Runtime

```
  Device : Vivo Xplay5 Pro
     SDK : Android 5.1.1
     ABI : armeabi
```

**Comment by kuwork** [comment]
```java
public Intent createScanIntent() {
        Intent intentScan = new Intent(activity, getCaptureActivity());
        intentScan.setAction(Intents.Scan.ACTION);

        // check which types of codes to scan for
        if (desiredBarcodeFormats != null) {
            // set the desired barcode types
            StringBuilder joinedByComma = new StringBuilder();
            for (String format : desiredBarcodeFormats) {
                if (joinedByComma.length() > 0) {
                    joinedByComma.append(',');
                }
                joinedByComma.append(format);
            }
            intentScan.putExtra(Intents.Scan.FORMATS, joinedByComma.toString());
        }

        intentScan.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
        intentScan.addFlags(Intent.FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET);
        attachMoreExtras(intentScan);
        return intentScan;
    }
```
问题应该就出在这两句上
```java
     intentScan.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
        intentScan.addFlags(Intent.FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET);
```

**Comment by taoqiyang** [comment]
我也是刚看 不知道说的对不对   应该是你的activity没有在app里注册  所以启动的时候用的默认的启动方式，并且名字用的stub里面的默认名字pagename.A  因为前面开启的activity也是用的同样的stub里的默认名字pagename.A  所以当clearTop的时候就把之前启动的activity关了   所以应该可以把activity预先注册到app里或者只能用第二种方式不加flag

**Comment by kuwork** [comment]
AddFlags 前的栈
> TaskRecord{28cf191e #3041 A=com.ajb.anjubao.intelligent U=0 sz=2}
      Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x30200000 cmp=com.ajb.anjubao.intelligent/com.ajb.LaunchActivity }
        Hist #1: ActivityRecord{1c64de5e u0 com.ajb.anjubao.intelligent/net.wequick.small.A t3041}
          Intent { act=com.google.zxing.client.android.SCAN cat=[>com.ajb.app.main.CustomCaptureActivity] cmp=com.ajb.anjubao.intelligent/net.wequick.small.A (has extras) }
          ProcessRecord{302d59ea 19126:com.ajb.anjubao.intelligent/u0a364}
        Hist #0: ActivityRecord{39c9e96b u0 com.ajb.anjubao.intelligent/net.wequick.small.A t3041}
          Intent { cat=[>com.ajb.app.main.MainActivity] cmp=com.ajb.anjubao.intelligent/net.wequick.small.A }
          ProcessRecord{302d59ea 19126:com.ajb.anjubao.intelligent/u0a364}

AddFlags 后的栈

> TaskRecord{28cf191e #3041 A=com.ajb.anjubao.intelligent U=0 sz=1}
      Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x30200000 cmp=com.ajb.anjubao.intelligent/com.ajb.LaunchActivity }
        Hist #0: ActivityRecord{3e760ac9 u0 com.ajb.anjubao.intelligent/net.wequick.small.A t3041}
          Intent { cat=[>com.ajb.app.main.CustomCaptureActivity] flg=0x14000000 cmp=com.ajb.anjubao.intelligent/net.wequick.small.A (has extras) }
          ProcessRecord{302d59ea 19126:com.ajb.anjubao.intelligent/u0a364}

**Comment by kuwork** [comment]
@taoqiyang 的确没有在app里面注册。类文件在app.main 里。关于你说的stub，我不太明白。怎么注册到app里？

**Comment by taoqiyang** [comment]
我没试过  但是sample里面有个类似的例子    `app+stub里注册了一个`<activity android:name="net.wequick.example.small.appok_if_stub.MyRemoteActivity"
            android:process=":remote.activity"/>`  然后在app.ok-if-stub里面有这个activity

**Comment by taoqiyang** [comment]
<activity android:name="net.wequick.example.small.appok_if_stub.MyRemoteActivity"
            android:process=":remote.activity"/>

**Comment by taoqiyang** [comment]
代码拷不了  app+stub里注册了net.wequick.example.small.appok_if_stub.MyRemoteActivity

**Comment by taoqiyang** [comment]
好像不对   看了下栈MyRemoteActivity还是用默认的A.. 在研究下

**Comment by kuwork** [comment]
@galenlin  这个会不是Small里面 Launcher 的问题？

**Comment by kuwork** [comment]
@galenlin 有什么头绪么？怎么可以使用Flags ？

**Comment by kuwork** [comment]
转至 #415 ，终结这个
