### ISSUE TITLE
关于目录问题，可否将lib.*统一放入一类似Common的根目录

### ISSUE THREAD

**Issue by george5613** [wequick/Small#407]
尝试之后发现在编译阶段，lib间的项目引用关系出现丢失，报各种 package does not exist exception，只要是应用了其他lib的项目都无法正确编译通过。

**Comment by george5613** [comment]
安装DevSample中的setting进行修改顺利解决了问题

**Comment by tuxuzhang** [comment]
朋友，我在运用small开发中遇到几个问题

**Comment by tuxuzhang** [comment]
师兄，我在运用small开发中遇到几个问题。1 ： 我在主框架里面实现了pods工程， 并且insall AFNetworking第三方库， 现在我在子模块里面想要用这个AFNetworking 能怎么操作呢 ？2：子模块tagert工程能否支持pods？3：子模块的数据存储，在主框架中怎么得到？（反过来能实现也可以）请问 朋友能给点指点或建议吗？如果能可否留个联系方式？提前谢谢师兄了。
