### ISSUE TITLE
AddFlags 启动异常

### ISSUE THREAD

**Issue by kuwork** [wequick/Small#415]
# 错误报告

## 你做了什么？
我通过Intent启动一个在lib.*里面的Activity.
```java
        Intent intent = new Intent(MainActivity.this, CustomCaptureActivity.class);
        intent.putExtra(Intents.Scan.PROMPT_MESSAGE, "Scan something");
        intent.putExtra(Intents.Scan.ORIENTATION_LOCKED, true);
        intent.putExtra(Intents.Scan.BEEP_ENABLED, true);
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        startActivityForResult(intent, IntentIntegrator.REQUEST_CODE);
```

## 你期望的结果是什么？

从CustomCaptureActivity返回时，还是回到底层的MainActivity

## 实际结果是什么？

只要我添加了
```java
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
```
就不能回到MainActivity。直接到了桌面。

### Compile-time

```
  gradle-small plugin : 1.1.0-beta4 (project)
            small aar : 1.1.0-alpha1 (project)
          gradle core : 2.14.1
       android plugin : 2.2.3
       OS : Mac OS X 10.12 (x86_64)
```

### Runtime

```
  Device : Vivo Xplay5 Pro
     SDK : Android 5.1.1
     ABI : armeabi
```

**Comment by kuwork** [comment]
如果在MainActivity通过Intent先跳到SetActivity(仍然在app.main中)，再打开CustomCaptureActivity。返回时，直接回到了MainActivity。

**Comment by kuwork** [comment]
@galenlin 这个问题会在Small出现，能做一下解释么？

**Comment by galenlin** [comment]
我试下看看

**Comment by galenlin** [comment]
看了下，主要的问题在 CLEAR_TOP 这个 Flag 上，由于我们的占坑Activity的Component同为一个： `net.wequick.small.A`（以下简写为A），包括你所举例子中的 MainActivity。

所以这个过程应该是：
A A A A -> CLEAR_TOP启动 -> A ~A~ ~A~ ~A~ -> 返回Finish -> ~A~ => 桌面

虽然Small在应用进程对 A 设置了 `targetActivity` 使其能正确跳往插件Activity，但是系统进程的缓存中 `targetActivity` 是空的，从而出现上述流程。源码参见[ActivityRecord.java](https://github.com/android/platform_frameworks_base/blob/master/services/core/java/com/android/server/am/ActivityRecord.java#L661)。

可能的解决方法：

1. 某种方式hook掉ActivityRecord（在系统进程里，希望不大）
2. 进入 `wrapIntent` 后，清除 CLEAR_TOP Flag，模拟底层处理方式

**Comment by kuwork** [comment]
@galenlin 可以在Small里面修复吗？毕竟A->B->C,从C返回A的情景是普遍存在的，需要解决

**Comment by galenlin** [comment]
估计无法完美解决。临时的解决方案是把那个Activity放到宿主manifest来注册。

**Comment by kuwork** [comment]
@galenlin 模拟底层处理Flag方式不行吗？代码还是留在插件内，只是在宿主的mainfest注册吗？这算是Small的一个缺陷，没真正的解耦。

**Comment by galenlin** [comment]
> 代码还是留在插件内，只是在宿主的mainfest注册吗？
是的。

> 模拟底层处理Flag方式不行吗？
Framework层的ActivityStack细节颇多，暂不清楚直接简单的做个 _轮询Finish_ 能不能满足需求，需要进一步确认，你可以先尝试下看看。

**Comment by kuwork** [comment]
@galenlin 早点看到#207 就不用惆了。这应该放到项目源码里。

**Comment by galenlin** [comment]
@kuwork 首页贡献指南也建议看下，里面的 `理解 项目结构` 包含了#207

**Comment by kuwork** [comment]
在宿主注册CustomCaptureActivity，并且不再app.* 内注册，可以通过FLAG_ACTIVITY_CLEAR_TOP启动，并获取返回值。
FLAG_ACTIVITY_NEW_TASK 仍不支持。
同时添加FLAG_ACTIVITY_CLEAR_TOP和FLAG_ACTIVITY_NEW_TASK ，会在进入CustomCaptureActivity的同时，onActivityResult直接返回了。
