### ISSUE TITLE
旧项目集成small, 遇到的一个坑：模块名、包名如何改方便、快捷？？？

### ISSUE THREAD

**Issue by struggle111** [wequick/Small#426]
在集成的过程中，模块名、包名如何改方便、快捷？？？
  
## 我的思路：
     如：旧项目中有个lib module 叫 utils，然后我会新建一个module，叫lib.utils，包名也是  *.lib.utils，然后把旧项目的utils中所有的代码都移到lib.utils中，这样包名模块名是没有问题了。
## 遇到的问题：
     如果按我的思路，那整个项目中有用到utils的时候，都应该改成import *.lib.utils， 那这样的话，工作量就很大了，而且不止一个lib module啊。

**Comment by MaYunFei** [comment]
`model` 名字要改成 `lib.utils`， 包名 可以不改 ， 在 `bundle.json` 中可以用 `type` ，同样的 `app` 模块也是可以不改包名的

例子 
```json
{
  "version": "1.0.0",
  "bundles": [
    {
      "uri": "main",
      "type": "app", // 包名不改得添加type
      "pkg": "io.github.mayunfei.main" // 这个包名就没改
    },
    {
      "uri": "push",
      "type": "app",
      "pkg": "io.github.mayunfei.push_control"
    },
    {
      "type": "lib", // 得添加type
      "uri": "lib.push_sdk", // 包名不是 *lib.*
      "pkg": "io.github.mayunfei.push_sdk"
    },
    {
      "type": "lib",
      "uri": "lib.analytics",
      "pkg": "io.github.mayunfei.analytics"
    }
  ]
}
```

**Comment by struggle111** [comment]
ok, 好了，谢谢，一开始没发现还有type这个字段，我看wiki中似乎没有啊，你在哪儿找的，还有其他字段吗？？

**Comment by MaYunFei** [comment]
#311 
在 `Issues` 中搜索 `包名` 就可以看之前有人提过这个问题
在 项目上搜索 关键词 `type` 就能找到一些跟 `type` 有关的提交
也可以跟根 源码 看看 是怎么加载 这些 apk的

**Comment by struggle111** [comment]
ok, 学习了，谢谢
