### ISSUE TITLE
lib.* 的 R 文件中所有字段都是非 final，导致在 switch 时候会报非常量表达式错误

### ISSUE THREAD

**Issue by linchaolong** [wequick/Small#427]
发现 lib.*/app.stub 的 R 文件中所有字段都是非 final 

![image](https://cloud.githubusercontent.com/assets/16344622/23355725/147b7c6a-fd12-11e6-817a-06179152d660.png)

导致在 switch 时候会报非常量表达式错误

![image](https://cloud.githubusercontent.com/assets/16344622/23355770/48cfe690-fd12-11e6-974a-c44a953b1aa4.png)

small环境：
```
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'net.wequick.tools.build:gradle-small:1.1.0-beta4'
    }
}

apply plugin: 'net.wequick.small'

small {
    buildToAssets = false
    strictSplitResources = false
    aarVersion = '1.1.0-alpha1'
    android {
        compileSdkVersion = rootProject.ext.compileSdkVersion
        buildToolsVersion = rootProject.ext.buildToolsVersion
    }
}
```

**Comment by galenlin** [comment]
这个报错是AS的规定，Library模块的R不是常量，不能switch。

**Comment by linchaolong** [comment]
OK，谢谢，Library模块通过if判断就好了
