### ISSUE TITLE
7.0+ raw文件读取问题

### ISSUE THREAD

**Issue by xufan** [wequick/Small#429]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

我在插件app.home模块中使用了VideoView，去加载raw文件中的mp4文件，
```java
final String uri = "android.resource://" + getActivity().getPackageName() + "/" + R.raw.guide;
videoView.setVideoURI(Uri.parse(uri));
```

## 你期望的结果是什么？

能够在插件中放置视频raw文件，并且被正确读取。

## 实际结果是什么？

在7.0以下机型能正确读取,但是在7.0以及以上机型会出现找不到视频资源

运行warning，信息如下：
```
net.wequick.example.small E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
net.wequick.example.small E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
net.wequick.example.small W/ResourceType: No known package when getting value for resource number 0x70030000
net.wequick.example.small W/MediaPlayer: Couldn't open android.resource://net.wequick.example.small/1879244800: java.io.FileNotFoundException: Resource does not exist: android.resource://net.wequick.example.small/1879244800
net.wequick.example.small E/MediaPlayer: error (1, -2147483648)
net.wequick.example.small E/MediaPlayer: Error (1,-2147483648)
net.wequick.example.small D/VideoView: Error: 1,-2147483648
```
### Compile-time

```
  gradle-small plugin : 1.1.0-alpha2 (maven)
            small aar : 1.1.0-alpha2 (maven)
          gradle core : 2.14.1
       android plugin : 2.1.2
                   OS : Windows 10 10.0 (amd64)
```

### Bundles

| type |      name      |  PP  | sdk |  aapt  | support | file(armeabi)  |   size   |
|------|----------------|------|-----|--------|---------|----------------|----------|
| host | app            |      | 23  | 23.0.3 | 23.4.0  |                |          |
| stub | app+stub       |      | 23  | 23.0.3 | 23.4.0  |                |          |
| app  | app.main       | 0x77 | 23  | 23.0.3 | 23.4.0  | *_main.so      | 10.9 KB  |
| app  | app.mine       | 0x16 | 23  | 23.0.3 |         | *_mine.so      | 35.5 KB  |
| app  | app.ok-if-stub | 0x6a | 23  | 23.0.3 |         | *_stub.so      | 20.2 KB  |
| app  | app.detail     | 0x67 | 23  | 23.0.3 | 23.4.0  | *_detail.so    | 6.6 KB   |
| app  | app.home       | 0x70 | 23  | 23.0.3 |         | *_home.so      | 1.6 MB   |
| lib  | lib.analytics  | 0x76 | 23  | 23.0.3 |         | *_analytics.so | 126.1 KB |
| lib  | lib.utils      | 0x73 | 23  | 23.0.3 | 23.4.0  | *_utils.so     | 6.2 KB   |
| lib  | lib.style      | 0x79 | 23  | 23.0.3 | 23.4.0  | *_style.so     | 4.9 KB   |
| web  | web.about      |      | 23  | 23.0.3 | 23.4.0  | *_about.so     | 24.5 KB  |

### Runtime

```
  Device : XiaoMi Redmi 3
     SDK : Android 7.1.1
     ABI : armeabi-v7a
```

**Comment by xufan** [comment]
临时解决方案 MP4文件放到app+stub宿主的分身的raw里面 则7.0以及以上版本都能正常读取raw中的mp4文件

**Comment by panden** [comment]
现在除了临时解决方案之外还有更好的方案吗？

**Comment by yukunxie** [comment]
临时解决方案 MP4文件放到app+stub宿主的分身的raw里面 则7.0以及以上版本都能正常读取raw中的mp4文件

不知“ stub宿主的分身的raw里面”是什么意思，对安卓开发不熟悉

**Comment by galenlin** [comment]
@yukunxie `app+*` 是 Small 特有的宿主分身模块规范，可以参考官网文档的说明 http://code.wequick.net/Small/cn/stub-module
