### ISSUE TITLE
release包启动闪退： Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Package.getName()' on a null object reference 

### ISSUE THREAD

**Issue by struggle111** [wequick/Small#430]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

旧项目集成small，是加了混淆的（release包），但是small的混淆我也加了

## 你期望的结果是什么？

release包可以正常运行

## 实际结果是什么？

debug包能够正常运行，但是release包启动闪退

Small发送运行报错，报错信息如下：
  : FATAL EXCEPTION: main
03-02 15:08:50.998 E/AndroidRuntime(17387): Process: com.nice.main, PID: 17387
03-02 15:08:50.998 E/AndroidRuntime(17387): java.lang.ExceptionInInitializerError
03-02 15:08:50.998 E/AndroidRuntime(17387): 	at net.wequick.small.Small.preSetUp(SourceFile:157)
03-02 15:08:50.998 E/AndroidRuntime(17387): 	at com.nice.main.NiceApplication.onCreate(SourceFile:145)
03-02 15:08:50.998 E/AndroidRuntime(17387): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
03-02 15:08:50.998 E/AndroidRuntime(17387): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5023)
03-02 15:08:50.998 E/AndroidRuntime(17387): 	at android.app.ActivityThread.access$1500(ActivityThread.java:174)
03-02 15:08:50.998 E/AndroidRuntime(17387): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
03-02 15:08:50.998 E/AndroidRuntime(17387): 	at android.os.Handler.dispatchMessage(Handler.java:111)
03-02 15:08:50.998 E/AndroidRuntime(17387): 	at android.os.Looper.loop(Looper.java:194)
03-02 15:08:50.998 E/AndroidRuntime(17387): 	at android.app.ActivityThread.main(ActivityThread.java:5815)
03-02 15:08:50.998 E/AndroidRuntime(17387): 	at java.lang.reflect.Method.invoke(Native Method)
03-02 15:08:50.998 E/AndroidRuntime(17387): 	at java.lang.reflect.Method.invoke(Method.java:372)
03-02 15:08:50.998 E/AndroidRuntime(17387): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009)
03-02 15:08:50.998 E/AndroidRuntime(17387): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
03-02 15:08:50.998 E/AndroidRuntime(17387): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Package.getName()' on a null object reference
03-02 15:08:50.998 E/AndroidRuntime(17387): 	at kbv.<clinit>(SourceFile:82)

### Compile-time

```
  gradle-small plugin : 1.1.0-alpha2 (project)
            small aar : 1.1.0-alpha2(project)
          gradle core : 2.10
       android plugin : 2.1.2
                   OS : Mac OS X 10.12 (x86_64)
```
### Runtime

```
  Device : 魅蓝 note
     SDK : Android 5.1
     ABI : armeabi-v7a, armeabi
```

**Comment by struggle111** [comment]
@galenlin 麻烦大神给个思路，感觉还是混淆的问题，我把
-dontwarn android.support.**

-keep class android.support.** { *; }
-keep interface android.support.** { *; }

# Small
-keep class net.wequick.small.Small { public *; }
-keep interface net.wequick.small.** { *; }
已经加上了，可是还是会报错

**Comment by galenlin** [comment]
调试下看看

**Comment by struggle111** [comment]
问题解决了。
我把-keep class net.wequick.small.Small { public ; } 改成 -keep class net.wequick.small.** { *; }就好了

**Comment by wilsonssss** [comment]
# Small
-keep interface net.wequick.small.** { *; }
-keep class net.wequick.small.** { *; }

config like this should be ok
