### ISSUE TITLE
所有的第三方jar，so放在了lib里，依赖到宿主模块出现错误

### ISSUE THREAD

**Issue by Zangmingchao** [wequick/Small#433]
我把所有的第三方jar，so文件放到一个lib里，依赖的各个模块作为共用代码，并在宿主模块的aoolication中对多个需要初始化的第三方进行初始化，然后出现了错误

:lib.style:unspecified on project app resolves to an APK archive which is not supported as a compilation dependency. File: C:\Users\DELL\Downloads\MySmall-master\Android\Renwuhulian\app\smallLibs\com.renwu
.lib.style.apk
:app:prepareReleaseDependencies FAILED

**Comment by galenlin** [comment]
宿主不能依赖插件，请先阅读首页贡献指南。

**Comment by Zangmingchao** [comment]
dddd
