### ISSUE TITLE
参数传递出现java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.URL.toString()' on a null object reference

### ISSUE THREAD

**Issue by lishoulin** [wequick/Small#434]
### 我做了什么？
在插件A的activity传递参数到插件b的activity，参数values为http链接(例：b?key=http://192.168.0.1/index.html这种)，出现java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.URL.toString()' on a null object reference

### 你期望的结果是什么？
能够正常运行跳转并且传递类似的参数

### 实际结果是什么？
运行跳转崩溃，并抛出java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.URL.toString()' on a null object reference

#### Compile-time
gradle-small plugin : 1.1.0-alpha2(project)
small aar : 1.1.0-alpha2 (project)
gradle core : 2.14.1
android plugin : 2.2.3
OS : windows 7 64位
#### Runtime
Device : m1 metal
SDK : Android 5.1
ABI : armeabi

**Comment by galenlin** [comment]
把 `key=http://192.168.0.1/index.html` 这部分 URLEncode 试试。
不转码的话可能会影响 Uri 参数的解析。

**Comment by lishoulin** [comment]
thinks
