### ISSUE TITLE
Nonsupport ConstraintLayout.

### ISSUE THREAD

**Issue by RonnyWu** [wequick/Small#444]
## did
used ConstraintLayout
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.ronnywu.small.demo.app.main.MainActivity">

    <TextView...>

</android.support.constraint.ConstraintLayout>
```
## want
Normal running
## encounter
```
java.lang.RuntimeException: Unable to start activity
ComponentInfo{com.ronnywu.small.demo/com.ronnywu.small.demo.app.main.MainActivity}:
android.view.InflateException: Binary XML file line #2: Binary XML file line #2: 
Error inflating class android.support.constraint.ConstraintLayout.

Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class android.support.constraint.ConstraintLayout

Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.constraint.ConstraintLayout

Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/constraint/R$styleable;

Caused by: java.lang.ClassNotFoundException: Didn't find class
"android.support.constraint.R$styleable" on path: DexPathList

[
    [
        zipfile"xxx/lib/arm/libcom_ronnywu_small_demo_app_main.so",
        dir"xxx/lib/arm/libcom_ronnywu_small_demo_app_main.so",
        zipfile"xxx/base.apk",
        zipfile"xxx/split_lib_dependencies_apk.apk",
        zipfile"xxx/split_lib_slice_0_apk.apk",
        zipfile"xxx/split_lib_slice_1_apk.apk",
        zipfile"xxx/split_lib_slice_2_apk.apk",
        zipfile"xxx/split_lib_slice_3_apk.apk",
        zipfile"xxx/split_lib_slice_4_apk.apk",
        zipfile"xxx/split_lib_slice_5_apk.apk",
        zipfile"xxx/split_lib_slice_6_apk.apk",
        zipfile"xxx/split_lib_slice_7_apk.apk",
        zipfile"xxx/split_lib_slice_8_apk.apk",
        zipfile"xxx/split_lib_slice_9_apk.apk"
    ],
    nativeLibraryDirectories=[
        xxx/lib/arm,
        xxx/base.apk!/lib/armeabi,
        xxx/split_lib_dependencies_apk.apk!/lib/armeabi,
        xxx/split_lib_slice_0_apk.apk!/lib/armeabi,
        xxx/split_lib_slice_1_apk.apk!/lib/armeabi,
        xxx/split_lib_slice_2_apk.apk!/lib/armeabi,
        xxx/split_lib_slice_3_apk.apk!/lib/armeabi,
        xxx/split_lib_slice_4_apk.apk!/lib/armeabi,
        xxx/split_lib_slice_5_apk.apk!/lib/armeabi,
        xxx/split_lib_slice_6_apk.apk!/lib/armeabi,
        xxx/split_lib_slice_7_apk.apk!/lib/armeabi,
        xxx/split_lib_slice_8_apk.apk!/lib/armeabi,
        xxx/split_lib_slice_9_apk.apk!/lib/armeabi,
        /system/lib,
        /vendor/lib
    ]
]
```
### Compile-time

```
  gradle-small plugin : 1.2.0-beta1 (maven)
            small aar : 1.1.0-alpha2 (maven)
          gradle core : 3.3
       android plugin : 2.3.0
                   OS : Mac OS X 10.12.3 (x86_64)
```
### Bundles

| type |   name   |  PP  | sdk |  aapt  | support | file(armeabi) |   size   |
|------|----------|------|-----|--------|---------|---------------|----------|
| host | app      |      | 25  | 25.0.2 | 25.+    |               |          |
| app  | app.main | 0x77 | 25  | 25.0.2 | 25.+    | *_main.so     | 117.2 KB |

### Runtime
```
 Device : OnePlus A3000
    SDK : 25 (Android 7.1.1)
    ABI : armeabi-v7a
   ABI2 : armeabi
```

**Comment by MartinDong** [comment]
遇到了同样的问题，com.android.support.constraint:constraint-layout:1.0.2这种新的布局方式Small好像不兼容，只要使用就会编译失败

**Comment by StiflerJj** [comment]
同样问题+1

**Comment by galenlin** [comment]
我新建了一个工程 试过没问题的呀。

**Comment by RonnyWu** [comment]
那我再试试看!

**Comment by linhongbao** [comment]
我也遇到了这个同样的问题。
gradlew buildBundle -q
Small building bundle 1 of 1 - app.main (0x77)
Unexpected failure during lint analysis of MainActivity.java (this is a bug in lint or one of the libraries it depends on)
                                                                                                                           AbortCompilation:ProblemHandler.handle(ProblemHandler.java:159)<-ProblemHandler.handle(ProblemHandler.java:226)<-ProblemReporter.handle(ProblemReporter.java:2393)<-ProblemReporter.is

在执行的时候：
  java.lang.RuntimeException: Unable to start activity ComponentInfo{cordova.hongyun.com.tone/cordova.hongyun.com.tone.appmain.MainActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.constraint.ConstraintLayout

**Comment by HolenZhou** [comment]
遇到同样的问题，布局文件中使用ConstraintLayout就启动崩溃，错误log跟上面的一样，不使用就正常。

**Comment by woodstream** [comment]
我执行命令./gradlew buildBundle -q -Dbundle.arch=x86，下面两行会标红，然后运行就遇到楼主同样的情况
 Using vendor aar 'com.android.support.constraint:constraint-layout:1.0.2'
 Using vendor aar 'com.android.support:design:25.3.1'

**Comment by galenlin** [comment]
@woodstream 试着在宿主添加下这两个的依赖

**Comment by RonnyWu** [comment]
我在宿主上添加试试看!

**Comment by woodstream** [comment]
@galenlin 这两个依赖在宿主上添加，不用在插件中移除吧，添加完再跑还是出错，提示：Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

**Comment by galenlin** [comment]
宿主上添加后，要重新 buildLib 一下。

**Comment by woodstream** [comment]
@RonnyWu 你成功了吗？我还是不行@galenlin，有空你可以试试

**Comment by woodstream** [comment]
可以了，应该是我的问题，把主题换掉就可以了

**Comment by RonnyWu** [comment]
Using 'ConstraintLayout' ,  you need add compile in the host plugin 'app':

> looks so:
> ````
> compile 'com.android.support.constraint:constraint-layout:1.0.2'
> ````
