### ISSUE TITLE
Theme.AppCompat在armeabi-v7a目录内找不到

### ISSUE THREAD

**Issue by linjson** [wequick/Small#446]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

我在插件模块中使用了`compile 'com.facebook.react:react-native:0.38.0'`. 
AppCompatActivity作为基类启动,在app.gradle文件中添加
```
    
    ndk{
            abiFilters "armeabi-v7a","x86"
        }
```
如果不加上类这段那我的reactnative就无法运行,但是加了这段small插件就无法运行,最后我在app/smallLibs目录下又加了一个armeabi-v7a目录,文件从armeabi文件夹内复制过来,项目可以正常运行,但是Theme.AppCompat找不到
## 你期望的结果是什么？

Small能够正确识别armeabi-v7a内的样式资源如Theme.AppCompat theme 

## 实际结果是什么？

可以编译,但是运行时报错,信息如下:
```
 java.lang.IllegalStateException: You need to use a Theme.AppCompat theme 
```
### Compile-time

```
  gradle-small plugin : 1.2.0-beta2 (project)
            small aar : 1.2.0-beta2 (project)
          gradle core : 2.14.1
       android plugin : 2.3
                   OS : Mac OS X 10.12 (x86_64)
```

### Bundles

|  type  |       name       |   PP   |          file           |    size    |
|--------|------------------|--------|-------------------------|------------|
|  host  |  app             |        |                         |            |
|  app   |  app.main        |    |  *_main.so (x86)        |  1M   |
|  lib   |  lib.util        |    |  *_util.so (x86)  |  1.1M   |

（注：编译时错误只需本行以上内容，运行时错误补充本行以下内容）
### Runtime

```
  Device : 小米4
     SDK : Android 6.0.1
     ABI : armeabi-v7a/x86
```

**Comment by galenlin** [comment]
bundle.json配置 lib.util 了吗

**Comment by linjson** [comment]
配置了

**Comment by galenlin** [comment]
`./gradlew small` 看下 support 包版本是否一致
`./gradlew smallLint` 看下是否有 R 类是不是重复了

可以使用 `abiFilters "armeabi", "x86"`，rn应该支持 armeabi 的。clean重编下试试。

**Comment by linjson** [comment]
图片上传太慢 了,
support包版本一致
smallLint:提示[!] Passed.
rn不支持armeabi,已单独测试运行过

**Comment by linjson** [comment]
so插件为什么只生成armeabi,能配置生成多种吗?如armeabi-v7a,arm等等

**Comment by linjson** [comment]
已经搞定了,
在local.properties文件里加上bundle.arch=armeabi-v7a这个参数,运行正常
