### ISSUE TITLE
测试多渠道打包出现错误

### ISSUE THREAD

**Issue by dxiaogang** [wequick/Small#45]
操作如下:在原有Sample 工程的gradle配置添加多渠道相关配置:
添加占位:
  <meta-data
            android:name="UMENG_CHANNEL"
            android:value="${UMENG_CHANNEL_VALUE}"/>

manifestPlaceholders = [UMENG_CHANNEL_VALUE: "umeng"]

添加渠道配置:
// 渠道配置
    productFlavors {
        baidu {}
        qihu360 {}
    }

    productFlavors.all {
        flavor -> flavor.manifestPlaceholders = [UMENG_CHANNEL_VALUE: name]
    }

添加APK输出: 
applicationVariants.all { variant ->
                variant.outputs.each { output ->
                    def outputFile = output.outputFile
                    if (outputFile != null && outputFile.name.endsWith('.apk')) {
                        def fileName = "TestSample${defaultConfig.versionName}_${variant.productFlavors[0].name}.apk"
                        output.outputFile = new File(outputFile.parent, fileName)
                    }
                }
            }

执行 ./gradlew buildLib -q

出现错误:
* What went wrong:
Could not determine the dependencies of task ':app:buildLib'.
> Task with path 'jarReleaseClasses' not found in project ':app'.

**Comment by galenlin** [comment]
已解决，请更新。gradle-small升至0.3.0
