### ISSUE TITLE
supportVersion属性的bug

### ISSUE THREAD

**Issue by aliyao** [wequick/Small#456]
由于项目的原因旧的项目准备作为宿主，以后慢慢一步步的拆分下层为插件，而且旧的项目方法数超了，所以用到com.android.support:multidex，在我给项目配置supportVersion属性的时候显示错误Error:Failed to resolve: com.android.support:multidex:25.+，com.android.support:multidex本来就没有25那么大的，希望修改这个属性兼容
 android {
        compileSdkVersion = 25
        buildToolsVersion = "25.0.2"
        supportVersion = "25.+" //导致错误的地方
    }
报错信息
Error:Failed to resolve: com.android.support:multidex:25.+

**Comment by baby2431** [comment]
+1
