### ISSUE TITLE
你好，我在跟着官方例子做的时候无法提取公共库插件

### ISSUE THREAD

**Issue by Xiao-ShaBi** [wequick/Small#460]
Error:
Dependency TestSmall:lib.style:unspecified on project app resolves to an APK archive which is not supported as a compilation dependency. 
File: F:\workspace\TestSmall\lib.style\build\outputs\apk\lib.style-release-unsigned.apk

**Comment by Xiao-ShaBi** [comment]
:app.main:prepareReleaseDependencies
Dependency MySmall:lib.style:unspecified on project app.main resolves to an APK archive which is not supported as a compilation dependency. File: F:\workspace\MySmall\lib.style\build\outputs\apk\lib.style-release-unsigned.apk
Dependency MySmall:lib.style:unspecified on project app.main resolves to an APK archive which is not supported as a compilation dependency. File: F:\workspace\MySmall\lib.style\build\outputs\apk\lib.style-release-unsigned.apk
:app.main:prepareReleaseDependencies FAILED

FAILURE: Build failed with an exception.

**Comment by Xiao-ShaBi** [comment]
在执行gradlew buildBundle时报的错误

**Comment by galenlin** [comment]
宿主不能依赖插件，请仔细看下教程。

**Comment by Xiao-ShaBi** [comment]
@galenlin 谢谢回答，但是我是使用appmain去依赖的插件，这个是官网教程上做的第一个插件。并没有用宿主去依赖插件

**Comment by Xiao-ShaBi** [comment]
我把依赖的library做成application了。。。
