### ISSUE TITLE
Missing library resource entry: "anim/popup_enter", try to cleanLib and buildLib.

### ISSUE THREAD

**Issue by Larvas** [wequick/Small#47]
不支持Lib使用第三方项目带有anim文件，使用第三方的项目是https://github.com/afollestad/material-dialogs
报错如下：
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib.test:processReleaseResources'.
> Missing library resource entry: "anim/popup_enter", try to cleanLib and buildLib.

**Comment by Larvas** [comment]
![qq 20160227103641](https://cloud.githubusercontent.com/assets/6273888/13370285/00e5f30a-dd3e-11e5-91f9-12a1f41e0279.png)

**Comment by galenlin** [comment]
same to #49, closed.
