### ISSUE TITLE
有个问题，单个组件内部activity相互调用启动

### ISSUE THREAD

**Issue by ab503044120** [wequick/Small#470]
如果是组件内部activity调用启动需要传递一些对象数据而且需要返回一些对象，实现起来岂不是很麻烦？

**Comment by galenlin** [comment]
组件内部跟普通开发一样。openUri 只是为了跨组件调用而做的解耦。

**Comment by ab503044120** [comment]
但是就算这组件内部的两个activity也是没有在menifest中注册的啊,想要相互启动岂不是也得用openUri

**Comment by galenlin** [comment]
不用，这个实现的了，Small会帮你完成内部转换。你试试就知道了

**Comment by ab503044120** [comment]
非常感谢您的解答,我试试
