### ISSUE TITLE
在lib模块添加productFlavors然后buildLib出错。

### ISSUE THREAD

**Issue by shadowera** [wequick/Small#476]
lib模块的build.gradle中添加:
 ```
productFlavors {
        letv {
        }
        xiaomi {
        }
    }
```
然后执行 ./gradlew buildLib -q  出错
错误日志如下

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':lib.vendor'.
> Could not get unknown property 'jarReleaseClasses' for project ':lib.vendor' of type org.gradle.api.Project.

描述：
在build.gradle中去掉productFlavors，可以编译通过。
为什么一定要添加productFlavors 呢？
flavor代码要有不同的实现，依赖库也不同。
为什么一定要放在lib中呢。
因为这个模块也要可以升级。。

**Comment by shadowera** [comment]
主项目配置如下
```
  classpath 'com.android.tools.build:gradle:2.3.0'
        classpath 'net.wequick.tools.build:gradle-small:1.2.0-beta5'
```

**Comment by shadowera** [comment]
@galenlin

**Comment by bhui** [comment]
遇到同样的问题，没找到方案
但是作者讲可以用flavor[https://github.com/wequick/Small/issues/243](243)

**Comment by shadowera** [comment]
@bhui @galenlin   
主项目中可以用build flavor ,已验证。后来验证在非small项目中，library中添加flavor也会出现同样问题。所以这不是small 的问题，故关闭。
