### ISSUE TITLE
Missing library resource entry: "attr/md_background_color", try to cleanLib and buildLib.

### ISSUE THREAD

**Issue by Larvas** [wequick/Small#48]
不支持Lib使用第三方项目带有attr属性的文件，使用第三方的项目是https://github.com/afollestad/material-dialogs

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib.test:processReleaseResources'.
> Missing library resource entry: "attr/md_background_color", try to cleanLib and buildLib.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by Larvas** [comment]
![qq 20160227103720](https://cloud.githubusercontent.com/assets/6273888/13370289/1ccd471c-dd3e-11e5-8bea-361779985a97.png)

**Comment by galenlin** [comment]
see #49
