### ISSUE TITLE
有插件模块被分配资源id分段为0x10

### ISSUE THREAD

**Issue by WayJ** [wequick/Small#481]
Small 教程里已经注明
      “Small 根据哈希算法将插件的模块名散列到 [0x11, 0x7e] 区间，作为自动分配的插件资源ID段”

但是使用时候依然有模块分到了0x10
small版本：1.2.0-beta5

查看了AppPlugin的genRandomPackageId方法
private static int genRandomPackageId(String bundleName) {
        int minPP = 0x10
        int maxPP = 0x7e
        int maxHash = 0xffff
        int d = maxPP - minPP
        int hash = bundleName.hashCode() & maxHash
        int pp = (hash * d / maxHash) + minPP
        return pp
    }
最小值还是0x10

**Comment by galenlin** [comment]
是的，因为这个算法之前没考虑到 `0x10`，我看看增加个黑名单把它做一次镜像映射。
