### ISSUE TITLE
Missing library resource entry: "drawable/md_btn_selected", try to cleanLib and buildLib.

### ISSUE THREAD

**Issue by Larvas** [wequick/Small#49]
![qq 20160227104621](https://cloud.githubusercontent.com/assets/6273888/13370340/598dfa38-dd3f-11e5-95ef-6cec66080b30.png)

**Comment by galenlin** [comment]
第三方库需要同时在宿主中添加依赖。插件会分离所有第三方依赖以保证最小化。

**Comment by galenlin** [comment]
跟设计原则有出入，暂不支持。
