### ISSUE TITLE
【混淆问题】宿主后插件都混淆后出现混淆后的类冲突

### ISSUE THREAD

**Issue by zhenghuanpeng1992** [wequick/Small#496]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

插件和宿主都开启混淆

## 你期望的结果是什么？

程序正常运行

## 实际结果是什么？

```
Rejecting re-init on previously-failed class java.lang.Class<ch>: java.lang.IncompatibleClassChangeError: Class ch implements non-interface class ao (declaration of 'ch' appears in /data/xxxx
```
因为插件和宿主打包是在不同时机且各自混淆，两边混淆后的类是随机的所以可能造成冲突，加载类时就会有问题。

### Compile-time

```
  gradle-small plugin : 1.2.0-alpha6 (maven)
            small aar : 1.2.0-alpha6 (maven)
          gradle core : 3.3
       android plugin : 2.3.0
                   OS : Mac OS X 10.12.5 (x86_64)
```

### Bundles

| type |          name          |  PP  | sdk |  aapt  | support |     file     |   size   |
|------|------------------------|------|-----|--------|---------|--------------|----------|
| host | app             |      | 25  | 25.0.3 |         |              |          |
| stub | app+stub                   |      | 25  | 25.0.3 |         |              |          |
| app  | app.xxx | 0x30 | 25  | 25.0.3 |         | *.xxx.apk | 205.4 KB |
| app  | app.xx               | 0x40 | 25  | 25.0.3 |         | *.xxx.apk   | 228.3 KB |
| lib  | lib.common             | 0x20 | 25  | 25.0.3 |         | *.common.apk | 104.8 KB |

### Runtime

```
  Device : Samsung Nexus S
     SDK : Android 7.0
     ABI : armeabi-v7a
```

**Comment by galenlin** [comment]
你好，请按照模板提issue，保留除注释区间外的所有内容。

**Comment by zhenghuanpeng1992** [comment]
Update
