### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xiaoxiaohaozai** [wequick/Small#497]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？
在tasks 
执行buildLib
执行buildBundle
执行assembleDebug 编译成功 能成功运行

在tasks 
执行buildLib
执行buildBundle
执行assembleRelease 编译失败 

 使用自己的签名打包出现异常

## 你期望的结果是什么？

release包成功

## 实际结果是什么？

Error:(6, 25) 错误: 程序包net.wequick.small不存在
Error:(15, 36) 错误: 程序包Small不存在
Error:(15, 9) 错误: 找不到符号
符号:   变量 Small
位置: 类 HomeActivity
Error:Execution failed for task ':app.main:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

### Compile-time

```
 radle-small plugin : 1.3.0-beta1 (maven)
            small aar : 1.3.0-beta1 (maven)
          gradle core : 3.3
       android plugin : 2.3.0
                   OS : Mac OS X 10.12.5 (x86_64)
```

### Bundles

| type |   name    |  PP  | sdk |  aapt  | support | file(armeabi) |  size  |
|------|-----------|------|-----|--------|---------|---------------|--------|
| host | app       |      | 25  | 25.0.2 | 25.3.1  |               |        |
| app  | app.radio | 0x53 | 25  | 25.0.2 | 25.3.1  | *_radio.so    | 6.6 KB |
| app  | app.main  | 0x77 | 25  | 25.0.2 | 25.3.1  | *_main.so     | 6.6 KB |

```

**Comment by galenlin** [comment]
在 `buildBundle` 之前，需要先执行  `buildLib` 。

> 你的issue内容格式有误(未完全显示)。请对需要显示的内容去除 `<!-- -->` 区间注释。

**Comment by xiaoxiaohaozai** [comment]
已更新bug

**Comment by xiaoxiaohaozai** [comment]
@galenlin  已更新bug  debug打包是没问题的  release 打包失败

**Comment by galenlin** [comment]
`buildLib` 跑了没有？

**Comment by xiaoxiaohaozai** [comment]
@galenlin  每次签名都得buildlib吗

**Comment by xiaoxiaohaozai** [comment]
@galenlin 报错  Error:(6, 25) 错误: 程序包net.wequick.small不存在
Error:(15, 36) 错误: 程序包Small不存在
Error:(15, 9) 错误: 找不到符号
符号:   变量 Small
位置: 类 HomeActivity
Error:Execution failed for task ':app.main:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by galenlin** [comment]
。。跟签名有什么关系？你是怎么编译的，在 `你做了什么` 里体现出来啊。

总之 `buildBundle` 之前要跑过一次 `buildLib` 就对了。

**Comment by xiaoxiaohaozai** [comment]
@galenlin 已修改

**Comment by galenlin** [comment]
编译宿主，跑 `:app:assembleRelease`，直接跑 `assembleRelease` 会触发所有模块的编译。

**Comment by xiaoxiaohaozai** [comment]
@galenlin buildLib buildBundle 也是编译宿主的吗

**Comment by galenlin** [comment]
我要跪了，文档看了吗，那两个的用途你先了解下吧

**Comment by xiaoxiaohaozai** [comment]
@galenlin  现在是这样了
chenhaodeMacBook-Pro:NewNativeControl chenhao$ ./gradlew buildLib -q
  Small building library 1 of 1 - app (0x7f)
chenhaodeMacBook-Pro:NewNativeControl chenhao$ ./gradlew buildBundle 
都通过了 没问题

chenhaodeMacBook-Pro:NewNativeControl chenhao$ ./gradlew assembleRelease

卡在了 
/Users/chenhao/NewNativeControl/app.main/src/main/java/com/ebanswers/nativecontrol/app/main/HomeActivity.java:15: 错误: 找不到符号
        Small.setUp(this, new Small.OnCompleteListener() {
        ^
  符号:   变量 Small
  位置: 类 HomeActivity
3 个错误
:app.main:compileReleaseJavaWithJavac FAILED

**Comment by galenlin** [comment]
我就问你 `./gradlew assembleRelease` 敢不敢改成 `./gradlew :app:assembleRelease`

**Comment by xiaoxiaohaozai** [comment]
@galenlin  大神我的锅  小弟我新手对着gradle 不是很理解。。。  解决了
