### ISSUE TITLE
寄主分身ButterKnife8集成问题

### ISSUE THREAD

**Issue by whosmyqueen** [wequick/Small#498]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

我在app+stub里面添加ButterKnife8依赖,编译通过
## 你期望的结果是什么？

运行成功,并且控件对象能正常使用

## 实际结果是什么？

依赖放到寄主分身里面,运行的时候,控件对象报空指针;依赖添加到业务插件里面,能正常使用

### Compile-time

```
  gradle-small plugin : 1.3.0-beta1 (maven)
            small aar : 1.3.0-beta1 (maven)
          gradle core : 3.3
       android plugin : 2.3.3
                   OS : Mac OS X 10.12.5 (x86_64)
```

### Bundles

| type |   name    |  PP  | sdk |  aapt  | support | file(armeabi) |   size   |
|------|-----------|------|-----|--------|---------|---------------|----------|
| host | app       |      | 25  | 25.0.3 | 25.3.1  |               |          |
| stub | app+stub  |      | 25  | 25.0.3 | 25.3.1  |               |          |
| app  | app.main  | 0x77 | 25  | 25.0.3 | 25.3.1  | *_main.so     | 5 KB     |
| lib  | lib.util  | 0x33 | 25  | 25.0.3 | 25.3.1  | *_util.so     | 730.4 KB |
| lib  | lib.style | 0x79 | 25  | 25.0.3 | 25.3.1  | *_style.so    | 4.1 KB   |

项目地址:
`https://github.com/whosmyqueen/ZHYQ`

### Runtime

```
  Device : Samsung Nexus S
     SDK : Android 7.0
     ABI : armeabi
```

**Comment by galenlin** [comment]
经验证，`annotationProcessor xx` 依赖必须在模块 build.gradle 直接指明，不能传递依赖。否则无法在 `apt` 目录下生成 `xx_ViewBinding.java`，即造成运行时绑定失败。

这个问题是 `Android Gradle Plugin` 内部原因，也就是说在非 Small 工程里同样存在这个问题。

你只需要在插件模块 build.gradle 里加上 `annotationProcessor $butterknife` 即可。

**Comment by whosmyqueen** [comment]
了解
