### ISSUE TITLE
openUri 启动失败

### ISSUE THREAD

**Issue by xiaoxiaohaozai** [wequick/Small#503]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

Small.openUri("Main", MainActivity.this);

## 你期望的结果是什么？

跳到主界面

## 实际结果是什么？

一直在启动界面，没有跳转

### Compile-time

```
   gradle-small plugin : 1.3.0-beta1 (maven)
            small aar : 1.3.0-beta1 (maven)
          gradle core : 3.3
       android plugin : 2.3.3
                   OS : Mac OS X 10.12.5 (x86_64)
```

### Bundles

| type |      name       |  PP  | sdk |  aapt  | support |  file(armeabi)   |    size    |
|------|-----------------|------|-----|--------|---------|------------------|------------|
| host | app             |      | 25  | 25.0.2 | 25.3.1  |                  |            |
| stub | app+stub        |      | 25  | 25.0.2 | 25.3.1  |                  |            |
| app  | app.photo       | 0x66 | 25  | 25.0.2 |         | *_photo.so       | 5.7 MB     |
| app  | app.radio       | 0x53 | 25  | 25.0.2 | 25.3.1  | *_radio.so       | 65.2 KB    |
| app  | app.main        | 0x77 | 25  | 25.0.2 | 25.3.1  | *_main.so        | 113.7 KB   |
| app  | app.video       | 0x54 | 25  | 25.0.2 | 25.3.1  | *_video.so       | 10.5 KB    |
| app  | app.soundsearch | 0x76 | 25  | 25.0.2 | 25.3.1  | *_soundsearch.so | 12.6 KB    |
| app  | app.control     | 0x2a | 25  | 25.0.2 | 25.3.1  | *_control.so     | 309 KB     |
| app  | app.food        | 0x7a | 25  | 25.0.2 | 25.3.1  | *_food.so        | 10.4 KB    |
| app  | app.music       | 0x43 | 25  | 25.0.2 | 25.3.1  | *_music.so       | 10.3 KB    |
| app  | app.setup       | 0x64 | 25  | 25.0.2 | 25.3.1  | *_setup.so       | 105 KB     |
| lib  | lib.viewbuffer  | 0x57 | 25  | 25.0.3 |         | *_viewbuffer.so  | 9 MB       |
| lib  | lib.androidview | 0x37 | 25  | 25.0.3 |         | *_androidview.so | 1,022.7 KB |
| lib  | lib.voice       | 0x5f | 25  | 25.0.2 | 25.3.1  | *_voice.so       | 5.5 MB     |
| lib  | lib.utils       | 0x73 | 25  | 25.0.2 | 25.3.1  | *_utils.so       | 1.1 MB     |
| lib  | lib.style       | 0x79 | 25  | 25.0.2 | 25.3.1  | *_style.so       | 1.1 MB     |

**Comment by galenlin** [comment]
详细一点吧，log得有吧，大哥。

**Comment by xiaoxiaohaozai** [comment]
![image](https://user-images.githubusercontent.com/14050369/27617536-8aab1888-5be9-11e7-9fe8-6672364142f4.png)
返回是null

**Comment by xiaoxiaohaozai** [comment]
error 里面一只报这些

06-28 10:13:23.541 1570-1861/? E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=2775, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
06-28 10:13:23.589 1963-1963/? E/ROW: topAppWindowChanged11111111111111111 classname=net.wequick.small.A
06-28 10:13:23.594 1963-1963/? E/ROW: topAppWindowChanged11111111111111111 classname=net.wequick.small.A
06-28 10:13:23.594 1963-1963/? E/ROW: topAppWindowChanged11111111111111111 classname=net.wequick.small.A

@galenlin

**Comment by xiaoxiaohaozai** [comment]
@galenlin 
![image](https://user-images.githubusercontent.com/14050369/27617870-9ee4da26-5beb-11e7-8d6b-22c35be5ce59.png)
主界面的application 不停启动

**Comment by galenlin** [comment]
这个信息给到我 看不出任何问题的。

**Comment by xiaoxiaohaozai** [comment]
@galenlin  关键是 它没报错  也没崩 就是一片黑

**Comment by galenlin** [comment]
贡献指南看了吗，我就一个很简单的要求：复现问题。你让我都没法复现，我怎么查？怎么解决。你的测试给你提这种bug你接收吗？

以前没模板，issue提的毫无章法，现在有模板，也就随便填些没用的信息。。
哎。。同是开发，我就问你受得了受不了？

**Comment by xiaoxiaohaozai** [comment]
@galenlin 
![image](https://user-images.githubusercontent.com/14050369/27618240-a3fe9a2c-5bed-11e7-816c-ac54e27004f0.png)
![image](https://user-images.githubusercontent.com/14050369/27618241-a8a1a240-5bed-11e7-9bf3-bf8dc5ca9ac9.png)
