### ISSUE TITLE
在最新版Gradle编译不通过。

### ISSUE THREAD

**Issue by Jian-ming** [wequick/Small#513]
# 错误报告

## 你做了什么？
     使用最新版Android studio 3.0 Canary 5 ，gradle-4.1-milestone-1 编译Sample（替换了gradle版本）编译通不过。

## 你期望的结果是什么？
      在gradle-4.1-milestone-1 中正常编译通过。

## 实际结果是什么？
       使用最新版Android studio 3.0 Canary 5 ，gradle-4.1-milestone-1 编译Sample（替换了gradle版本）编译通不过，但替换会Sample的gradle 3.3可正常编译。

编译不通过时错误为：
Gradle 'Sample' project refresh failed
Error:No such property: name for class: org.gradle.api.internal.file.CompositeFileTree$3

**Comment by wilsonssss** [comment]
the same issue,  
```
Caused by: groovy.lang.MissingPropertyException: No such property: name for class: org.gradle.api.internal.file.CompositeFileTree$3
17:26:52.639 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at net.wequick.gradle.AppPlugin$_getLibraryJars_closure5$_closure71.doCall(AppPlugin.groovy:181)
17:26:52.639 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at net.wequick.gradle.AppPlugin$_getLibraryJars_closure5.doCall(AppPlugin.groovy:181)
17:26:52.639 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at net.wequick.gradle.AppPlugin.getLibraryJars(AppPlugin.groovy:178)
17:26:52.639 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at net.wequick.gradle.LibraryPlugin.afterEvaluate(LibraryPlugin.groovy:68)
17:26:52.639 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at net.wequick.gradle.AndroidPlugin$_configureProject_closure2.doCall(AndroidPlugin.groovy:50)
17:26:52.639 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
```

**Comment by changfeifan** [comment]
同样编译不通过 
### Compile-time

```
  gradle-small plugin : 1.3.0-beta3 (maven)
            small aar : 1.3.0-beta3 (maven)
          gradle core : 4.1
       android plugin : 3.0.0
                   OS : Mac OS X 10.12.6 (x86_64)
```

### Bundles

| type |   name   | PP | sdk |  aapt  | support | file | size |
|------|----------|----|-----|--------|---------|------|------|
| host | app      |    | 27  | 27.0.0 |         |      |      |
| App  | App.test |    | 27  | 27.0.0 |         |      |      |

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > com/android/build/gradle/internal/tasks/PrepareLibraryTask

**Comment by Ivonhoe** [comment]
@Jian-ming  https://github.com/wequick/Small/issues/545

**Comment by galenlin** [comment]
Android Gradle Plugin 3.0 已初步适配，见 #557
