### ISSUE TITLE
Unexpected failure during lint analysis of HomeActivity.java (this is a bug in lint or one of the libraries it depends on)无法解决

### ISSUE THREAD

**Issue by liyuhaolol** [wequick/Small#515]
# 错误报告

## 你做了什么？

`执行gradlew buildBundle -q`

## 你期望的结果是什么？

`编译后中正常编译通过。显示OK，输出对应的.so文件`

## Small环境

`Unexpected failure during lint analysis of HomeActivity.java (this is a bug in lint or one of the libraries it depends on)`
 `AbortCompilation:ProblemHandler.handle(ProblemHandler.java:159)`
`<-ProblemHandler.handle(ProblemHandler.java:226)`
`<-ProblemReporter.handle(ProblemReporter.java:2393)`
`<-ProblemReporter.isClassPathCorrect(ProblemReporter.java:4761)`

### Compile-time

```
  gradle-small plugin : 1.0.0-alpha2 (project)
            small aar : 1.1.0-beta5 (project)
          gradle core : 2.10
       android plugin : 2.0.0
                   OS : Mac OS X 10.12 (x86_64)
```

### Bundles

|  type  |       name       |   PP   |          file           |    size    |
|--------|------------------|--------|-------------------------|------------|
|  host  |  app             |        |                         |            |
|  app   |  app.main        |  0x77  |  *_main.so        |  5.2KB   |

### Compile-time

```
  gradle-small plugin : 1.2.0-alpha6 (maven)
            small aar : 1.2.0-alpha6 (maven)
          gradle core : 3.3
       android plugin : 2.3.3
                   OS : Windows 8.1 6.3 (amd64)
```

我是在初学Small，现在做的是最基础的集成学习，我app和app.main引用的依赖全部都是

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha9'
    testCompile 'junit:junit:4.12'
}
```

 先运行gradlew buildLib -q再运行gradlew buildBundle -q，以后始终报这个错误，求作者可以给我解惑，这个问题要怎么修复？

**Comment by GggggitHub** [comment]
同样的bug
gradlew buildBundle -q -Dbundle.arch=armeabi
  Small building bundle 1 of 1 - app.login (0x44)
        Using vendor aar 'com.android.support:appcompat-v7:26.1.0'
        Using vendor aar 'com.android.support:design:26.1.0'
        Using vendor aar 'com.android.support.constraint:constraint-layout:1.0.2'
        [app.login] split library res files...                          [  OK  ]
        [app.login] slice asset package and reset package id...         [  OK  ]
        [app.login] split library R.java files...                       [  OK  ]
        [app.login] split R.class...                                    [  OK  ]
Unexpected failure during lint analysis of LoginActivity.java (this is a bug in lint or one of the libraries it depends on)
                                                                                                                            AbortCompilation:ProblemHandler.handle(ProblemHandler.java:159)<-ProblemHandler.handle(Pr
oblemHandler.java:226)<-ProblemReporter.handle(ProblemReporter.java:2393)<-ProblemReporter.isClassPathCorrect(ProblemReporter.java:4761)
Unexpected failure during lint analysis of LoginHomeActivity.java (this is a bug in lint or one of the libraries it depends on)
AbortCompilation:ProblemHandler.handle(ProblemHandler.java:159)<-ProblemHandler.handle(ProblemHandler.java:226)<-ProblemReporter.handle(ProblemReporter.java:2393)<-ProblemReporter.isClassPathCorrect(ProblemReporte
r.java:4761)
        -> armeabi/libcom_app_login.so (1751968 bytes = 1.7 MB)
