### ISSUE TITLE
Missing library resource entry: "array/de_search_letters", try to cleanLib and buildLib.

### ISSUE THREAD

**Issue by zinclee123** [wequick/Small#52]
宿主module不包含寄生module的资源文件，buildBundle时报如下错误
* What went wrong:
Execution failed for task ':app.main:processReleaseResources'.
> Missing library resource entry: "array/de_search_letters", try to cleanLib and buildLib.

**Comment by galenlin** [comment]
Fix by commit of [Support array resource type](https://github.com/wequick/Small/commit/634c7cec4ecd3c4d8446f3977d227c5eec959959)
