### ISSUE TITLE
startActivity不能正确打开外部安装应用

### ISSUE THREAD

**Issue by qomg** [wequick/Small#522]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告
startActivity不能正确打开外部安装应用

## 你做了什么？
```
Intent intent = new Intent();
intent.setPackage("cn.wps.moffice_eng");
intent.setAction(Intent.ACTION_MAIN);
intent.addCategory(Intent.CATEGORY_LAUNCHER);
startActivity(intent);
```

bundle.json
```json
{
  "version": "1.0.0",
  "bundles": [
    {
      "uri": "pdfplugin",
      "type": "app",
      "pkg": "com.example.pdfplugin",
      "rules": {
        "agency": "PDFPrintAgency"
      }
    }
  ]
}
```

## 你期望的结果是什么？
打开WPS的主页面

## 实际结果是什么？
通过上面startActivity实际打开的是我 com.example.pdfplugin 里面的MainActivity

## Small环境
> classpath 'net.wequick.tools.build:gradle-small:1.2.0-beta3'

### Compile-time

```
  gradle-small plugin : 1.2.0-beta3 (project)
  small aar : 1.2.0-beta3 (project)
  gradle core : 2.3.2
  android build tools version : 25.0.3
  OS : Windows 10(x64)
```

### Bundles

|  type  |       name       |   PP   |          file           |    size    |
|--------|------------------|--------|-------------------------|------------|
|  host  |  app             |        |                         |            |
|  app   |  app.pdfplugin        |  ?  |  libcom_example_pdfplugin.so (x86)        |  4170 KB   |

### Runtime

```
  Device : Meizu Pro5
     SDK : Android 5.1
     ABI : armeabi-v7a (not sure)
```

**Comment by qomg** [comment]
通过debug进到这个方法
> net.wequick.small.ApkBundleLauncher.InstrumentationWrapper#wrapIntent
```
private void wrapIntent(Intent intent) {
            ComponentName component = intent.getComponent();
            String realClazz;
            if (component == null) {
                // Try to resolve the implicit action which has registered in host.
                component = intent.resolveActivity(Small.getContext().getPackageManager());
                if (component != null) {
                    // A system or host action, nothing to be done.
                    return;
                }

                // Try to resolve the implicit action which has registered in bundles.
                realClazz = resolveActivity(intent);
                if (realClazz == null) {
                    // Cannot resolved, nothing to be done.
                    return;
                }
            } else {
                ...
            }
            ...
        }
```
realClazz = resolveActivity(intent); 
这句查询已加载的activities返回插件的ACTION_MAIN\CATEGORY_LAUNCHER
所以提个建议：resolveActivity方法里面多加一些匹配条件会好些

**Comment by tianfuchao** [comment]
能告诉下具体的解决方案么 ComponentName 不知道怎么设置
