### ISSUE TITLE
希望尽快支持as3.0

### ISSUE THREAD

**Issue by yingchen066** [wequick/Small#546]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

### Compile-time

```
  gradle-small plugin : 1.0.0-alpha2 (project)
            small aar : 1.1.0-beta5 (project)
          gradle core : 2.10
       android plugin : 2.0.0
                   OS : Mac OS X 10.12 (x86_64)
```

### Bundles

|  type  |       name       |   PP   |          file           |    size    |
|--------|------------------|--------|-------------------------|------------|
|  host  |  app             |        |                         |            |
|  app   |  app.main        |  0x77  |  *_main.so (x86)        |  10.9 KB   |
|  app   |  app.mine        |  0x16  |  *_mine.so (x86)        |  35.5 KB   |
|  app   |  app.detail      |  0x67  |  *_detail.so (x86)      |  6.6 KB    |
|  app   |  app.home        |  0x70  |  *_home.so (x86)        |  10.4 KB   |
|  lib   |  lib.afterutils  |  0x45  |  *_afterutils.so (x86)  |  21.2 KB   |
|  lib   |  lib.analytics   |  0x76  |  *_analytics.so (x86)   |  125.7 KB  |
|  lib   |  lib.utils       |  0x73  |  *_utils.so (x86)       |  46 KB     |
|  lib   |  lib.style       |  0x79  |  *_style.so (x86)       |  44.9 KB   |
|  web   |  web.about       |        |  *_about.so (x86)       |  24.3 KB   |

### Runtime

```
  Device : Samsung Nexus S
     SDK : Android 7.0
     ABI : armeabi-v7a
```

**Comment by zhouxin1233** [comment]
同问: 编译时报错 Could not get unknown property 'libraries', 请问这个该怎么解决

**Comment by HysDennis** [comment]
同问

**Comment by galenlin** [comment]
@yingchen066 这个issue题文不符。
@zhouxin1233 请确认你的版本是最新的，同时，在我看来你这个问题不是所谓 ”AS 3.0“ 的问题

从你的内容来看：

```
gradle-small plugin : 1.0.0-alpha2 (project)
            small aar : 1.1.0-beta5 (project)
          gradle core : 2.10
       android plugin : 2.0.0
```

这段环境应该是你拷贝来的？这里面的版本已经过时很久了。请根据你真实的环境提问。

最后，说明下：“AS 3.0 不是问题，是其中使用了 Android Gradle Plugin 3.0 才需要适配“

Android Gradle Plugin 3.0 的适配正在处理，但内部 API 变化很高，需要时间。

短期内建议继续使用 Android Gradle Plugin 2.3.0 版本。（跟 AS 3.0 没关系）

关闭本 issue。

**Comment by podinns** [comment]
AS3.0 好像有最低支持的gradle版本吧
