### ISSUE TITLE
安装运行DevSample分支代码,直接退出

### ISSUE THREAD

**Issue by mowenGithub** [wequick/Small#55]
@cheukho @galenlin @sukeygithub   谢谢各位,特别是cheukho,用他的方法解决了,开始确实没有好好阅读编译过程的文档,抱歉!

[
![bug](https://cloud.githubusercontent.com/assets/8080944/13490588/95b403e0-e168-11e5-80d7-571fa820cf6a.jpg)
](url)

上面是安装后第一次启动log,经调试是启动Small.openUri("main", LaunchActivity.this); -->bundle.launchFrom(context);-->mApplicableLauncher==null导致没有启动起来,希望看看什么情况:
测试两个手机:
三星note3 5.0
坚果手机
均这样

**Comment by sukeygithub** [comment]
运行宿主 app，进入后crash（MX5 pro）
03-04 15:57:55.921 30870-30900/net.wequick.example.small E/libGameXtend: LUCID_1 (1457078275929) GameXtend is currently running in Manual mode
03-04 15:57:55.921 30870-30900/net.wequick.example.small E/libGameXtend: LUCID_1 (1457078275929) GameXtend is currently running in no_save Save power state
03-04 15:57:55.921 30870-30900/net.wequick.example.small E/libGameXtend: LUCID_1 (1457078275929) net.wequick.example.small is currently running with GameXtend, with PS parameter = 1
03-04 15:57:57.951 30870-30900/net.wequick.example.small E/libGameXtend: LUCID_1 (1457078277958) GameXtend is currently running in Manual mode
03-04 15:57:57.951 30870-30900/net.wequick.example.small E/libGameXtend: LUCID_1 (1457078277958) GameXtend is currently running in no_save Save power state
03-04 15:57:57.951 30870-30900/net.wequick.example.small E/libGameXtend: LUCID_1 (1457078277958) net.wequick.example.small is currently running with GameXtend, with PS parameter = 1

**Comment by galenlin** [comment]
@mowenGithub, @sukeygithub  方便的话提供一个demo给我，从提供的信息无法确定是什么问题。

**Comment by sukeygithub** [comment]
就在MX5 pro 运行 Small/Android/Sample project中的 app 就报那错误了

**Comment by mowenGithub** [comment]
@galenlin 我也运行的是DevSample分支的代码,没有改一行,也就是Demo就是DevSample/Sample的代码

**Comment by cheukho** [comment]
我刚刚遇到这个问题，正确的运行方式是运行Sample的app项目。运行之前需要对插件进行build，具体方法有两步：1、Sample>gradlew buildLib -q；2、Sample>gradlew buildBundle -q
