### ISSUE TITLE
Error:Execution failed for task ':app.mian:preBuild'. > Could not get unknown property 'libraries' for task ':app.mian:processDebugManifest' of type com.android.build.gradle.tasks.MergeManifests.

### ISSUE THREAD

**Issue by podinns** [wequick/Small#556]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告
Error:Execution failed for task ':app.mian:preBuild'.
> Could not get unknown property 'libraries' for task ':app.mian:processDebugManifest' of type com.android.build.gradle.tasks.MergeManifests.
## 你做了什么？
在根目录按照教程配置了
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'net.wequick.tools.build:gradle-small:1.3.0-beta3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
apply plugin: 'net.wequick.small'
small {
    aarVersion = '1.3.0-beta3'
}
创建Moudle后编译报错

## 你期望的结果是什么？
Small能够正确编译数据

## Small环境
SmallDemo lwhan$ ./gradlew small

> Configure project :app
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.

> Configure project :app.mian
Configuration 'debugCompile' in project ':app.mian' is deprecated. Use 'debugImplementation' instead.

没有使用compile

### Compile-time

```
  gradle-small plugin : 1.3.0-beta3 (maven)
            small aar : 1.3.0-beta3 (maven)
          gradle core : 4.1
       android plugin : 3.0.1
                   OS : Mac OS X 10.13.1 (x86_64)
```

**Comment by podinns** [comment]
### Bundles

| type |   name   |  PP  | sdk |  aapt  | support | file | size |
|------|----------|------|-----|--------|---------|------|------|
| host | app      |      | 26  | 26.0.2 |         |      |      |
| app  | app.mian | 0x16 | 26  | 26.0.2 |         |      |      |

**Comment by galenlin** [comment]
`com.android.tools.build:gradle:3.0` 以上版本正在适配，请先使用 `2.3.0`。
具体问题见 #557
