### ISSUE TITLE
 host 和 plugin 相互调用

### ISSUE THREAD

**Issue by lrhehe** [wequick/Small#56]
1. 通过Small使用URI来互相调用，彼此之间是感知不到对方存在的。
这个适用于app. 开头的module之间相互调用
```java
// app 调起 app.main
Small.openUri("main", LaunchActivity.this);
```

2. 相互依赖，一方直接使用另外一方
适用于app. 对 lib. 的调用，或者 lib. 之间的调用
app.home 依赖了 net.wequick.example.small.lib.utils

    // User libraries
    compile project(':lib.style')
    compile project(':lib.utils')

```java
// app.home 中直接使用
import net.wequick.example.small.lib.utils.UIUtils;
...
UIUtils.showToast(getContext(), "Hello World!");
```
感谢作者，很赞的工作！看了一下介绍和例子，不知道理解的有没有错

有两个问题：
1. app. 是否可以直接依赖另一个 app. 呢？
从例子里看到下面的获取另一个app的fragment的方式，能否直接import，进行new呢
``` Fragment fragment = Small.createObject("fragment-v4", sUris[position], MainActivity.this);```
2. 看到check upgrade 的例子，想问一个lib在下载patch，进行升级的过程中会影响它本身的使用吗？会影响其他lib的使用吗？

**Comment by galenlin** [comment]
没有公开API调用。

Small的设计准则是宿主只做setUp与启动主插件，其他的事交由插件处理。

不过在Small.setUp onComplete之后，所有的插件类都会共存于宿主的classLoader中。实在需要，反射或许行得通。

**Comment by galenlin** [comment]
@lrhehe 可以再加一条评论的。。你直接改第一个评论，我差点没看到你的新问题。。

1. app.\* 只能依赖 lib.\*，不能相互依赖。

  > 如果你发现需要相互依赖，显然需要重构，并提取到lib.\*作为公共部分

2. 完全可以把检查更新写到某个lib.\*。

  > 目前升级过程实际上只是下载一个新的库，在下次启动时替换更新。

**Comment by lrhehe** [comment]
@galenlin 多谢答疑。第2个问题是后来想到的，当时看没有回复就直接加在问题后面了，我下次注意，^_^
