### ISSUE TITLE
现有项目插件化遇到的问题

### ISSUE THREAD

**Issue by lrhehe** [wequick/Small#57]
1. 如果 app.main 依赖了两个android library 库 liba 和 libb，能否只把其中一个做为插件，另外一个直接放在 app.main 中呢？也就是把liba 改成lib.liba，并且定义在 bundle.json 中，但是 libb 还是放在 app.main中。

2. app.main 依赖了一个 android library 库 liba，那么在 app.main 中是否可以直接使用 liba 中的资源文件呢？实际尝试过程中发现在 prepareSplit() 时会抛出异常：
```
if (be.type != 'id') {
    throw new Exception(
        "Missing library resource entry: \"$k\", try to cleanLib and buildLib.")
}
```
不知道是不是这个原因引起的？

**Comment by galenlin** [comment]
1. 如果直接放在app.main中，为何要提取lib.b？
2. 可以直接使用的，是不是你在lib.a中新增了资源，但是没有buildLib？

**Comment by lrhehe** [comment]
@galenlin 在对现有工程进行插件化尝试，buildLib 总是不成功，所以在找原因。
1. ok，明白了，直接放在 app.main 不回引入问题
2. 工程比较大，buildLib 一直失败，遇到过 @string/app_name，@animator/info.xml 出现下面异常的情况
```
    throw new Exception(
        "Missing library resource entry: \"$k\", try to cleanLib and buildLib.")
```
把 app_name 以及使用 app_name 的地方删除就没报这个错了
info.xml 的那个没找到原因。目前在看 AppPlugin 的逻辑，进度比较慢

另外问一下：
1. 能否把 app.main 与 app 合并呢，我的工程只有一个 app ，其他都是lib，所以我目前尝试的是把app.main 和 app 放在一起做为 app 的
2. 如果有两个 lib 插件 lib.a 和 lib.b 。那么 lib.a 可以依赖 lib.b 吗？ 在 buildLib 时有先后顺序吗？

**Comment by galenlin** [comment]
出现**Missing library resource entry**表示该资源：
1. 在插件自身的res中没找到
2. 在公共库lib.\*的res中也没找到
info.xml你是如何定义的？麻烦发下res目录结构。

另外：
1. 如果只是为了分模块开发而不打插件包，不要以\*.\*命名。普通命名（e.g. your_module）的Library模块Android Studio默认支持compile project(':your_module');
2. 如果lib.b中不包含资源，lib.a可以依赖lib.b。有资源的处理情况有点复杂，涉及到你说的顺序问题。

**Comment by lrhehe** [comment]
1.  我确实不用打插件包，不过希望能够动态加载 lib ，类似于 Small Sample 里面动态更新 lib.utils ， 请问有什么好的方法吗
2.  恩，我把带资源的 lib 直接放到另一个lib里面就解决了，info.xml 的问题也没有了

**Comment by galenlin** [comment]
额 这个需求有点诡异。既然要动态更新，为什么不把业务分解成app.\*？目前的设计宿主是无法直接依赖lib.\*的。

**Comment by lrhehe** [comment]
原来宿主无法直接依赖 lib.* ，是因为有个插件加载过程吧，所以不能在加载前依赖，了解

因为我只有一个application，所以想省事，就把 app 和 app.main 合并了

**Comment by blingz** [comment]
例子跑起来了。但没找到文档说明可以这样的：  宿主启动之后，从网络或sd卡加载子模块（插件），然后启动子模块。   这个动作可以实现嘛？ 若可以实现怎么调用？

**Comment by blingz** [comment]
插件测试也跑起来了。文档不清晰调试其他听苦x，码一下简单过程：
1，采用./gradlew buildLib 和 ./gradlew buildBundle 生产插件包，如libcom_example_mysmall_app_main.so （其实就是apk包)
2，宿主本身必须包含插件包(旧版本)，新版本copy到指定的目录下
/data/data/com.example.mysmall/app_small_patch/libcom_example_mysmall_app_main.so
3，Small会检查2个包的versionCode，启用新版本。

**Comment by galenlin** [comment]
@blingz 加载新增模块现有不支持；更新模块是你说的这个流程，不过这些不用手动操作的，在Sample的app.home里有示例代码。
