### ISSUE TITLE
编译插件报错Using vendor aar 'com.android.support:appcompat-v7:23.2.1'         Using vendor aar 'com.android.support:design:23.2.1'

### ISSUE THREAD

**Issue by GggggitHub** [wequick/Small#575]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告
D:\Android\osChinaSpace\MySmall>gradlew buildBundle -q
  Small building bundle 1 of 1 - app.login (0x44)
        Using vendor aar 'com.android.support:appcompat-v7:23.2.1'
        Using vendor aar 'com.android.support:design:23.2.1'
        [app.login] split library res files...                          [  OK  ]
        [app.login] slice asset package and reset package id...         [  OK  ]
        [app.login] split library R.java files...                       [  OK  ]
        [app.login] split R.class...                                    [  OK  ]
        -> armeabi/libcom_app_login.so (1364745 bytes = 1.3 MB)

## 你做了什么？
gradlew cleanBundle

gradlew buildBundle -q

 gradle-small plugin : 1.3.0-beta5 (maven)
            small aar : 1.3.0-beta5 (maven)
          gradle core : 3.3
       android plugin : 2.3.3
                   OS : Windows 7 6.1 (amd64)

dependencies {
//        classpath 'com.android.tools.build:gradle:3.0.0'
        classpath 'com.android.tools.build:gradle:2.3.0'

其中插件中有依赖：
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.2.1'
    compile 'com.android.support:design:23.2.1'

### Bundles结果：

| type |   name    |  PP  | sdk |  aapt  | support | file(armeabi) |  size  |
|------|-----------|------|-----|--------|---------|---------------|--------|
| host | app       |      | 26  | 26.0.2 | 26.1.0  |               |        |
| app  | app.login | 0x44 | 26  | 26.0.2 | 26.1.0  | *_login.so    | 1.7 MB |

其中插件中有依赖：
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.2.1'
    compile 'com.android.support:design:23.2.1'

## 你期望的结果是什么？
Small能够正确编译数据绑定

## 实际结果是什么？
D:\Android\osChinaSpace\MySmall>gradlew buildBundle -q
  Small building bundle 1 of 1 - app.login (0x44)
        Using vendor aar 'com.android.support:appcompat-v7:23.2.1'
        Using vendor aar 'com.android.support:design:23.2.1'
        [app.login] split library res files...                          [  OK  ]
        [app.login] slice asset package and reset package id...         [  OK  ]
        [app.login] split library R.java files...                       [  OK  ]
        [app.login] split R.class...                                    [  OK  ]
        -> armeabi/libcom_app_login.so (1364745 bytes = 1.3 MB)

## Small环境

gradlew buildBundle -q
  Small building bundle 1 of 1 - app.login (0x44)
        Using vendor aar 'com.android.support:appcompat-v7:23.2.1'
        Using vendor aar 'com.android.support:design:23.2.1'
        [app.login] split library res files...                          [  OK  ]
        [app.login] slice asset package and reset package id...         [  OK  ]
        [app.login] split library R.java files...                       [  OK  ]
        [app.login] split R.class...                                    [  OK  ]
        -> armeabi/libcom_app_login.so (1364745 bytes = 1.3 MB)

**Comment by galenlin** [comment]
这是编译警告信息，你可以把 appcompat， design 包放到宿主里或宿主分身模块中，解决该问题。
