### ISSUE TITLE
为什么要把 library 替换成 application 呢？

### ISSUE THREAD

**Issue by lrhehe** [wequick/Small#59]
如题，看代码没看明白
在 LibraryPlugin.groovy 的 configureProject() 中
```
def text = project.buildFile.text.replaceAll(
                    'com\\.android\\.library', 'com.android.application')
```

**Comment by galenlin** [comment]
因为lib.\*在开发时以**library**模块存在，方便相互引用。在发布时则需要打包成一个独立插件，以使得可独立更新，故在assembleRelease时动态切换成**application**。

详见：[Gradle-small-plugin](https://github.com/wequick/Small/tree/master/Android/DevSample/buildSrc)
