### ISSUE TITLE
关于插件后缀名和插件存储位置的疑问？

### ISSUE THREAD

**Issue by lrhehe** [wequick/Small#61]
1. 为什么以 so 为后缀名呢？ 
    从结构上看更像是apk
2. 为什么要放在 armbi 中呢？
    安装程序的时候会把这些文件放到应用程序缓存中，那么可以放在 assets 里面，在宿主打开的时候把文件复制到应用程序缓存

**Comment by galenlin** [comment]
其实1是为了2，用so的好处时，解压过程在安装时，用户感知小；而assets是在启动应用时。同时，在重装时如果是用assets，自己要处理文件是否有更新等逻辑再行复制。

**Comment by peacepassion** [comment]
这两个好处令人信服。但是，这就可能导致打出的包为了支持多种架构，增加不少体积。
