### ISSUE TITLE
新建lib.* 4.4.4报错：java.lang.ArrayIndexOutOfBoundsException at android.content.res.AssetManager.getPooledString

### ISSUE THREAD

**Issue by harry2008** [wequick/Small#62]
roidRuntime(11134): Process: net.wequick.example.small, PID: 11134
E/AndroidRuntime(11134): java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wequick.example.small/net.wequick.small.A}: android.view.InflateException: Binary XML file line #18: Error inflating class <unknown>
E/AndroidRuntime(11134): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2197)
E/AndroidRuntime(11134): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
E/AndroidRuntime(11134): 	at android.app.ActivityThread.access$800(ActivityThread.java:143)
E/AndroidRuntime(11134): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1209)
E/AndroidRuntime(11134): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11134): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(11134): 	at android.app.ActivityThread.main(ActivityThread.java:5120)
E/AndroidRuntime(11134): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(11134): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(11134): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
E/AndroidRuntime(11134): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
E/AndroidRuntime(11134): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(11134): Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class <unknown>
E/AndroidRuntime(11134): 	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
E/AndroidRuntime(11134): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
E/AndroidRuntime(11134): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/AndroidRuntime(11134): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
E/AndroidRuntime(11134): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
E/AndroidRuntime(11134): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime(11134): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime(11134): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
E/AndroidRuntime(11134): 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
E/AndroidRuntime(11134): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
E/AndroidRuntime(11134): 	at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:53)
E/AndroidRuntime(11134): 	at android.app.Activity.performCreate(Activity.java:5351)
E/AndroidRuntime(11134): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime(11134): 	at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:148)
E/AndroidRuntime(11134): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2161)
E/AndroidRuntime(11134): 	... 11 more
E/AndroidRuntime(11134): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(11134): 	at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime(11134): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
E/AndroidRuntime(11134): 	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
E/AndroidRuntime(11134): 	... 25 more
E/AndroidRuntime(11134): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=9; index=9
E/AndroidRuntime(11134): 	at android.content.res.AssetManager.getPooledString(AssetManager.java:291)
E/AndroidRuntime(11134): 	at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:727)
E/AndroidRuntime(11134): 	at android.content.res.TypedArray.getValueAt(TypedArray.java:712)
E/AndroidRuntime(11134): 	at android.content.res.TypedArray.getColorStateList(TypedArray.java:342)
E/AndroidRuntime(11134): 	at android.support.v7.widget.ThemeUtils.getThemeAttrColorStateList(ThemeUtils.java:76)
E/AndroidRuntime(11134): 	at android.support.v7.widget.TintManager.getTintList(TintManager.java:314)
E/AndroidRuntime(11134): 	at android.support.v7.widget.TintManager.getDrawable(TintManager.java:183)
E/AndroidRuntime(11134): 	at android.support.v7.widget.TintManager.getDrawable(TintManager.java:168)
E/AndroidRuntime(11134): 	at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:62)
E/AndroidRuntime(11134): 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:257)
E/AndroidRuntime(11134): 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:199)
E/AndroidRuntime(11134): 	... 28 more
E/OppoPhoneWindow(  897): OppoPhoneWindow

**Comment by harry2008** [comment]
OPPO A31 Android 4.4.4 系统，m1 note Android 4.4.4 系统有问题；
Nexus 6 Android 5.1.1 系统 没有问题该问题

**Comment by harry2008** [comment]
估计是 和 4.4 的系统有关系，因为 在 4.4 中 android.content.res.AssetManager 才会存在 ：getPooledString 方法，5.0 以后 都用 getPooledStringForCookie 替换了

**Comment by xiaoxinxing12** [comment]
同样遇到此问题，有解决办法了吗？

**Comment by xiaoxinxing12** [comment]
把自己的代码复制到Sample里的lib.* 4.4就不报错了
原因还不明

**Comment by galenlin** [comment]
@harry2008 @xiaoxinxing12 今天偶然复现了这个bug，发现如果某个插件编译后不存在resources.arsc在4.x版本会出现该报错。你们可以按这个思路验证下。

这个bug尝试了解决了下，预计下周发布fix。

**Comment by galenlin** [comment]
gradle-small:0.9.0 已解决，关闭本问题

**Comment by weixinfree** [comment]
我们遇到了同样的问题，但是没有使用咱们的small框架，请教下这个问题的根因是？

**Comment by ThugKd** [comment]
> 我们遇到了同样的问题，但是没有使用咱们的small框架，请教下这个问题的根因是？

我也遇到了，大佬解决了吗？
