### ISSUE TITLE
插件代码中对公共Lib中颜色资源的引用值出现错误

### ISSUE THREAD

**Issue by trisiffer** [wequick/Small#63]
插件中在JAVA代码中使用公共Lib中颜色值时，com,xx,xx,lib.xx.R.color.xx 获取到lib中的颜色值被改为 7F - 0B002E ,而不是原有的插件的资源分区的前缀如73 - xxxxxx，导致颜色取值失败。

**Comment by galenlin** [comment]
已不完美解决：在app模块中可以使用 _\*.lib.xx.R.\*_ 来取得lib插件的资源。
直接使用 _R.\*_ 的方式实现方式较麻烦且增加编译步骤，现暂不考虑。
