### ISSUE TITLE
出现问题“you need a Appcompat Theme"

### ISSUE THREAD

**Issue by Brooks0129** [wequick/Small#67]
1.运行时报错： 
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.brooks.smalldemo/net.wequick.small.A}: 
       java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
2.或者报错：
android.content.res.Resouces$NotFoundException:Resouse ID **********
而该id就是对应着插件的布局文件

可能的解决方案：

1. com.android.support:appcompat-v7版本使用的是23.2.1，改成23.1.1应该就好了

2. 将style抽取出一个library，让插件依赖这个library,一定要抽取干净，也就是说插件里就不需要style.xml了

**Comment by galenlin** [comment]
前因后果、群里讨论的当前可用的解决方案也在这做个记录吧。方便后来人看。

我再想想更好的方案。

**Comment by leohan1992** [comment]
资源ID报错时把我对应的Module build了一下就好了

**Comment by galenlin** [comment]
问题原因：
23.2+ AppCompatActivity重载了getResources函数：
```java
@Override
public Resources getResources() {
    if (mResources == null) {
        mResources = new TintResources(this, super.getResources());
    }
    return mResources;
}
```
导致我们反射修改的mResources失效。

解决办法：
通过反射对`AppCompatActivity`的`mResources`属性进行修改，赋值为null。
当系统再次调用其`getResources()`方法时，语句
```java
mResources = new TintResources(this, super.getResources());
```
被重新执行，而此时传入的`super.getResources()`已经是我们处理过的`ResourcesMerger`对象，从而保证插件资源查找正确。

**Comment by parcool** [comment]
玩这个2天了，填了不下10个坑了。到现在还报这个错：`Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.`
`lib.style`也单独出来了，也改为23.1.1，也反射试过了，还是不行。另外，我还有个SPUtil也是报找不到类的错误。

总之，千奇百怪的错误。就算把这2个错误解决了，也感觉后面还有100多个错误需要再到处搜索解决。Q群里也没人说话，提issues也没人回答。想放弃的感觉，毕竟时间很短。。。

**Comment by wcfred** [comment]
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity这个问题解决了吗？
