### ISSUE TITLE
Working with Android 5.0 Shared Library Resource Support

### ISSUE THREAD

**Issue by baoti** [wequick/Small#68]
Android 5.0 新增 SharedLibrary 支持，在 AndroidManifest.xml 中声明 <use-library ... /> 或者在 build.gradle 中声明 useLibrary 将使用到此特性。

aapt 也包含相关的命令行选项 --shared-lib ，可用于生成 packageId 为 0 的资源包，将会在运行时动态设置。

你觉得这个特性会不会与 Small 的组件资源相冲突？
这个特性能否用来改善组件apk的构建与运行时加载的方式？

**Comment by baoti** [comment]
另外，有没有更好的方式来实现组件资源的分离？ Small-Gradle-Plugin 好像复杂了一些。
能否借助于 Apktool 这样的一些工具来简化？

能否针对组件资源的拆分方式，对几个插件框架进行对比？

**Comment by baoti** [comment]
[Shared library resource support](https://github.com/android/platform_frameworks_base/commit/de898ff42912bd7ca1bfb099cd439562496765a4#diff-7d1ce6b79d49595427b7e9fe15778a4bR1162)
[Fix regression generating dynamic ref table for shared libraries](https://github.com/android/platform_frameworks_base/commit/6022debdbcc4498736580640c6287b57872617a2)

**Comment by galenlin** [comment]
感谢@baoti的持续关注，以及认真的分析与提供建议! :+1: 

1. shared-lib的方式似乎有局限。

  * Currently, shared libraries should not import other shared libraries,
    as those dependencies will not be loaded at runtime.

  > 公共库之间不能相互依赖。

  * At runtime, reflection is used to update the package ID of resource
    symbols in the shared library's R class file. The package name of
    the R class file is assumed to be the same as the shared library's
    package name declared in its manifest. This will be customizable in
    a future commit.

  > 运行时，通过反射来更新公共库的R文件？代码级别的分离，离资源完美分区还差太多。

  * 不过在适配5.0的过程中，我们倒是用到了这个特性的DynamicRefTable部分。

2. gradle-small 足够简洁、实用、并且对用户透明。

  * 它并不复杂，至少相对你提到的apktool等第三方工具来说要简洁的多。 除去为了保障开发透明性的逻辑。其核心逻辑为**“重设package id, 对资源加以过滤，留下插件自身res目录下的资源”**。
  * 同时它也并不简单，业内首创「工程内公共库」- lib.\*模块，使得公共库可以独立更新。这其中的逻辑Small专有、并经过一段时间的有效验证。并不是「某个工具」能够愉快的拿来直接用的。
  * 更多细节，如果你没看过的话，可以参考[这里](https://github.com/wequick/Small/tree/master/Android/DevSample/buildSrc)。

3. 资源ID为0xPPTTNNNN，拆分方式无外乎PP、TT、NNNN三种。[wiki](https://github.com/wequick/Small/wiki/Android-dynamic-load-resources)上已经有部分说明与分析。

**Comment by baoti** [comment]
其实昨天刚分析完 Small 的 Gradle 插件源码，之前已经分析运行时加载的代码。之后会再去分析 ACDD 和 Android-Plugin-Framework。它们的代码也一直都在更新。

Small 中确实有很多好的点子，独树一帜。

对于 SharedLibrary ，我喜欢它跨包引用资源的方式：[layout xml](https://github.com/android/platform_frameworks_base/blob/master/tests/SharedLibrary/client/res/layout/main.xml)

> 运行时，通过反射来更新公共库的R文件？

[源码](https://github.com/android/platform_frameworks_base/blob/master/core/java/android/app/LoadedApk.java#L634)
当然，ResourceTable 也要在运行时进行调整。

我觉得 SharedLibrary 可以导向另一条不一样的路。

**Comment by galenlin** [comment]
:+1: 
SharedLibrary可以继续关注下
