### ISSUE TITLE
 error creating cache file /data/data/net.wequick.example.small/cache/com.android.opengl.shaders_cache: No such file or directory (2)

### ISSUE THREAD

**Issue by xujinyang** [wequick/Small#69]
error creating cache file /data/data/net.wequick.example.small/cache/com.android.opengl.shaders_cache: No such file or directory (2)

跑起来就崩溃了，这是什么鬼？

**Comment by galenlin** [comment]
跑的Sample吗？还是自己新建的工程，是否设置签名了。

**Comment by xujinyang** [comment]
搞定了，是因为我没有编译，得先执行
gradle buildLib -q
gradle buildBundle -q

完事就可以执行了

请问现在有线上的app用了这个方案么？
