### ISSUE TITLE
 java.lang.NegativeArraySizeException (no error message)

### ISSUE THREAD

**Issue by ayou6232290** [wequick/Small#71]
Error:Execution failed for task ':app.main:processReleaseResources'.
> java.lang.NegativeArraySizeException (no error message)

这种情况会可能是那种情况引起的?

**Comment by galenlin** [comment]
自己建的工程吗？gradle-small的版本是多少，用--stracetrace打印下详细错误

**Comment by ayou6232290** [comment]
引用了一些第三方库引起的异常,我再研究研究

**Comment by peacepassion** [comment]
我也遇到了这个问题，我尝试重现一下
