### ISSUE TITLE
插件有办法如何通过网络后期加载进来并且可以更新

### ISSUE THREAD

**Issue by leohan1992** [wequick/Small#72]
我直接openUri打开插件的so文件是不可行的，具体该怎么样做呢

**Comment by galenlin** [comment]
更新插件请参考Sample app.home

**Comment by leohan1992** [comment]
目前不太会这种联合开发，而且我这水平也不敢跟着凑热闹，不过倒是有个思路。我经过一天的试验，最一开始的思路是把编译出来的.so文件直接放入data/data/包名/lib目录下，提前在bundle.json文件中声明。当需要加载的时候去判断目录下有没有该.so文件，没有加下载一个，就加载了，有就看看要不要更新。可后来发现lib文件夹不可写。。。转变思路就是全部使用更新的方式，我把更新的时候简化了，直接就调了里面必须有的方法，其他的省略了，最后发现更新是要比较版本的，可以前没有.so文件，所以会发生空指针。到了这一步我的想法是只要比较的时候能把空指针解决掉，让他能加载small_patch下的.so文件，即便是重启后生效，也算后期加载实现了吧。

**Comment by galenlin** [comment]
客气了，没有人天生会的。随时欢迎您在Small做开源实践。

从你的描述来看，确实需要框架内部做些调整，这周我会看下，做个尝试。

**Comment by leohan1992** [comment]
现在动态添加实现了吗

**Comment by galenlin** [comment]
已经实现挺久了呀，你可以更新Sample来感受下~

**Comment by leohan1992** [comment]
好的~我是今天收到issue关闭的邮件，才看的，有一段时间没关注了
