### ISSUE TITLE
android的UI文档与实际开发情况对不上，bundle.json中uri必须加上后缀*Activity不然不能引用

### ISSUE THREAD

**Issue by lucifdch** [wequick/Small#77]
bundle.json内貌似得写全名，HomeThreeActivity后边的Activity删除了的话我这儿是找不到ACTIVITY的，和文档不一样，文档中"three":".HomeThree"实测后边必须添加*Activity即"three":".HomeThreeActivity"。

Version:0.6
Anroid version:22、23、24，x86模拟器

**Comment by galenlin** [comment]
DevSample已解决，aar待发布。
