### ISSUE TITLE
实测插件不能携带so进行更新

### ISSUE THREAD

**Issue by lucifdch** [wequick/Small#79]
so文件必须放在宿主的smallLibs下，且实测不能通过更新宿主的方式（即在bundle.json下写上so的pkg）进行更新。
即so文件若要更新只能升级宿主，步骤较为繁琐。

**Comment by lrhehe** [comment]
so文件本质上和插件是一样的，所以也能支持动态更新，只不过目前作者没支持
可以加个逻辑，下载新的 so，直接替换掉原来的就可以

so 文件动态更新有不少解决方案，可以找找看，根据自己需要加进来
