### ISSUE TITLE
如果默认系统的Java版本是Java8，编译Sample会失败 Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by xzstar** [wequick/Small#8]
应该是build gradle-small-plugin的时候用了java8生成包，android build系统只支持到7.
建议在文档里加一个说明
如果碰到这种情况 需要在gradle-small-plugin的 build.gradle指定一下java6或者java7
sourceCompatibility = 1.7

**Comment by galenlin** [comment]
就以此issue为文档了，closing.

**Comment by never615** [comment]
我的环境都是java8，没有遇到问题。

**Comment by bajiecjh** [comment]
我的电脑都没安装java8的，为什么会遇到这个问题
