### ISSUE TITLE
插件依赖AAR的疑问

### ISSUE THREAD

**Issue by peacepassion** [wequick/Small#81]
AppLugin.groovy有段如下代码，
![image](https://cloud.githubusercontent.com/assets/5254121/14097531/ac24006c-f5a4-11e5-82b7-54fc47751dea.png)

其目的是在dex之前将exploaded-aar改名，让插件依赖的aar中的代码不会被打进插件so里面。

请问这样做的目的是什么？

**Comment by galenlin** [comment]
设计上aar公共库只需在宿主依赖，插件模块专注自身的业务逻辑。

**Comment by peacepassion** [comment]
这样的目的确实很好，插件之间共享的依赖只保留一份。

但这样处理有个问题，如果插件compile依赖一个aarA，这个aarA确实不会被打进so，但是，如果这个aarA有依赖一个jarB，这个jarB就会被打进so。如果我同时也在host里面compile依赖aarA，host apk也会打进一个jarB，这样就会有问题的。

**Comment by galenlin** [comment]
soga，可否提供下这个示例，方便调试下

**Comment by peacepassion** [comment]
@galenlin 请参考https://github.com/peacepassion/allinonetry
注意app.mine/build.gradle的依赖

**Comment by galenlin** [comment]
thx, got it

**Comment by galenlin** [comment]
确认问题，准备处理如下：
1. 不含资源的aar：如果宿主存在，把深层次的依赖也分离。
2. 包含资源的aar：增加强制写入模式，允许插件加入第三方资源

**Comment by peacepassion** [comment]
1. 解析深层次依赖想必不容易呢，需要解析aar里面的pom.xml，然后可能还要递归的解析；
2. 允许插件引入第三方的资源确实有用，比如说只有一个插件引入了特定的aar依赖；但我觉得这个处理起来也未必简单，但是提个我个人的思路： buildLib的时候已经把lib提供的provided依赖都解析出来了，这样，在处理bundle的时候，可以将bundle自身依赖或者递归依赖的jar与哪些provided依赖做对比，如果provided的没有，就保留，否则，就删除，至于版本冲突的问题，可以强制做个替换等。

**Comment by peacepassion** [comment]
这样带来一个好处，可以解放host的压力。host的方法数几乎不可能超出限制了。

**Comment by galenlin** [comment]
对的，有点复杂，，

**Comment by galenlin** [comment]
gradle-small 0.4.0 已支持，@peacepassion 如果可以了 请告知下

**Comment by peacepassion** [comment]
确认问题，准备处理如下：
1. 不含资源的aar：如果宿主存在，把深层次的依赖也分离。
2. 包含资源的aar：增加强制写入模式，允许插件加入第三方资源

@galenlin 感谢支持。
已经测试完毕，但对2有个疑问
如果bundle依赖了一个aar，同时开启了强制写入模式，这个时候，会把aar的资源打入bundle中，但jar仍然被抛弃了，bundle依然无法使用这个aar， 这个强制写入模式就没有什么意义了

**Comment by galenlin** [comment]
有道理，这个应该是疏忽了，我再看看

**Comment by peacepassion** [comment]
@galenlin 现在依赖的aar中的jar确实已经打进包里，但是jar中间少了一个很重要的类，aar的R.java.比如说，host没有依赖v7，lib 或者 bundle依赖了一个v7,打出的so少了app.support.v7.R.java这个文件。

**Comment by peacepassion** [comment]
我也在找原因，目前的实现已经很棒了，如果能把这个bug解掉，lib/bundle的aar依赖就算可用了。

**Comment by peacepassion** [comment]
![image](https://cloud.githubusercontent.com/assets/5254121/14732197/d69a67de-088a-11e6-9740-7461b6efa74a.png)

**Comment by galenlin** [comment]
额，这个确实是这个地方删除掉了，看来还得折腾一下，根据包名过滤

**Comment by peacepassion** [comment]
@galenlin 不仅是包名过滤，还要把内容给改了，因为默认生成的是0x7f开头的。

我周末先尝试解决一下吧。 😃

**Comment by galenlin** [comment]
@peacepassion ok :+1:

**Comment by peacepassion** [comment]
@galenlin  经过研究，准备处理如下：
直接将lib/bundle生成的R复制一份覆盖掉aar自动生成的R.java，同时，将R.java的包名修改掉即可。

这样处理比较简单，因为aar不会导出响应的R.txt，再针对不同的aar做细分的话，相当的麻烦。而且，也没有必要。

**Comment by galenlin** [comment]
@peacepassion 在`exploded-aar`目录里找到了各aar的`R.txt`，基于此生成了各个深层次依赖aar的`R.java`。
