### ISSUE TITLE
插件添加第三方jar包，编译报错

### ISSUE THREAD

**Issue by nj-code-hub** [wequick/Small#84]
在插件libs下添加了第三方sdk jar包， buildBundle报错
Error processing E:\Android\SmallDemo\**\sdk.jar: **.class: broken class file?

另外，demo里面也没有相关的例子，不知道插件化开发对第三方jar的使用，如何实现？还是和非插件化时没有区别？

**Comment by galenlin** [comment]
Sample `app.mine`已添加插件内引用jar示例，并未发现异常。烦请对比参看下是否是工程设置问题？

**Comment by nj-code-hub** [comment]
我把报错的部分单独打个了jar包，之前的一个jar包变成两个jar包，然后可以使用了......
好诡异的问题！！！

**Comment by galenlin** [comment]
囧。。
