### ISSUE TITLE
插件packageInfo, activityInfo获取加速

### ISSUE THREAD

**Issue by galenlin** [wequick/Small#91]
现阶段使用`packageManager.getPackageArchiveInfo`收集插件packageInfo/activityInfo，该方法会同时解析收集插件包：

* services
* providers
* permissions

等信息。

为提高性能，拟通过实现`PackageParser. parseApplication`阉割版本加速二者获取过程。

**Comment by lixf078** [comment]
怎么启动一个Service呀？

**Comment by galenlin** [comment]
@lixf078 你这还是单独提个issue吧。。
