### ISSUE TITLE
设置透明背景的Activity无效

### ISSUE THREAD

**Issue by brady9308** [wequick/Small#94]
Activity的style设置了如下配置，没有透明效果
```xml
<item name="android:windowBackground">@android:color/transparent</item>
<item name="android:windowIsTranslucent">true</item>
```

**Comment by peacepassion** [comment]
@brady9308 试下这个？
```xml
  <style name="Theme.FullScreen" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:windowContentOverlay">@null</item>
    <item name="android:windowIsTranslucent">true</item>
    <item name="android:windowBackground">@android:color/transparent</item>
    <item name="android:backgroundDimEnabled">false</item>
  </style>
```

**Comment by brady9308** [comment]
直接修改app.detail下的style
```xml
<style name="MyAppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorLight</item>
        <item name="android:backgroundDimEnabled">false</item>
        <item name="android:windowContentOverlay">@null</item>
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:windowBackground">@android:color/transparent</item>
</style>
```
ActionBar依然存在效果没用上？估计插件引用上的问题吧

**Comment by peacepassion** [comment]
@brady9308 是不是透明效果已经OK了？我这边NoActionBar是有效的

**Comment by brady9308** [comment]
gradle1.5.0上编译出错，切换到2.0.0 rc3一切正常，NoActionBar有效，背景透明效果效果应该是有，但是黑色背景而不是上一页Activity背景

**Comment by peacepassion** [comment]
@brady9308 是黑色背景而不是上一页Activity背景肯定有问题，你可以对比一下独立运行的结果

**Comment by peacepassion** [comment]
但按照我的理解，主题方面，Small应该是没什么问题的。

**Comment by brady9308** [comment]
测试了，单独运行没问题，发现app:detail的launchMode为singleInstance本以为启动模式的问题，取消了设置也是黑色背景，看过其他的貌似透明Activity需要特殊处理

**Comment by brady9308** [comment]
APF和DPG在这方面没问题，而[android-pluginmgr](https://github.com/houkx/android-pluginmgr/)也存在黑色背景的问题，我认为问题在于`<activity android:name=".A" android:launchMode="standard"/>`我们只预先注册一个standard模式的问题，应该注册两个或多个轮流跳转，只是直觉没去考究

**Comment by brady9308** [comment]
@peacepassion 顺带一提，通过Intent以Serializable形式传递ArrayList，APF反序列化没问题，DPG和plugiinmgr等反序列化为null，不知道Small是否也有这问题，还未测试过

**Comment by 4gg** [comment]
@brady9308 运用Small框架的时候研究过这个问题，动态的在代码中设置theme透明与不透明是无效的，所以可以在宿主中预埋一个透明的activity，挑选代理activity的时候选择透明的activity就可以解决该问题

**Comment by galenlin** [comment]
@wu4321 测试下看看

**Comment by peacepassion** [comment]
@brady9308  http://stackoverflow.com/questions/31992147/android-dialog-activity-theme-androidtheme-vs-settheme

Small是调用了setTheme()把插件的主题设置到stub activity中的，这个时候，或许已经无法改变window的若干属性了。

我测试了正常的app，manifest里面声明了非透明的theme，在Activity#onCreate()中setTheme()为透明的主题，也是显示黑色的背景。

**Comment by wu4321** [comment]
@galenlin 插件activity透明主题透明位置变黑色

**Comment by galenlin** [comment]
@all 非标准模式 (singleTask / singleInstance / singleTop) 的Activity是否需要支持透明？

**Comment by brady9308** [comment]
都支持下比较好吧，不敢保证透明Activity一定是标准模式

**Comment by galenlin** [comment]
@brady9308 目前的做法是预置两个标准模式：一个透明，一个不透明。程序中做动态选择。(see d9924e9) 

考虑稳定性与快速迭代，先满足标准模式。后期有需要再调整。

**Comment by xiaweizi** [comment]
请问客户端应该怎么处理呢？

**Comment by xiaweizi** [comment]
@galenlin
